// ── Local Fly Shops by Region ──────────────────────────────────────────────────
// Curated independent fly shops, real shops, real addresses

export interface FlyShop {
  name: string;
  city: string;
  state: string;
  address: string;
  phone: string;
  website: string;
  notes: string;              // one-line character note
  rivers: string[];           // rivers they know best
  lat: number;
  lng: number;
}

export const flyShopsByRegion: Record<string, FlyShop[]> = {
  montana_rockies: [
    {
      name: "Madison River Fishing Company",
      city: "Ennis",
      state: "MT",
      address: "109 Main St, Ennis, MT 59729",
      phone: "(406) 682-4293",
      website: "https://www.mrfc.com",
      notes: "The definitive Madison shop, guides, gear, and daily hatch reports since 1994.",
      rivers: ["Madison River", "Gallatin River", "Missouri River"],
      lat: 45.3494, lng: -111.7316,
    },
    {
      name: "Gallatin River Guides",
      city: "Big Sky",
      state: "MT",
      address: "47650 Gallatin Rd, Big Sky, MT 59716",
      phone: "(406) 995-2290",
      website: "https://www.montanaflyfishing.com",
      notes: "Best source for Gallatin Canyon conditions, especially summer caddis and hopper season.",
      rivers: ["Gallatin River", "Madison River"],
      lat: 45.2844, lng: -111.3817,
    },
    {
      name: "Headhunters Fly Shop",
      city: "Craig",
      state: "MT",
      address: "101 Bridge St, Craig, MT 59648",
      phone: "(406) 235-4165",
      website: "https://www.headhuntersflyshop.com",
      notes: "Missouri River specialists, unmatched local knowledge of the tailwater below Holter Dam.",
      rivers: ["Missouri River", "Smith River"],
      lat: 47.0108, lng: -111.6025,
    },
    {
      name: "Dan Bailey's Fly Shop",
      city: "Livingston",
      state: "MT",
      address: "209 W Park St, Livingston, MT 59047",
      phone: "(406) 222-1673",
      website: "https://www.danbaileys.com",
      notes: "One of the oldest fly shops in the West, legendary Yellowstone River expertise since 1938.",
      rivers: ["Yellowstone River", "Boulder River", "Stillwater River"],
      lat: 45.6627, lng: -110.5593,
    },
    {
      name: "East Slope Anglers",
      city: "Choteau",
      state: "MT",
      address: "120 Main Ave N, Choteau, MT 59422",
      phone: "(406) 466-2321",
      website: "#",
      notes: "Gateway to the Rocky Mountain Front, cutthroat and whitefish in remote wilderness drainages.",
      rivers: ["Teton River", "Sun River", "Blackfoot River"],
      lat: 47.8127, lng: -112.1836,
    },
  ],

  pacific_northwest: [
    {
      name: "The Fly Fisher's Place",
      city: "Sisters",
      state: "OR",
      address: "151 W Main Ave, Sisters, OR 97759",
      phone: "(541) 549-3474",
      website: "https://www.flyfish.com",
      notes: "Premier Metolius and Deschutes shop, cult following for their weekly river condition updates.",
      rivers: ["Metolius River", "Deschutes River", "Crooked River"],
      lat: 44.2907, lng: -121.5490,
    },
    {
      name: "The Deschutes Canyon Fly Shop",
      city: "Maupin",
      state: "OR",
      address: "599 S Deschutes Ave, Maupin, OR 97037",
      phone: "(541) 395-2565",
      website: "https://www.deschutescanyon.com",
      notes: "The original canyon outpost, if you're fishing Maupin, you stop here first.",
      rivers: ["Deschutes River"],
      lat: 45.1779, lng: -121.0807,
    },
    {
      name: "Kaufmann's Streamborn",
      city: "Portland",
      state: "OR",
      address: "8861 SW Commercial St, Tigard, OR 97223",
      phone: "(503) 639-6400",
      website: "https://www.kman.com",
      notes: "Pacific Northwest institution, huge selection, expert staff, and Northwest-specific pattern library.",
      rivers: ["Sandy River", "Clackamas River", "Deschutes River"],
      lat: 45.4254, lng: -122.7739,
    },
    {
      name: "Patrick's Fly Shop",
      city: "Seattle",
      state: "WA",
      address: "2237 Eastlake Ave E, Seattle, WA 98102",
      phone: "(206) 325-8988",
      website: "https://patricksflyfishing.com",
      notes: "Seattle's go-to shop for Puget Sound, Olympic Peninsula, and BC steelhead intel.",
      rivers: ["Skagit River", "Sauk River", "Hoh River"],
      lat: 47.6424, lng: -122.3269,
    },
  ],

  northeast: [
    {
      name: "Catskill Flies",
      city: "Roscoe",
      state: "NY",
      address: "Main St, Roscoe, NY 12776",
      phone: "(607) 498-6146",
      website: "https://www.catskillflies.com",
      notes: "In the heart of Catskill tradition, Beaverkill and Willowemoc experts, classic wet fly patterns.",
      rivers: ["Beaverkill River", "Willowemoc Creek", "Delaware River"],
      lat: 41.9390, lng: -74.9080,
    },
    {
      name: "Dette Flies",
      city: "Roscoe",
      state: "NY",
      address: "9 Stewart Ave, Roscoe, NY 12776",
      phone: "(607) 498-4991",
      website: "https://www.detteflies.com",
      notes: "Three generations of Catskill fly tying, hand-tied classics from the Dette family since the 1920s.",
      rivers: ["Beaverkill River", "Willowemoc Creek"],
      lat: 41.9396, lng: -74.9073,
    },
    {
      name: "Orvis Manchester",
      city: "Manchester",
      state: "VT",
      address: "4180 Main St, Manchester, VT 05254",
      phone: "(802) 362-3750",
      website: "https://www.orvis.com/manchester",
      notes: "The flagship Orvis store, fishing school, casting pond, and the original Orvis retail experience.",
      rivers: ["Battenkill River", "Mettawee River"],
      lat: 43.1609, lng: -73.0674,
    },
    {
      name: "West Branch Angler",
      city: "Deposit",
      state: "NY",
      address: "150 Faulkner Rd, Deposit, NY 13754",
      phone: "(607) 467-5525",
      website: "https://www.westbranchangler.com",
      notes: "Best access point for the West Branch Delaware, daily flow and hatch reports all season.",
      rivers: ["Delaware River (West Branch)", "East Branch Delaware"],
      lat: 42.0468, lng: -75.4327,
    },
  ],

  appalachian_east: [
    {
      name: "TCO Fly Shop, State College",
      city: "State College",
      state: "PA",
      address: "2030 E College Ave, State College, PA 16801",
      phone: "(814) 689-3654",
      website: "https://www.tcoflyfishing.com",
      notes: "Pennsylvania limestone country specialists, Spring Creek, Penn's Creek, and Fishing Creek Intel.",
      rivers: ["Spring Creek", "Penns Creek", "Bald Eagle Creek"],
      lat: 40.7924, lng: -77.8474,
    },
    {
      name: "Little River Outfitters",
      city: "Townsend",
      state: "TN",
      address: "7807 E Lamar Alexander Pkwy, Townsend, TN 37882",
      phone: "(865) 448-9459",
      website: "https://www.littleriveroutfitters.com",
      notes: "Gateway to Great Smoky Mountains wild trout fishing, brook, brown, and rainbow in pristine streams.",
      rivers: ["Little River", "Abrams Creek", "Middle Prong"],
      lat: 35.6896, lng: -83.7413,
    },
    {
      name: "Mossy Creek Fly Fishing",
      city: "Harrisonburg",
      state: "VA",
      address: "4870 Rawley Pike, Harrisonburg, VA 22801",
      phone: "(540) 434-2444",
      website: "https://www.mossycreekflyfishing.com",
      notes: "Shenandoah Valley limestone creek specialists, Mossy Creek and the Jackson River.",
      rivers: ["Mossy Creek", "Jackson River", "Shenandoah River"],
      lat: 38.4240, lng: -79.0128,
    },
  ],

  southeast: [
    {
      name: "Cohutta Fishing Company",
      city: "Blue Ridge",
      state: "GA",
      address: "7752 Blue Ridge Dr, Blue Ridge, GA 30513",
      phone: "(706) 258-0867",
      website: "https://www.cohuttafishing.com",
      notes: "North Georgia mountain trout shop, Toccoa tailwater and Chattahoochee headwaters expertise.",
      rivers: ["Toccoa River", "Chattahoochee River", "Jacks River"],
      lat: 34.8618, lng: -84.3240,
    },
    {
      name: "Davidson River Outfitters",
      city: "Pisgah Forest",
      state: "NC",
      address: "49 Pisgah Hwy, Pisgah Forest, NC 28768",
      phone: "(828) 877-4181",
      website: "https://www.davidsonflyfishing.com",
      notes: "Davidson River, North Carolina's blue-ribbon wild trout stream. Best sulphur shop in the Southeast.",
      rivers: ["Davidson River", "South Mills River", "French Broad River"],
      lat: 35.2694, lng: -82.6890,
    },
    {
      name: "Unicoi Outfitters",
      city: "Helen",
      state: "GA",
      address: "7120 S Main St, Helen, GA 30545",
      phone: "(706) 878-3083",
      website: "https://www.unicoioutfitters.com",
      notes: "Alpine Helen base camp for the Chattahoochee headwaters, German village setting, serious trout fishing.",
      rivers: ["Chattahoochee River", "Soque River"],
      lat: 34.7001, lng: -83.7269,
    },
  ],

  great_lakes: [
    {
      name: "Gates' Au Sable Lodge",
      city: "Grayling",
      state: "MI",
      address: "471 Stephan Bridge Rd, Grayling, MI 49738",
      phone: "(989) 348-8462",
      website: "https://www.gateslodge.com",
      notes: "The soul of Au Sable fly fishing, Holy Water access, hex hatch headquarters, and a legendary tying bench.",
      rivers: ["Au Sable River", "North Branch Au Sable"],
      lat: 44.6564, lng: -84.7058,
    },
    {
      name: "Pere Marquette River Lodge",
      city: "Baldwin",
      state: "MI",
      address: "8841 S M-37, Baldwin, MI 49304",
      phone: "(231) 745-3972",
      website: "https://www.steelheadcountry.com",
      notes: "Pere Marquette specialists since 1945, steelhead in fall and spring, browns in summer.",
      rivers: ["Pere Marquette River", "Little Manistee River"],
      lat: 43.8898, lng: -85.8507,
    },
    {
      name: "Tight Lines Fly Fishing Co.",
      city: "De Pere",
      state: "WI",
      address: "2487 S Oneida St, Green Bay, WI 54304",
      phone: "(920) 336-4106",
      website: "https://www.tightlinesflyfishing.com",
      notes: "Wisconsin's most complete fly shop, spring creeks, Lake Michigan tributaries, and Great Lakes steelhead.",
      rivers: ["Brule River", "Bois Brule", "Wolf River"],
      lat: 44.4439, lng: -88.0637,
    },
  ],

  great_plains: [
    {
      name: "Sportsman's Warehouse, Sioux Falls",
      city: "Sioux Falls",
      state: "SD",
      address: "3709 S Louise Ave, Sioux Falls, SD 57106",
      phone: "(605) 362-0000",
      website: "https://www.sportsmanswarehouse.com",
      notes: "Best regional option for Black Hills and Missouri River fly fishing outfitting on the plains.",
      rivers: ["Missouri River", "Rapid Creek", "Spearfish Creek"],
      lat: 43.5020, lng: -96.7752,
    },
    {
      name: "Black Hills Fly Fishing",
      city: "Rapid City",
      state: "SD",
      address: "612 Mt Rushmore Rd, Rapid City, SD 57701",
      phone: "(605) 342-5100",
      website: "https://www.blackhillsflyfishing.com",
      notes: "Rapid Creek runs through town, guided wade fishing for browns in an urban canyon setting.",
      rivers: ["Rapid Creek", "Spearfish Creek", "French Creek"],
      lat: 44.0805, lng: -103.2310,
    },
  ],

  southwest: [
    {
      name: "Duranglers Flies & Supplies",
      city: "Durango",
      state: "CO",
      address: "801B Main Ave, Durango, CO 81301",
      phone: "(970) 385-4081",
      website: "https://www.duranglers.com",
      notes: "San Juan River gateway shop, the definitive stop before floating the quality water below Navajo Dam.",
      rivers: ["San Juan River", "Animas River", "Los Pinos River"],
      lat: 37.2753, lng: -107.8801,
    },
    {
      name: "Taylor Creek Fly Shops",
      city: "Basalt",
      state: "CO",
      address: "183 Basalt Center Cir, Basalt, CO 81621",
      phone: "(970) 927-4374",
      website: "https://www.taylorcreek.com",
      notes: "Roaring Fork Valley experts, Fryingpan, Roaring Fork, and Crystal River specialists.",
      rivers: ["Fryingpan River", "Roaring Fork River", "Crystal River"],
      lat: 39.3692, lng: -107.0339,
    },
    {
      name: "Los Pinos Fly Fishing",
      city: "Albuquerque",
      state: "NM",
      address: "4022 Rio Grande Blvd NW, Albuquerque, NM 87107",
      phone: "(505) 344-2444",
      website: "https://www.lospinosflyfishing.com",
      notes: "New Mexico's premier fly shop, San Juan, Cimarron, and high-country beaver pond expertise.",
      rivers: ["San Juan River", "Cimarron River", "Rio Grande"],
      lat: 35.1320, lng: -106.6791,
    },
  ],

  california: [
    {
      name: "The Troutfitter",
      city: "Mammoth Lakes",
      state: "CA",
      address: "Shell Mart Center, Mammoth Lakes, CA 93546",
      phone: "(760) 934-2517",
      website: "https://www.thetroutfitter.com",
      notes: "Hot Creek and Owens River headquarters, finest spring creek shop in the Sierra Nevada.",
      rivers: ["Hot Creek", "Owens River", "Crowley Lake"],
      lat: 37.6485, lng: -118.9722,
    },
    {
      name: "The Fly Shop",
      city: "Redding",
      state: "CA",
      address: "4140 Churn Creek Rd, Redding, CA 96002",
      phone: "(800) 669-3474",
      website: "https://www.theflyshop.com",
      notes: "California's largest fly shop, Sacramento River, Fall River, and Klamath system specialists.",
      rivers: ["Sacramento River", "Fall River", "Pit River", "Klamath River"],
      lat: 40.5418, lng: -122.3447,
    },
    {
      name: "Sierra Fly Fisher",
      city: "Truckee",
      state: "CA",
      address: "10200 Donner Pass Rd, Truckee, CA 96161",
      phone: "(530) 587-7929",
      website: "https://www.sierraflyfisher.com",
      notes: "Truckee River and Lake Tahoe tributaries, premier high Sierra shop with excellent guide program.",
      rivers: ["Truckee River", "Little Truckee River", "East Carson River"],
      lat: 39.3288, lng: -120.1830,
    },
  ],

  alaska: [
    {
      name: "Alaska Fly Fishing Goods",
      city: "Anchorage",
      state: "AK",
      address: "641 W 36th Ave, Anchorage, AK 99503",
      phone: "(907) 344-8218",
      website: "https://www.alaskaflygoods.com",
      notes: "Anchorage's go-to for pre-trip outfitting, Kenai, Susitna, and remote fly-out planning.",
      rivers: ["Kenai River", "Susitna River", "Russian River"],
      lat: 61.1867, lng: -149.8976,
    },
    {
      name: "Soldotna Creek Flies",
      city: "Soldotna",
      state: "AK",
      address: "35375 Kenai Spur Hwy, Soldotna, AK 99669",
      phone: "(907) 262-4741",
      website: "https://www.kenaiflyfishing.com",
      notes: "Right on the Kenai, daily salmon and rainbow reports, tackle, and guided drift boat trips.",
      rivers: ["Kenai River", "Kasilof River", "Russian River"],
      lat: 60.4875, lng: -151.0594,
    },
  ],
};

// Map fallback for appalachian_east
flyShopsByRegion["appalachian_east"] = flyShopsByRegion["appalachian_east"] ?? flyShopsByRegion["southeast"];

export function getShopsForRegion(region: string): FlyShop[] {
  return flyShopsByRegion[region] ?? [];
}
