export interface FlyShop {
  name: string;
  city: string;
  state: string;
  address: string;
  phone: string;
  website: string;
  notes: string;        // one-line character note, what makes them special
  rivers: string[];     // rivers they know best (2-3)
  lat: number;
  lng: number;
}

export const shopsByState: Record<string, FlyShop[]> = {
  AL: [
    {
      name: "Riverside Fly Shop",
      city: "Bremen",
      state: "AL",
      address: "17027 Alabama 69, Bremen, AL 35033",
      phone: "(256) 287-9582",
      website: "https://www.riversideflyshop.com",
      notes: "North Alabama's top smallmouth and trout shop, deep local knowledge of the Sipsey Fork and Mulberry Fork.",
      rivers: ["Sipsey Fork", "Mulberry Fork", "Warrior River"],
      lat: 33.9732,
      lng: -87.2203,
    },
    {
      name: "Deep South Outfitters",
      city: "Birmingham",
      state: "AL",
      address: "4700 Cahaba River Rd, Birmingham, AL 35243",
      phone: "(205) 969-3868",
      website: "https://deepsouthoutfitters.com",
      notes: "Birmingham's premier fly shop for Cahaba River bass, carp, and wade-fishing the tailwaters.",
      rivers: ["Cahaba River", "Coosa River", "Locust Fork"],
      lat: 33.4312,
      lng: -86.7553,
    },
    {
      name: "Community Fly Supply",
      city: "Gulf Shores",
      state: "AL",
      address: "824 Gulf Shores Pkwy, Gulf Shores, AL 36542",
      phone: "(251) 975-0980",
      website: "https://www.communityflysupply.com",
      notes: "Gulf Coast Alabama's only dedicated fly shop, redfish, speckled trout, and cobia on the fly.",
      rivers: ["Perdido Bay", "Mobile Bay", "Magnolia River"],
      lat: 30.2460,
      lng: -87.6836,
    },
  ],

  AK: [
    {
      name: "Mossy's Fly Shop",
      city: "Anchorage",
      state: "AK",
      address: "750 W Dimond Blvd Ste 114, Anchorage, AK 99515",
      phone: "(907) 770-2666",
      website: "https://www.mossysflyshop.com",
      notes: "Anchorage's go-to shop for Alaska salmon, rainbow, and steelhead, expert guides for every major drainage.",
      rivers: ["Kenai River", "Anchor River", "Russian River"],
      lat: 61.1278,
      lng: -149.9002,
    },
    {
      name: "Alaska Fly Fishing Goods",
      city: "Juneau",
      state: "AK",
      address: "9045 Glacier Hwy Ste 101, Juneau, AK 99801",
      phone: "(907) 586-1550",
      website: "https://alaskaflyfishinggoods.com",
      notes: "Southeast Alaska specialist for Dolly Varden, steelhead, and Situk-style cutthroat trout fishing.",
      rivers: ["Situk River", "Chilkat River", "Mendenhall River"],
      lat: 58.3794,
      lng: -134.6390,
    },
    {
      name: "Mountain View Sports",
      city: "Anchorage",
      state: "AK",
      address: "11124 Old Seward Hwy Ste 600, Anchorage, AK 99515",
      phone: "(907) 563-8600",
      website: "https://www.mountainviewsports.com",
      notes: "Full-service Anchorage outfitter stocking everything for king salmon and sockeye on major Peninsula rivers.",
      rivers: ["Kenai River", "Kasilof River", "Deshka River"],
      lat: 61.1221,
      lng: -149.8775,
    },
  ],

  AZ: [
    {
      name: "AZ Fly Shop",
      city: "Phoenix",
      state: "AZ",
      address: "3254 E Cactus Rd, Phoenix, AZ 85032",
      phone: "(602) 354-8881",
      website: "https://www.azflyshop.com",
      notes: "Phoenix's top fly shop, White Mountains trout, desert bass, and carp on the Salt River drainage.",
      rivers: ["Salt River", "Verde River", "Black River"],
      lat: 33.5990,
      lng: -112.0062,
    },
    {
      name: "Lees Ferry Anglers",
      city: "Marble Canyon",
      state: "AZ",
      address: "Hwy 89A Mile Marker 547, Marble Canyon, AZ 86036",
      phone: "(800) 962-9755",
      website: "https://leesferry.com",
      notes: "The definitive shop for the Colorado River at Lees Ferry, world-class rainbow trout in the Grand Canyon tailwater.",
      rivers: ["Colorado River (Lees Ferry)", "Paria River"],
      lat: 36.8634,
      lng: -111.5899,
    },
    {
      name: "Dry Creek Outfitters",
      city: "Tucson",
      state: "AZ",
      address: "1717 N Tucson Blvd, Tucson, AZ 85716",
      phone: "(520) 327-1560",
      website: "https://www.drycreekoutfitters.net",
      notes: "Southern Arizona's Orvis dealer, San Juan and Gila trout specialists with a passionate local following.",
      rivers: ["San Pedro River", "Gila River", "East Fork Black River"],
      lat: 32.2462,
      lng: -110.9405,
    },
  ],

  AR: [
    {
      name: "McLellan's Fly Shop",
      city: "Fayetteville",
      state: "AR",
      address: "18 W Sunbridge Dr, Fayetteville, AR 72703",
      phone: "(479) 251-7037",
      website: "https://mcflyshop.com",
      notes: "Arkansas's finest full-service fly shop, White River brown trout and Buffalo River smallmouth headquarters.",
      rivers: ["White River", "Buffalo National River", "Kings River"],
      lat: 36.0882,
      lng: -94.1719,
    },
    {
      name: "Dally's Ozark Fly Fisher",
      city: "Cotter",
      state: "AR",
      address: "1200 W Main St, Cotter, AR 72626",
      phone: "(870) 435-6167",
      website: "#",
      notes: "Legendary White River shop near Cotter, trophy brown trout, catch-and-release expertise for 40+ years.",
      rivers: ["White River", "North Fork River", "Buffalo River"],
      lat: 36.2756,
      lng: -92.5346,
    },
    {
      name: "Diamond State Fly Co",
      city: "Flippin",
      state: "AR",
      address: "10413 US-62, Flippin, AR 72634",
      phone: "(870) 453-8800",
      website: "https://www.diamondstateflyco.com",
      notes: "Norfork and White River tailwater specialists with custom guide packages for trophy trout seekers.",
      rivers: ["Norfork River", "White River", "Little Red River"],
      lat: 36.2826,
      lng: -92.5967,
    },
  ],

  CA: [
    {
      name: "The Fly Shop",
      city: "Redding",
      state: "CA",
      address: "4140 Churn Creek Rd, Redding, CA 96002",
      phone: "(800) 669-3474",
      website: "https://www.theflyshop.com",
      notes: "One of America's most iconic fly shops, Pit River, McCloud, and Trinity world-class steelhead and trout destination.",
      rivers: ["Sacramento River", "Pit River", "McCloud River"],
      lat: 40.5449,
      lng: -122.3481,
    },
    {
      name: "Bob Marriott's Flyfishing Store",
      city: "Fullerton",
      state: "CA",
      address: "2700 W Orangethorpe Ave, Fullerton, CA 92833",
      phone: "(714) 525-1827",
      website: "https://www.bobmarriottsflyshop.com",
      notes: "Southern California's legendary fly shop since 1969, steelhead, saltwater, and Sierra trout under one roof.",
      rivers: ["Santa Ana River", "San Gabriel River", "Kern River"],
      lat: 33.8742,
      lng: -117.9541,
    },
    {
      name: "Ted Fay Fly Shop",
      city: "Dunsmuir",
      state: "CA",
      address: "5732 Dunsmuir Ave, Dunsmuir, CA 96025",
      phone: "(530) 235-2969",
      website: "https://www.tedfayflyfishing.com",
      notes: "Gateway shop to the upper Sacramento River, dry fly paradise for wild trout in Northern California's canyon country.",
      rivers: ["Upper Sacramento River", "McCloud River", "Trinity River"],
      lat: 41.2015,
      lng: -122.2721,
    },
    {
      name: "Leland Fly Fishing Outfitters",
      city: "San Francisco",
      state: "CA",
      address: "542 Coleman Ave, San Jose, CA 95110",
      phone: "(408) 286-1986",
      website: "https://lelandflyfishing.com",
      notes: "Bay Area's premier saltwater and freshwater shop, striper, sturgeon, and Sierra high-country trout experts.",
      rivers: ["American River", "Feather River", "San Francisco Bay"],
      lat: 37.3382,
      lng: -121.8863,
    },
  ],

  CO: [
    {
      name: "Trouts Fly Fishing",
      city: "Denver",
      state: "CO",
      address: "1303 E 6th Ave, Denver, CO 80218",
      phone: "(303) 733-1434",
      website: "#",
      notes: "Denver's flagship fly shop, South Platte, Colorado, and Arkansas river experts with a legendary local reputation.",
      rivers: ["South Platte River", "Colorado River", "Arkansas River"],
      lat: 39.7289,
      lng: -104.9713,
    },
    {
      name: "St. Peter's Fly Shop",
      city: "Fort Collins",
      state: "CO",
      address: "2008 E Harmony Rd, Fort Collins, CO 80528",
      phone: "(970) 377-3785",
      website: "https://www.stpetersflyfishing.com",
      notes: "Northern Colorado's beloved shop, Cache la Poudre and Big Thompson specialists with outstanding guided wade trips.",
      rivers: ["Cache la Poudre River", "Big Thompson River", "South Platte River"],
      lat: 40.5153,
      lng: -105.0263,
    },
    {
      name: "Duranglers Flies & Supplies",
      city: "Durango",
      state: "CO",
      address: "923 Main Ave, Durango, CO 81301",
      phone: "(970) 385-4081",
      website: "https://www.duranglers.com",
      notes: "Southwest Colorado's essential stop, Animas and San Juan river guides, quality tying materials, and expert advice.",
      rivers: ["Animas River", "San Juan River", "Dolores River"],
      lat: 37.2753,
      lng: -107.8801,
    },
    {
      name: "Cutthroat Anglers",
      city: "Silverthorne",
      state: "CO",
      address: "400 Blue River Pkwy, Silverthorne, CO 80498",
      phone: "(970) 262-2878",
      website: "https://www.fishcolorado.com",
      notes: "Summit County shop at the heart of the Blue River Gold Medal tailwater, Colorado high-altitude trout specialists.",
      rivers: ["Blue River", "Colorado River", "Eagle River"],
      lat: 39.6285,
      lng: -106.0700,
    },
  ],

  CT: [
    {
      name: "The Compleat Angler",
      city: "Darien",
      state: "CT",
      address: "987 Post Rd, Darien, CT 06820",
      phone: "(203) 655-9400",
      website: "https://compleatanglernet.com",
      notes: "Connecticut's oldest fly shop, Housatonic River limestone hatches and Long Island Sound striped bass experts.",
      rivers: ["Housatonic River", "Farmington River", "Connecticut River"],
      lat: 41.0776,
      lng: -73.4679,
    },
    {
      name: "Housatonic Meadows Fly Shop",
      city: "Sharon",
      state: "CT",
      address: "9 Route 7, Sharon, CT 06069",
      phone: "(860) 672-6064",
      website: "https://www.housatonicmeadows.com",
      notes: "Riverside shop right on Connecticut's top trout water, matching the Housatonic's legendary sulfur and caddis hatches.",
      rivers: ["Housatonic River", "Salmon Creek", "Shepaug River"],
      lat: 41.9001,
      lng: -73.4776,
    },
    {
      name: "Main Stream Outfitters",
      city: "New Hartford",
      state: "CT",
      address: "228 Main St, New Hartford, CT 06057",
      phone: "(860) 738-0290",
      website: "https://mainstreamoutfitters.com",
      notes: "Farmington River specialists, CT's most popular tailwater with consistent guided hatches and streamer fishing.",
      rivers: ["Farmington River", "Still River", "Naugatuck River"],
      lat: 41.8793,
      lng: -72.9782,
    },
  ],

  DE: [
    {
      name: "A Marblehead Flyfisher",
      city: "Wilmington",
      state: "DE",
      address: "5715 Kirkwood Hwy, Wilmington, DE 19808",
      phone: "(302) 999-9811",
      website: "https://www.amarbleheadflyfisher.com",
      notes: "Delaware's premier fly shop, Brandywine Creek wild brown trout and striped bass in Delaware Bay.",
      rivers: ["Brandywine Creek", "Red Clay Creek", "Delaware River"],
      lat: 39.7318,
      lng: -75.6549,
    },
    {
      name: "Backwater Angler",
      city: "Monkton",
      state: "MD",
      address: "16928 York Rd, Monkton, MD 21111",
      phone: "(410) 357-9557",
      website: "https://www.backwaterangler.com",
      notes: "Serves both Delaware and upper Maryland, Gunpowder Falls wild trout and Chesapeake Bay rockfish on the fly.",
      rivers: ["Gunpowder Falls", "Deer Creek", "Susquehanna River"],
      lat: 39.5818,
      lng: -76.6163,
    },
  ],

  FL: [
    {
      name: "Florida Keys Outfitters",
      city: "Islamorada",
      state: "FL",
      address: "81888 Overseas Hwy, Islamorada, FL 33036",
      phone: "(305) 664-5423",
      website: "https://www.floridakeysoutfitters.com",
      notes: "The definitive Keys fly shop since 1989, bonefish, permit, and tarpon guides with unmatched flats expertise.",
      rivers: ["Florida Bay", "Everglades backcountry", "Atlantic flats"],
      lat: 24.9252,
      lng: -80.6318,
    },
    {
      name: "The Saltwater Angler",
      city: "Key West",
      state: "FL",
      address: "243 Front St, Key West, FL 33040",
      phone: "(305) 296-0700",
      website: "https://saltwaterangler.com",
      notes: "Key West's premier saltwater fly outfitter at the Westin Marina, permit, tarpon, and backcountry snook specialists.",
      rivers: ["Key West flats", "Marquesas flats", "Backcountry channels"],
      lat: 24.5597,
      lng: -81.8044,
    },
    {
      name: "Ole Florida Fly Shop",
      city: "Boca Raton",
      state: "FL",
      address: "6353 N Federal Hwy, Boca Raton, FL 33487",
      phone: "(561) 995-1929",
      website: "https://olefloridaflyshop.com",
      notes: "South Florida's top-rated saltwater fly shop, snook, tarpon, and bluewater species with expert custom fly selection.",
      rivers: ["Intracoastal Waterway", "Loxahatchee River", "Atlantic inshore"],
      lat: 26.3984,
      lng: -80.0853,
    },
    {
      name: "Seven Mile Fly Shop",
      city: "Marathon",
      state: "FL",
      address: "1638 Overseas Hwy, Marathon, FL 33050",
      phone: "(305) 743-4581",
      website: "https://www.sevenmileflyshop.com",
      notes: "Middle Keys hub for bonefish and permit on the flats, custom fly boxes pre-loaded for specific Keys species.",
      rivers: ["Florida Bay (Middle Keys)", "Gulf side flats", "Atlantic side flats"],
      lat: 24.7109,
      lng: -81.0230,
    },
  ],

  GA: [
    {
      name: "The Fish Hawk",
      city: "Atlanta",
      state: "GA",
      address: "764 Miami Cir NE #126, Atlanta, GA 30324",
      phone: "(404) 237-3473",
      website: "https://www.thefishhawk.com",
      notes: "Atlanta's legendary fly shop since 1977, Southeast's most respected shop for mountain trout and coastal redfish.",
      rivers: ["Chattahoochee River", "Tallulah River", "Savannah River"],
      lat: 33.8391,
      lng: -84.3652,
    },
    {
      name: "Unicoi Outfitters",
      city: "Helen",
      state: "GA",
      address: "7280 S Main St, Helen, GA 30545",
      phone: "(706) 878-3083",
      website: "https://www.unicoioutfitters.com",
      notes: "North Georgia's top trout shop in the heart of Chattahoochee National Forest, delayed harvest stream specialists.",
      rivers: ["Chattahoochee River (headwaters)", "Toccoa River", "Noontootla Creek"],
      lat: 34.7018,
      lng: -83.7318,
    },
    {
      name: "Cohutta Fishing Company",
      city: "Blue Ridge",
      state: "GA",
      address: "490 E Main St, Blue Ridge, GA 30513",
      phone: "(706) 946-3044",
      website: "https://cohuttafishingcompany.com",
      notes: "Blue Ridge mountain fly shop at the Toccoa River, wild trout guides and Fightingtown Creek expertise.",
      rivers: ["Toccoa River", "Fightingtown Creek", "Jacks River"],
      lat: 34.8629,
      lng: -84.3235,
    },
  ],

  HI: [
    {
      name: "Nervous Water Fly Fishers",
      city: "Honolulu",
      state: "HI",
      address: "1144 10th Ave Ste 207, Honolulu, HI 96816",
      phone: "(808) 366-7835",
      website: "https://www.nervouswater.com",
      notes: "Hawaii's only dedicated fly shop, bonefish on Oahu's flats with world-class light-tackle expertise.",
      rivers: ["Kaneohe Bay flats", "Oahu flats", "Kailua Bay"],
      lat: 21.2920,
      lng: -157.8115,
    },
    {
      name: "HI Tide Fly Fishing",
      city: "Kailua",
      state: "HI",
      address: "Kailua, HI 96734",
      phone: "(808) 342-0093",
      website: "https://www.hitidefishing.com",
      notes: "Oahu inshore guide service specializing in Hawaiian bonefish, giant trevally, and bluewater fly fishing.",
      rivers: ["Kaneohe Bay", "Kailua Bay", "Windward Oahu flats"],
      lat: 21.3961,
      lng: -157.7391,
    },
  ],

  ID: [
    {
      name: "Silver Creek Outfitters",
      city: "Ketchum",
      state: "ID",
      address: "500 N Main St, Ketchum, ID 83340",
      phone: "(208) 726-5282",
      website: "https://www.silvercreekoutfitters.com",
      notes: "Idaho's most storied fly shop, Silver Creek spring creek mastery with guides steeped in Hemingway-country tradition.",
      rivers: ["Silver Creek", "Big Wood River", "Henry's Fork"],
      lat: 43.6825,
      lng: -114.3638,
    },
    {
      name: "Idaho Angler",
      city: "Boise",
      state: "ID",
      address: "1682 S Vista Ave, Boise, ID 83705",
      phone: "(208) 389-9957",
      website: "https://www.idahoangler.com",
      notes: "Boise's best fly shop, South Fork Boise steelhead, Boise River brown trout, and Snake River bass specialists.",
      rivers: ["Boise River", "South Fork Boise River", "Snake River"],
      lat: 43.5946,
      lng: -116.2070,
    },
    {
      name: "Jimmy's All Seasons Angler",
      city: "Idaho Falls",
      state: "ID",
      address: "275 A St, Idaho Falls, ID 83402",
      phone: "(208) 524-7160",
      website: "https://www.jimmysallseasonsangler.com",
      notes: "Eastern Idaho's go-to shop, Henry's Fork, South Fork Snake, and Teton River guides for cutthroat and rainbow.",
      rivers: ["Henry's Fork", "South Fork Snake River", "Teton River"],
      lat: 43.4924,
      lng: -112.0330,
    },
    {
      name: "Castaway Fly Fishing Shop",
      city: "Coeur d'Alene",
      state: "ID",
      address: "1114 N 4th St, Coeur d'Alene, ID 83814",
      phone: "(208) 765-3133",
      website: "https://www.castawayflyshop.com",
      notes: "North Idaho shop for Clearwater steelhead, Spokane River rainbow trout, and panhandle cutthroat.",
      rivers: ["Clearwater River", "Spokane River", "St. Joe River"],
      lat: 47.6777,
      lng: -116.7805,
    },
  ],

  IL: [
    {
      name: "Chicago Fly Fishing Outfitters",
      city: "Chicago",
      state: "IL",
      address: "1279 N Clybourn Ave, Chicago, IL 60610",
      phone: "(312) 944-3474",
      website: "https://www.chicagoflyfishing.com",
      notes: "Chicago's top urban fly shop, Lake Michigan steelhead, carp on the lakefront, and Fox River smallmouth bass.",
      rivers: ["Chicago River", "Fox River", "Lake Michigan tributaries"],
      lat: 41.9053,
      lng: -87.6378,
    },
    {
      name: "Trout and Grouse",
      city: "Northbrook",
      state: "IL",
      address: "840 Willow Rd Ste P, Northbrook, IL 60062",
      phone: "(847) 205-9310",
      website: "#",
      notes: "North suburban Chicago shop, catch-and-release trout ponds, Des Plaines tributaries, and North Shore lake-run steelhead.",
      rivers: ["Des Plaines River", "North Branch Chicago River", "Skokie Lagoons"],
      lat: 42.1403,
      lng: -87.8536,
    },
    {
      name: "Orvis Chicago",
      city: "Chicago",
      state: "IL",
      address: "142 E Ontario St, Chicago, IL 60611",
      phone: "(312) 440-0662",
      website: "https://www.orvis.com/stores/chicago",
      notes: "Flagship Orvis dealer in the heart of Chicago, great urban resource for Midwest fly fishing gear and instruction.",
      rivers: ["Chicago River", "Fox River", "Wisconsin Driftless streams"],
      lat: 41.8935,
      lng: -87.6246,
    },
  ],

  IN: [
    {
      name: "Fly Masters of Indianapolis",
      city: "Indianapolis",
      state: "IN",
      address: "8232 Allisonville Rd, Indianapolis, IN 46250",
      phone: "(317) 845-9144",
      website: "https://www.flymastersindy.com",
      notes: "Indiana's longest-running full-service fly shop, Driftless streams, smallmouth bass, and Great Lakes steelhead.",
      rivers: ["Sugar Creek", "Blue River", "St. Joseph River"],
      lat: 39.8953,
      lng: -86.0560,
    },
    {
      name: "J.L. Waters & Co.",
      city: "Bloomington",
      state: "IN",
      address: "109 N College Ave, Bloomington, IN 47404",
      phone: "(812) 332-4965",
      website: "https://www.jlwaters.com",
      notes: "Southern Indiana's fly fishing hub near Monroe Lake, smallmouth bass and Brown County creek specialists.",
      rivers: ["Clear Creek", "Salt Creek", "Blue River"],
      lat: 39.1653,
      lng: -86.5264,
    },
    {
      name: "Great Lakes Fly Fishing Company",
      city: "Rockford",
      state: "MI",
      address: "8460 Algoma Ave NE, Rockford, MI 49341",
      phone: "(616) 866-6060",
      website: "https://www.greatlakesflyfishing.com",
      notes: "Serves both Indiana and Michigan, Grand River steelhead and Lake Michigan salmon with expert Midwest guides. (Note: Michigan-based dealer serving IN border region)",
      rivers: ["Grand River", "Muskegon River", "Kalamazoo River"],
      lat: 43.1203,
      lng: -85.5591,
    },
  ],

  IA: [
    {
      name: "Fin & Feather",
      city: "Iowa City",
      state: "IA",
      address: "125 Hwy 1 W, Iowa City, IA 52246",
      phone: "(319) 354-2200",
      website: "https://www.finfeather.com",
      notes: "Iowa's iconic fly shop since 1964, Driftless Area limestone trout streams and Iowa River smallmouth bass.",
      rivers: ["Upper Iowa River", "Yellow River", "Volga River"],
      lat: 41.6611,
      lng: -91.5718,
    },
    {
      name: "Scheels Sports",
      city: "Coralville",
      state: "IA",
      address: "1461 Coral Ridge Ave, Coralville, IA 52241",
      phone: "(319) 625-9959",
      website: "https://www.scheels.com",
      notes: "Iowa's largest fly fishing department, good selection for Driftless trout and Iowa smallmouth. (Orvis dealer / large-format retailer)",
      rivers: ["Upper Iowa River", "Maquoketa River", "Cedar River"],
      lat: 41.6954,
      lng: -91.6016,
    },
    {
      name: "Driftless Fly Fishing Company",
      city: "Preston",
      state: "MN",
      address: "208 St. Paul St SW, Preston, MN 55965",
      phone: "(507) 327-4276",
      website: "https://www.driftlessflyfishing.com",
      notes: "Serves the Iowa-Minnesota Driftless border region, limestone spring creeks and wild brown trout specialists.",
      rivers: ["Root River", "South Branch Root River", "Winnebago Creek"],
      lat: 43.6694,
      lng: -92.0807,
    },
  ],

  KS: [
    {
      name: "K&K Flyfishers",
      city: "Overland Park",
      state: "KS",
      address: "8643 Grant Ave, Overland Park, KS 66212",
      phone: "(913) 341-8118",
      website: "#",
      notes: "Kansas City metro's established fly shop, carp on the Kansas River and Kansas bass on the fly.",
      rivers: ["Kansas River", "Marais des Cygnes River", "Arkansas River"],
      lat: 38.9826,
      lng: -94.6819,
    },
    {
      name: "Yager's Fly Shop",
      city: "Lawrence",
      state: "KS",
      address: "2311 Wakarusa Dr Ste B, Lawrence, KS 66047",
      phone: "(785) 842-1239",
      website: "#",
      notes: "Lawrence's dedicated fly shop, Flint Hills watershed smallmouth, Clinton Lake carp, and Ozark trout trips.",
      rivers: ["Kansas River", "Wakarusa River", "Neosho River"],
      lat: 38.9451,
      lng: -95.2530,
    },
    {
      name: "Great Blue Heron Outdoors",
      city: "Lawrence",
      state: "KS",
      address: "823 Massachusetts St, Lawrence, KS 66044",
      phone: "(785) 856-5656",
      website: "https://www.greatblueheronoutdoors.com",
      notes: "Downtown Lawrence outdoor shop with solid fly fishing department, Kansas River carp and Ozark weekend trips.",
      rivers: ["Kansas River", "Clinton Lake", "Marais des Cygnes River"],
      lat: 38.9717,
      lng: -95.2353,
    },
  ],

  KY: [
    {
      name: "Lexington Angler",
      city: "Lexington",
      state: "KY",
      address: "119 Clay Ave, Lexington, KY 40502",
      phone: "(859) 389-6522",
      website: "https://www.lexingtonangler.com",
      notes: "Kentucky's finest fly shop, Cumberland River tailwater brown trout and Elkhorn Creek smallmouth bass.",
      rivers: ["Cumberland River", "North Fork Elkhorn Creek", "Kentucky River"],
      lat: 38.0406,
      lng: -84.4877,
    },
    {
      name: "Orvis Louisville",
      city: "Louisville",
      state: "KY",
      address: "4600 Shelbyville Rd, Louisville, KY 40207",
      phone: "(502) 896-6767",
      website: "https://www.orvis.com/stores/louisville",
      notes: "Louisville's top fly fishing resource, Cumberland tailwater access info and guided trips to Kentucky's best trout water. (Orvis dealer)",
      rivers: ["Cumberland River", "Green River", "Barren River"],
      lat: 38.2527,
      lng: -85.6363,
    },
    {
      name: "Quest Outdoors",
      city: "Louisville",
      state: "KY",
      address: "4600 Shelbyville Rd, Louisville, KY 40207",
      phone: "(502) 290-4589",
      website: "https://www.questoutdoors.com",
      notes: "Louisville outdoor gear and fly fishing department, serves the Cumberland River tailwater crowd with local know-how.",
      rivers: ["Cumberland River", "Nolin River", "Barren River"],
      lat: 38.2527,
      lng: -85.6363,
    },
  ],

  LA: [
    {
      name: "Marsh & Bayou Outfitters",
      city: "Mandeville",
      state: "LA",
      address: "2600 Florida St Ste 3, Mandeville, LA 70448",
      phone: "(985) 869-7335",
      website: "https://www.marshandbayououtfitters.com",
      notes: "Louisiana's leading fly shop for redfish, speckled trout, and sheepshead in the Lake Pontchartrain basin.",
      rivers: ["Lake Pontchartrain", "Tchefuncte River", "Biloxi Marsh"],
      lat: 30.3680,
      lng: -90.0837,
    },
    {
      name: "No Wake Outfitters",
      city: "Metairie",
      state: "LA",
      address: "1926 Airline Dr, Metairie, LA 70001",
      phone: "(504) 301-8587",
      website: "https://www.nowakeoutfitters.com",
      notes: "New Orleans metro's best fly shop, reds and drum in the marshes with deep Cajun fishing culture knowledge.",
      rivers: ["Mississippi River Gulf Outlet", "Lake Borgne", "Biloxi Marsh"],
      lat: 29.9881,
      lng: -90.1786,
    },
    {
      name: "Pack & Paddle",
      city: "Lafayette",
      state: "LA",
      address: "601 E Pinhook Rd, Lafayette, LA 70501",
      phone: "(337) 232-5854",
      website: "https://www.packpaddle.com",
      notes: "Acadiana's outdoors outfitter, Atchafalaya Basin redfish and Vermilion Bay speckled trout fly specialists.",
      rivers: ["Atchafalaya River", "Vermilion Bay", "Mermentau River"],
      lat: 30.2239,
      lng: -92.0131,
    },
  ],

  ME: [
    {
      name: "Eldredge Brothers Fly Shop",
      city: "Cape Neddick",
      state: "ME",
      address: "1480 US-1, Cape Neddick, ME 03902",
      phone: "(207) 363-9269",
      website: "https://www.eldredgebrosflyshop.com",
      notes: "Maine's oldest fly shop since 1935, southern Maine saltwater stripers and Saco River smallmouth bass.",
      rivers: ["Saco River", "York River", "Kennebec River"],
      lat: 43.2032,
      lng: -70.6554,
    },
    {
      name: "Rangeley Region Sports Shop",
      city: "Rangeley",
      state: "ME",
      address: "2529 Main St, Rangeley, ME 04970",
      phone: "(207) 864-5615",
      website: "https://www.rangeleyregionsports.com",
      notes: "Gateway to Maine's legendary lake trout and brook trout country, Rangeley Lakes fly fishing heritage shop.",
      rivers: ["Rangeley River", "Kennebago River", "Dead River"],
      lat: 44.9643,
      lng: -70.6476,
    },
    {
      name: "All Points Fly Shop",
      city: "South Portland",
      state: "ME",
      address: "525 Main St Ste B, South Portland, ME 04106",
      phone: "(888) 919-9077",
      website: "https://www.allpointsflyfishing.com",
      notes: "Portland-area full-service fly shop, stripers on Casco Bay, landlocked salmon, and Androscoggin River guides.",
      rivers: ["Presumpscot River", "Androscoggin River", "Kennebec River"],
      lat: 43.6370,
      lng: -70.2826,
    },
  ],

  MD: [
    {
      name: "Backwater Angler",
      city: "Monkton",
      state: "MD",
      address: "16928 York Rd, Monkton, MD 21111",
      phone: "(410) 357-9557",
      website: "https://www.backwaterangler.com",
      notes: "Maryland's finest fly shop, Gunpowder Falls wild brown trout and Chesapeake Bay rockfish specialists since 1990.",
      rivers: ["Gunpowder Falls", "Big Gunpowder Falls", "Deer Creek"],
      lat: 39.5818,
      lng: -76.6163,
    },
    {
      name: "Great Feathers",
      city: "Sparks",
      state: "MD",
      address: "14824 York Rd, Sparks, MD 21152",
      phone: "(410) 472-6799",
      website: "https://www.greatfeathers.com",
      notes: "Baltimore-area shop for Gunpowder trout and Chesapeake Bay striped bass, knowledgeable staff and local fly selection.",
      rivers: ["Gunpowder Falls", "Patapsco River", "Chesapeake Bay"],
      lat: 39.5409,
      lng: -76.6510,
    },
    {
      name: "Hunting Creek Outfitters",
      city: "Frederick",
      state: "MD",
      address: "29 N Market St, Frederick, MD 21701",
      phone: "(301) 668-4333",
      website: "#",
      notes: "Western Maryland's fly shop, Catoctin Mountain stream trout and Potomac River smallmouth bass expertise.",
      rivers: ["Monocacy River", "Hunting Creek", "Potomac River"],
      lat: 39.4143,
      lng: -77.4105,
    },
  ],

  MA: [
    {
      name: "Bear's Den Fly Fishing Co.",
      city: "Taunton",
      state: "MA",
      address: "262 Winthrop St, Taunton, MA 02780",
      phone: "(508) 824-5819",
      website: "https://www.bearsdenflyfish.com",
      notes: "Top-rated Massachusetts fly shop, Westfield River trout, coastal striped bass, and saltwater flats expertise.",
      rivers: ["Westfield River", "Deerfield River", "Cape Cod saltwater"],
      lat: 41.9001,
      lng: -71.0898,
    },
    {
      name: "Deerfield Fly Shop",
      city: "South Deerfield",
      state: "MA",
      address: "4 S Main St, South Deerfield, MA 01373",
      phone: "(413) 397-3682",
      website: "https://www.deerfieldflyfishing.com",
      notes: "Deerfield River tailwater specialists, lower flows tailored for winter and spring trophy trout on the Deerfield.",
      rivers: ["Deerfield River", "Connecticut River", "Westfield River"],
      lat: 42.4787,
      lng: -72.6090,
    },
    {
      name: "Cape Cod Outfitters",
      city: "Falmouth",
      state: "MA",
      address: "15 Scranton Ave, Falmouth, MA 02540",
      phone: "(508) 548-6900",
      website: "#",
      notes: "Cape Cod's go-to saltwater fly shop, striped bass, false albacore, and bonito in Vineyard Sound and Nantucket Sound.",
      rivers: ["Cape Cod Bay", "Vineyard Sound", "Nantucket Sound"],
      lat: 41.5512,
      lng: -70.6087,
    },
  ],

  MI: [
    {
      name: "Gates AuSable Lodge",
      city: "Grayling",
      state: "MI",
      address: "471 S Stephan Bridge Rd, Grayling, MI 49738",
      phone: "(989) 348-8462",
      website: "https://www.gateslodge.com",
      notes: "Michigan's most legendary fly shop, world-famous AuSable River Hex hatch guides since 1963, a true dry-fly mecca.",
      rivers: ["AuSable River", "Manistee River", "Jordan River"],
      lat: 44.6560,
      lng: -84.7087,
    },
    {
      name: "Schultz Outfitters",
      city: "Ypsilanti",
      state: "MI",
      address: "4 E Cross St, Ypsilanti, MI 48198",
      phone: "(734) 544-1761",
      website: "https://www.schultzoutfitters.com",
      notes: "Southeast Michigan's beloved destination shop, Huron River brown trout, Great Lakes salmon, and steelhead experts.",
      rivers: ["Huron River", "Grand River", "Muskegon River"],
      lat: 42.2414,
      lng: -83.6130,
    },
    {
      name: "The Northern Angler",
      city: "Traverse City",
      state: "MI",
      address: "426 W Front St, Traverse City, MI 49684",
      phone: "(231) 933-4730",
      website: "https://www.thenorthernangler.com",
      notes: "Northwest Michigan's premier fly shop, Boardman River trout and Lake Michigan salmon with friendly local guides.",
      rivers: ["Boardman River", "Betsie River", "Platte River"],
      lat: 44.7631,
      lng: -85.6247,
    },
    {
      name: "Little Forks Outfitters",
      city: "Midland",
      state: "MI",
      address: "143 E Main St, Midland, MI 48640",
      phone: "(877) 550-4668",
      website: "https://www.littleforksoutfitters.com",
      notes: "Central Michigan fly shop on the Tittabawassee, north-country brook trout and Pere Marquette steelhead specialists.",
      rivers: ["Tittabawassee River", "Chippewa River", "Pere Marquette River"],
      lat: 43.6156,
      lng: -84.2472,
    },
  ],

  MN: [
    {
      name: "Bob Mitchell's Fly Shop",
      city: "St. Paul",
      state: "MN",
      address: "550 Vandalia St #119, St. Paul, MN 55114",
      phone: "(651) 770-5854",
      website: "https://www.bobmitchellsflyshop.com",
      notes: "Minnesota's most storied fly shop, Driftless stream trout, North Shore steelhead, and classic shop culture.",
      rivers: ["Whitewater River", "Root River", "Brule River"],
      lat: 44.9509,
      lng: -93.1704,
    },
    {
      name: "The Fly Angler",
      city: "Blaine",
      state: "MN",
      address: "10091 Central Ave NE, Blaine, MN 55434",
      phone: "(763) 572-3782",
      website: "https://www.thornebros.com",
      notes: "Twin Cities' full-service fly shop inside Thorne Brothers, muskie, bass, and Driftless trout specialists.",
      rivers: ["St. Croix River", "Kinnickinnic River", "Root River"],
      lat: 45.1283,
      lng: -93.2249,
    },
    {
      name: "Mend Provisions",
      city: "Minneapolis",
      state: "MN",
      address: "2719 E 42nd St, Minneapolis, MN 55406",
      phone: "(612) 724-4272",
      website: "https://www.mendprovisions.com",
      notes: "Hip Minneapolis fly shop, Driftless trout, urban carp in the Metro, and a curated gear selection for modern anglers.",
      rivers: ["Mississippi River (Twin Cities)", "Kinnickinnic River", "Whitewater River"],
      lat: 44.9168,
      lng: -93.2331,
    },
  ],

  MS: [
    {
      name: "White River Fly Shop at Bass Pro",
      city: "Pearl",
      state: "MS",
      address: "200 Bass Pro Dr, Pearl, MS 39208",
      phone: "(601) 933-3700",
      website: "https://www.basspro.com",
      notes: "Mississippi's best fly fishing retail option, solid selection for Natchez-area bass, Pascagoula redfish. (Bass Pro White River brand)",
      rivers: ["Pearl River", "Pascagoula River", "Tombigbee River"],
      lat: 32.2749,
      lng: -90.0878,
    },
    {
      name: "Orvis Ridgeland",
      city: "Ridgeland",
      state: "MS",
      address: "1000 Highland Colony Pkwy, Ridgeland, MS 39157",
      phone: "(601) 856-2070",
      website: "https://www.orvis.com/stores/ridgeland",
      notes: "Jackson-area Orvis dealer, the go-to resource for Mississippi coast redfish, flounder, and inland bass on the fly. (Orvis dealer)",
      rivers: ["Natchez Trace waterways", "Ross Barnett Reservoir", "Pearl River"],
      lat: 32.4187,
      lng: -90.1374,
    },
    {
      name: "Community Fly Supply",
      city: "Gulf Shores",
      state: "AL",
      address: "824 Gulf Shores Pkwy, Gulf Shores, AL 36542",
      phone: "(251) 975-0980",
      website: "https://www.communityflysupply.com",
      notes: "Nearest dedicated fly shop for coastal Mississippi anglers, redfish and speckled trout on Mississippi Sound. (Alabama-based, serves MS Gulf Coast)",
      rivers: ["Mississippi Sound", "Biloxi Bay", "Back Bay of Biloxi"],
      lat: 30.2460,
      lng: -87.6836,
    },
  ],

  MO: [
    {
      name: "T. Hargrove Fly Fishing",
      city: "St. Louis",
      state: "MO",
      address: "9024 Manchester Rd, St. Louis, MO 63144",
      phone: "(314) 961-4948",
      website: "https://www.thargrove.com",
      notes: "St. Louis's legendary neighborhood fly shop, Missouri Ozark trout and smallmouth bass with old-school expertise.",
      rivers: ["Meramec River", "Gasconade River", "Current River"],
      lat: 38.5981,
      lng: -90.3629,
    },
    {
      name: "Reading's Fly Shop",
      city: "Lebanon",
      state: "MO",
      address: "11937 Hwy 64, Lebanon, MO 65536",
      phone: "(417) 588-4334",
      website: "https://www.readingsflyshop.com",
      notes: "Ozark Missouri's premier trout shop, Bennett Spring and Roaring River state park trout stream guides.",
      rivers: ["Bennett Spring", "Roaring River", "Gasconade River"],
      lat: 37.6756,
      lng: -92.6638,
    },
    {
      name: "Feather-Craft Fly Fishing",
      city: "St. Louis",
      state: "MO",
      address: "8307 Manchester Rd, St. Louis, MO 63144",
      phone: "(800) 659-1707",
      website: "https://www.feather-craft.com",
      notes: "St. Louis institution for fly tying materials and tackle, Current River float-trip outfitting and Ozark stream knowledge.",
      rivers: ["Current River", "Eleven Point River", "Meramec River"],
      lat: 38.5981,
      lng: -90.3696,
    },
  ],

  MT: [
    {
      name: "The River's Edge",
      city: "Bozeman",
      state: "MT",
      address: "612 E Main St, Bozeman, MT 59715",
      phone: "(406) 586-5373",
      website: "https://www.theriversedge.com",
      notes: "One of Montana's finest fly shops, Gallatin, Madison, and Yellowstone River guides with deep blue-ribbon trout expertise.",
      rivers: ["Gallatin River", "Madison River", "Yellowstone River"],
      lat: 45.6794,
      lng: -111.0322,
    },
    {
      name: "Headhunters Fly Shop",
      city: "Craig",
      state: "MT",
      address: "145 Bridge St, Craig, MT 59648",
      phone: "(406) 235-3447",
      website: "https://www.headhuntersflyshop.com",
      notes: "The definitive shop on Montana's Missouri River tailwater, Craig's legendary trout fishing and midging culture.",
      rivers: ["Missouri River", "Sun River", "Smith River"],
      lat: 47.0070,
      lng: -111.6541,
    },
    {
      name: "Blue Ribbon Flies",
      city: "West Yellowstone",
      state: "MT",
      address: "305 N Canyon St, West Yellowstone, MT 59758",
      phone: "(406) 646-9365",
      website: "https://www.blueribbonflies.com",
      notes: "West Yellowstone's iconic shop, Madison, Gallatin, and Yellowstone Park hatches memorized, Craig Mathews's legendary patterns.",
      rivers: ["Madison River", "Gallatin River", "Firehole River"],
      lat: 44.6635,
      lng: -111.0991,
    },
    {
      name: "Grizzly Hackle",
      city: "Missoula",
      state: "MT",
      address: "215 W Front St, Missoula, MT 59801",
      phone: "(406) 721-8996",
      website: "https://www.grizzlyhackle.com",
      notes: "Missoula's top fly shop on the Clark Fork, Blackfoot, Bitterroot, and Clark Fork river guides with a loyal local following.",
      rivers: ["Blackfoot River", "Bitterroot River", "Clark Fork River"],
      lat: 46.8701,
      lng: -113.9969,
    },
  ],

  NE: [
    {
      name: "Scheels Sports Omaha",
      city: "Omaha",
      state: "NE",
      address: "17202 Davenport St, Omaha, NE 68118",
      phone: "(402) 289-5666",
      website: "https://www.scheels.com",
      notes: "Nebraska's best fly fishing retail, Platte and Niobrara River bass, carp, and catfish on the fly. (Large-format Orvis dealer)",
      rivers: ["Platte River", "Niobrara River", "Elkhorn River"],
      lat: 41.2781,
      lng: -96.1868,
    },
    {
      name: "Scheels Sports Lincoln",
      city: "Lincoln",
      state: "NE",
      address: "3030 Pine Lake Rd, Lincoln, NE 68516",
      phone: "(402) 420-9000",
      website: "https://www.scheels.com",
      notes: "Lincoln's fly fishing department, Niobrara and Dismal River trout, plus carp in the lower Platte. (Large-format Orvis dealer)",
      rivers: ["Niobrara River", "Dismal River", "Platte River"],
      lat: 40.7767,
      lng: -96.6437,
    },
    {
      name: "North Platte Sporting Goods",
      city: "North Platte",
      state: "NE",
      address: "502 N Dewey St, North Platte, NE 69101",
      phone: "(308) 534-8323",
      website: "#",
      notes: "Western Nebraska's local outfitter for fly fishing the South Platte system and Sandhills carp and bass.",
      rivers: ["North Platte River", "South Platte River", "Dismal River"],
      lat: 41.1234,
      lng: -100.7659,
    },
  ],

  NV: [
    {
      name: "Reno Fly Shop",
      city: "Reno",
      state: "NV",
      address: "294 E Moana Ln #16, Reno, NV 89502",
      phone: "(775) 323-3474",
      website: "https://www.renoflyfishing.com",
      notes: "Nevada's best fly shop, Truckee River rainbow trout in Reno and Walker River brown trout specialists.",
      rivers: ["Truckee River", "Walker River", "Carson River"],
      lat: 39.4875,
      lng: -119.8094,
    },
    {
      name: "Tahoe Fly Fishing Outfitters",
      city: "South Lake Tahoe",
      state: "CA",
      address: "3433 Lake Tahoe Blvd, South Lake Tahoe, CA 96150",
      phone: "(530) 541-8208",
      website: "https://www.tahoeflyfishing.com",
      notes: "Serves both Nevada and California Lake Tahoe region, Truckee River and East Fork Carson guides for wild trout.",
      rivers: ["Truckee River", "East Fork Carson River", "Walker River"],
      lat: 38.9319,
      lng: -119.9760,
    },
    {
      name: "Scheels All Sports Sparks",
      city: "Sparks",
      state: "NV",
      address: "1200 Scheels Dr, Sparks, NV 89434",
      phone: "(775) 331-2700",
      website: "https://www.scheels.com",
      notes: "Reno-Sparks metro fly fishing department, decent selection for Truckee River, pyramid lake flies. (Large-format retailer)",
      rivers: ["Truckee River", "Pyramid Lake", "Walker River"],
      lat: 39.5460,
      lng: -119.7553,
    },
  ],

  NH: [
    {
      name: "North Country Angler",
      city: "North Conway",
      state: "NH",
      address: "2988 White Mountain Hwy, North Conway, NH 03860",
      phone: "(603) 356-6000",
      website: "https://www.northcountryangler.com",
      notes: "New Hampshire's premier fly shop in the White Mountains, Saco River wild trout and Androscoggin landlocked salmon.",
      rivers: ["Saco River", "Ellis River", "Androscoggin River"],
      lat: 44.0520,
      lng: -71.1276,
    },
    {
      name: "Stone River Outfitters",
      city: "Amherst",
      state: "NH",
      address: "1 NH-101A Unit 1, Amherst, NH 03031",
      phone: "(603) 472-3191",
      website: "https://www.stoneriveroutfitters.com",
      notes: "Southern NH's family-owned gem, Souhegan and Contoocook river trout with warm, expert service.",
      rivers: ["Souhegan River", "Contoocook River", "Piscataquog River"],
      lat: 42.8670,
      lng: -71.6079,
    },
    {
      name: "The Troutsmith",
      city: "Littleton",
      state: "NH",
      address: "6 Mill St, Littleton, NH 03561",
      phone: "(603) 575-5199",
      website: "https://www.thetroutsmith.com",
      notes: "Northern New Hampshire's hidden gem, Ammonoosuc and Connecticut River headwater wild trout in classic North Country settings.",
      rivers: ["Ammonoosuc River", "Connecticut River (headwaters)", "Gale River"],
      lat: 44.3045,
      lng: -71.7717,
    },
  ],

  NJ: [
    {
      name: "Tight Lines Fly Fishing",
      city: "Parsippany",
      state: "NJ",
      address: "222 Baldwin Rd, Parsippany, NJ 07054",
      phone: "(973) 276-9000",
      website: "https://tightlinesflyfishing.com",
      notes: "New Jersey's top fly shop, South Branch Raritan limestone brown trout and Hudson River striped bass.",
      rivers: ["South Branch Raritan River", "Paulins Kill", "Delaware River"],
      lat: 40.8573,
      lng: -74.4168,
    },
    {
      name: "South Branch Outfitters",
      city: "Califon",
      state: "NJ",
      address: "51 Academy St, Califon, NJ 07830",
      phone: "(908) 832-9000",
      website: "https://www.southbranchoutfitters.com",
      notes: "Riverside shop on the South Branch Raritan, New Jersey's limestone trout stream specialists with guided wade trips.",
      rivers: ["South Branch Raritan River", "Lamington River", "Delaware River"],
      lat: 40.7237,
      lng: -74.8354,
    },
    {
      name: "Anglers Den",
      city: "Pawling",
      state: "NY",
      address: "180 E Main St, Pawling, NY 12564",
      phone: "(845) 855-5182",
      website: "https://www.anglersden.net",
      notes: "Serves the NJ-NY border region, Ten Mile River and Beaverkill trout specialists beloved by Tri-State anglers.",
      rivers: ["Ten Mile River", "Beaverkill River", "West Branch Delaware River"],
      lat: 41.5629,
      lng: -73.5979,
    },
  ],

  NM: [
    {
      name: "Taos Fly Shop",
      city: "Taos",
      state: "NM",
      address: "338 Paseo del Pueblo Sur, Taos, NM 87571",
      phone: "(575) 751-1312",
      website: "https://www.taosflyshop.com",
      notes: "New Mexico's best-known fly shop, Rio Grande gorge trout and Red River canyon specialists with expert local guides.",
      rivers: ["Rio Grande", "Red River", "Cimarron River"],
      lat: 36.3912,
      lng: -105.5799,
    },
    {
      name: "The San Juan Angler",
      city: "Durango",
      state: "CO",
      address: "600 Main St Unit 208, Durango, CO 81301",
      phone: "(970) 385-4665",
      website: "https://sanjuanangler.com",
      notes: "Serves both New Mexico and Colorado's San Juan River, the 4-mile trophy tailwater below Navajo Dam, world-class midge fishing.",
      rivers: ["San Juan River", "Animas River", "Los Pinos River"],
      lat: 37.2753,
      lng: -107.8780,
    },
    {
      name: "Los Pinos Fly Shop at Abe's Motel",
      city: "Navajo Dam",
      state: "NM",
      address: "Hwy 173 #3391, Navajo Dam, NM 87419",
      phone: "(505) 632-2194",
      website: "https://www.abesnavajodam.com",
      notes: "Right at the base of Navajo Dam, the most convenient shop for the famous San Juan River trophy trout section.",
      rivers: ["San Juan River", "Piedra River", "Animas River"],
      lat: 36.8014,
      lng: -107.6534,
    },
  ],

  NY: [
    {
      name: "Beaverkill Angler",
      city: "Roscoe",
      state: "NY",
      address: "Stewart Ave, Roscoe, NY 12776",
      phone: "(607) 498-5194",
      website: "https://www.beaverkillangler.com",
      notes: "In Roscoe, 'Trout Town USA', right on the legendary Beaverkill River, the birthplace of American fly fishing.",
      rivers: ["Beaverkill River", "Willowemoc Creek", "West Branch Delaware River"],
      lat: 41.9382,
      lng: -74.9134,
    },
    {
      name: "Urban Angler",
      city: "New York City",
      state: "NY",
      address: "206 5th Ave, New York, NY 10010",
      phone: "(212) 689-6400",
      website: "https://www.urbanangler.com",
      notes: "New York City's iconic fly shop, Catskill tradition meets saltwater stripers, urban carp, and world travel booking.",
      rivers: ["Delaware River", "Beaverkill River", "Hudson River"],
      lat: 40.7425,
      lng: -73.9893,
    },
    {
      name: "Dette Trout Flies",
      city: "Roscoe",
      state: "NY",
      address: "26 Faulkner Rd, Roscoe, NY 12776",
      phone: "(607) 498-4991",
      website: "https://www.detteflies.com",
      notes: "Living legend of the Catskill School, Walt Dette's shop has tied dry flies for 90 years, a pilgrimage for serious fly fishers.",
      rivers: ["Beaverkill River", "Willowemoc Creek", "East Branch Delaware River"],
      lat: 41.9446,
      lng: -74.9073,
    },
    {
      name: "AuSable River Two Fly Shop",
      city: "Wilmington",
      state: "NY",
      address: "5698 NY-86, Wilmington, NY 12997",
      phone: "(518) 946-2605",
      website: "https://www.ausableriverflyshop.com",
      notes: "Adirondacks gateway shop, West Branch AuSable and Olympic-region brook trout in stunning mountain scenery.",
      rivers: ["West Branch AuSable River", "East Branch AuSable River", "Saranac River"],
      lat: 44.3715,
      lng: -73.8362,
    },
  ],

  NC: [
    {
      name: "Davidson River Outfitters",
      city: "Pisgah Forest",
      state: "NC",
      address: "49 Pisgah Hwy, Pisgah Forest, NC 28768",
      phone: "(828) 877-4181",
      website: "https://www.davidsonflyfishing.com",
      notes: "North Carolina's finest fly shop on the world-class Davidson River, catch-and-release wild trout and expert guided wading.",
      rivers: ["Davidson River", "Mills River", "South Mills River"],
      lat: 35.2818,
      lng: -82.7232,
    },
    {
      name: "Hunter Banks Company",
      city: "Asheville",
      state: "NC",
      address: "29 Montford Ave, Asheville, NC 28801",
      phone: "(828) 252-3005",
      website: "https://www.hunterbanks.com",
      notes: "Asheville's beloved downtown fly shop, French Broad, Pigeon, and Tuckasegee wild trout with outstanding guided service.",
      rivers: ["French Broad River", "Pigeon River", "Tuckasegee River"],
      lat: 35.5770,
      lng: -82.5627,
    },
    {
      name: "Brookings Fly Shop",
      city: "Cashiers",
      state: "NC",
      address: "49 Pillar Dr, Cashiers, NC 28717",
      phone: "(828) 743-3768",
      website: "https://www.brookingsanglers.com",
      notes: "Western NC gem in the Nantahala, Chattooga River headwaters wild trout and smallmouth in gorgeous Blue Ridge scenery.",
      rivers: ["Chattooga River", "Whitewater River", "Horsepasture River"],
      lat: 35.0999,
      lng: -83.0963,
    },
  ],

  ND: [
    {
      name: "Scheels Sports Bismarck",
      city: "Bismarck",
      state: "ND",
      address: "800 Kirkwood Mall, Bismarck, ND 58504",
      phone: "(701) 221-4000",
      website: "https://www.scheels.com",
      notes: "North Dakota's best fly fishing retail, Missouri River walleye and northern pike on the fly from a knowledgeable staff. (Large-format retailer with fly dept.)",
      rivers: ["Missouri River", "Heart River", "Knife River"],
      lat: 46.7827,
      lng: -100.7829,
    },
    {
      name: "Scheels Sports Fargo",
      city: "Fargo",
      state: "ND",
      address: "1551 45th St S, Fargo, ND 58103",
      phone: "(701) 298-2918",
      website: "https://www.scheels.com",
      notes: "Red River Valley fly fishing resource, carp, bass, and northern pike on the fly in the Fargo-Moorhead metro. (Large-format retailer with fly dept.)",
      rivers: ["Red River of the North", "Sheyenne River", "Maple River"],
      lat: 46.8314,
      lng: -96.8453,
    },
  ],

  OH: [
    {
      name: "Mad River Outfitters",
      city: "Columbus",
      state: "OH",
      address: "1209 N High St, Columbus, OH 43201",
      phone: "(614) 451-0363",
      website: "https://www.madriveroutfitters.com",
      notes: "Columbus's legendary fly shop since 1994, Mad River, Scioto, and Lake Erie steelhead guides with a massive gear selection.",
      rivers: ["Mad River", "Scioto River", "Grand River (OH)"],
      lat: 39.9967,
      lng: -83.0088,
    },
    {
      name: "Chagrin River Outfitters",
      city: "Chagrin Falls",
      state: "OH",
      address: "87 N Main St, Chagrin Falls, OH 44022",
      phone: "(440) 247-7110",
      website: "https://www.chagrinriveroutfitters.com",
      notes: "Northeast Ohio's finest, Chagrin River steelhead and Lake Erie tribs with some of Ohio's most passionate fly fishers.",
      rivers: ["Chagrin River", "Grand River (OH)", "Rocky River"],
      lat: 41.4279,
      lng: -81.3912,
    },
    {
      name: "Delamere & Hopkins",
      city: "Cincinnati",
      state: "OH",
      address: "2708 Erie Ave, Cincinnati, OH 45208",
      phone: "(513) 871-5904",
      website: "https://www.delamere-hopkins.com",
      notes: "Cincinnati's premier fly shop, Little Miami River smallmouth bass and Kentucky Lake trout with warm local service.",
      rivers: ["Little Miami River", "Great Miami River", "Kentucky River"],
      lat: 39.1399,
      lng: -84.4420,
    },
  ],

  OK: [
    {
      name: "Beavers Bend Fly Shop",
      city: "Broken Bow",
      state: "OK",
      address: "545 Beavers Bend Rd, Broken Bow, OK 74728",
      phone: "(580) 494-6071",
      website: "https://beaversbendflyshop.com",
      notes: "Oklahoma's most celebrated fly shop, Mountain Fork River tailwater trout in stunning Ouachita Mountain scenery.",
      rivers: ["Mountain Fork River", "Little River", "Glover River"],
      lat: 34.1432,
      lng: -94.6826,
    },
    {
      name: "J.D. Adams & Co.",
      city: "Oklahoma City",
      state: "OK",
      address: "12325 N May Ave, Oklahoma City, OK 73120",
      phone: "(405) 607-0498",
      website: "https://jdadamsco.com",
      notes: "OKC's only dedicated fly shop, Red River carp and bass, Ozark weekend trips, with a welcoming community vibe.",
      rivers: ["North Canadian River", "Red River", "Arkansas River"],
      lat: 35.5717,
      lng: -97.5582,
    },
    {
      name: "Golden Rule Fly Shop",
      city: "Tahlequah",
      state: "OK",
      address: "104 S Muskogee Ave, Tahlequah, OK 74464",
      phone: "(918) 456-9083",
      website: "https://goldenruleflyshop.com",
      notes: "Eastern Oklahoma fly shop in Cherokee Nation country, Illinois River smallmouth bass and Tenkiller Lake bass specialists.",
      rivers: ["Illinois River", "Baron Fork", "Grand Lake of the Cherokees"],
      lat: 35.9156,
      lng: -94.9719,
    },
  ],

  OR: [
    {
      name: "The Caddis Fly Angling Shop",
      city: "Eugene",
      state: "OR",
      address: "168 W 6th Ave, Eugene, OR 97401",
      phone: "(541) 342-7005",
      website: "https://www.thecaddisfly.com",
      notes: "Oregon's most complete fly shop, McKenzie River drift boats, Willamette trout, and winter steelhead specialists.",
      rivers: ["McKenzie River", "Willamette River", "Deschutes River"],
      lat: 44.0485,
      lng: -123.0955,
    },
    {
      name: "Deschutes Angler Fly Shop",
      city: "Maupin",
      state: "OR",
      address: "504 Deschutes Ave, Maupin, OR 97037",
      phone: "(541) 395-0995",
      website: "https://deschutesangler.com",
      notes: "Right on the Deschutes River in Maupin, Oregon's greatest steelhead and trout river guided by true river insiders.",
      rivers: ["Deschutes River", "White River (OR)", "John Day River"],
      lat: 45.1788,
      lng: -121.0803,
    },
    {
      name: "The Gorge Fly Shop",
      city: "Hood River",
      state: "OR",
      address: "201 Oak St, Hood River, OR 97031",
      phone: "(541) 386-6977",
      website: "https://gorgeflyshop.com",
      notes: "Columbia Gorge's premier shop, Columbia and Klickitat steelhead with Sandy River winter and spring runs.",
      rivers: ["Columbia River", "Klickitat River", "Sandy River"],
      lat: 45.7051,
      lng: -121.5199,
    },
    {
      name: "Ashland Fly Shop",
      city: "Ashland",
      state: "OR",
      address: "165 A St, Ashland, OR 97520",
      phone: "(541) 488-6454",
      website: "https://www.ashlandflyshop.com",
      notes: "Southern Oregon's Rogue River specialists, guided drift trips for summer steelhead and wild coastal chinook.",
      rivers: ["Rogue River", "Klamath River", "Applegate River"],
      lat: 42.1946,
      lng: -122.7097,
    },
  ],

  PA: [
    {
      name: "TCO Fly Shop",
      city: "Boiling Springs",
      state: "PA",
      address: "2140 Ritner Hwy, Carlisle, PA 17013",
      phone: "(717) 249-2620",
      website: "https://www.tcoflyfishing.com",
      notes: "Pennsylvania's most respected fly shop chain, Yellow Breeches and LeTort limestone spring creek specialists.",
      rivers: ["Yellow Breeches Creek", "LeTort Spring Run", "Big Spring Creek"],
      lat: 40.1451,
      lng: -77.2024,
    },
    {
      name: "The Feathered Hook",
      city: "Coburn",
      state: "PA",
      address: "516 Main St, Coburn, PA 16832",
      phone: "(814) 349-8757",
      website: "https://www.thefeatheredhook.com",
      notes: "Central Pennsylvania limestone country gem, Penns Creek wild trout and Green Drake hatch pilgrims' essential stop.",
      rivers: ["Penns Creek", "Spring Creek", "Bald Eagle Creek"],
      lat: 40.8993,
      lng: -77.4427,
    },
    {
      name: "Anglers Den",
      city: "Pawling",
      state: "NY",
      address: "180 E Main St, Pawling, NY 12564",
      phone: "(845) 855-5182",
      website: "https://www.anglersden.net",
      notes: "Serves both PA and NY Delaware River country, West Branch Delaware trout and Delaware River smallmouth.",
      rivers: ["West Branch Delaware River", "East Branch Delaware River", "Beaverkill River"],
      lat: 41.5629,
      lng: -73.5979,
    },
    {
      name: "Whitetail Country Fly Shop",
      city: "Starlight",
      state: "PA",
      address: "6048 Hancock Hwy, Starlight, PA 18461",
      phone: "(570) 635-5151",
      website: "https://www.whitetailcountry.com",
      notes: "Northeast Pennsylvania on the upper Delaware, stream-side shop for wild trout in this pristine river corridor.",
      rivers: ["Delaware River", "West Branch Delaware River", "Callicoon Creek"],
      lat: 41.9515,
      lng: -75.1301,
    },
  ],

  RI: [
    {
      name: "The Saltwater Edge",
      city: "Portsmouth",
      state: "RI",
      address: "270 Thames St, Newport, RI 02840",
      phone: "(401) 849-4008",
      website: "https://www.saltwateredge.com",
      notes: "Rhode Island's premier saltwater fly shop, Narragansett Bay striped bass, false albacore, and Vineyard Sound bonito.",
      rivers: ["Narragansett Bay", "Providence River", "Sakonnet River"],
      lat: 41.4892,
      lng: -71.3133,
    },
    {
      name: "The Compleat Angler",
      city: "Darien",
      state: "CT",
      address: "987 Post Rd, Darien, CT 06820",
      phone: "(203) 655-9400",
      website: "https://compleatanglernet.com",
      notes: "Nearest full-service shop for Rhode Island freshwater anglers, Wood River trout and Block Island bluefish connections. (CT-based, serves RI)",
      rivers: ["Wood River", "Pawcatuck River", "Blackstone River"],
      lat: 41.0776,
      lng: -73.4679,
    },
    {
      name: "Quaker Lane Bait and Tackle",
      city: "North Kingstown",
      state: "RI",
      address: "4019 Quaker Lane, North Kingstown, RI 02852",
      phone: "(401) 294-9642",
      website: "https://www.quakerlane.com",
      notes: "Rhode Island's traditional full-service tackle shop with good fly fishing department, Narragansett Bay stripers and freshwater trout.",
      rivers: ["Pawcatuck River", "Hunt River", "Wood River"],
      lat: 41.5898,
      lng: -71.4898,
    },
  ],

  SC: [
    {
      name: "Chattooga River Fly Shop",
      city: "Mountain Rest",
      state: "SC",
      address: "6832A Highlands Hwy, Mountain Rest, SC 29664",
      phone: "(864) 638-2806",
      website: "https://chattoogariverflyshop.com",
      notes: "Upcountry South Carolina's wild trout shop on the famed Chattooga, guided wild trout in stunning Sumter National Forest.",
      rivers: ["Chattooga River", "Whitewater River", "Thompson River"],
      lat: 34.8504,
      lng: -83.1374,
    },
    {
      name: "Jocassee Outfitters",
      city: "Salem",
      state: "SC",
      address: "141 N Little River Rd, Salem, SC 29676",
      phone: "(864) 944-0100",
      website: "https://jocasseeoutfitters.com",
      notes: "Foothills fly shop serving Lake Jocassee headwater streams, wild trout in a Blue Ridge landscape unique to SC.",
      rivers: ["Whitewater River", "Thompson River", "Horsepasture River"],
      lat: 34.8887,
      lng: -82.9734,
    },
    {
      name: "Bay Street Outfitters",
      city: "Beaufort",
      state: "SC",
      address: "815 Bay St, Beaufort, SC 29902",
      phone: "(843) 524-5250",
      website: "https://www.baystreetoutfitters.com",
      notes: "Lowcountry coastal fly shop for redfish, speckled trout, and snook in Beaufort's iconic salt marsh estuaries.",
      rivers: ["Beaufort River", "Port Royal Sound", "ACE Basin"],
      lat: 32.4315,
      lng: -80.6698,
    },
  ],

  SD: [
    {
      name: "Dakota Angler & Outfitter",
      city: "Rapid City",
      state: "SD",
      address: "1010 Jackson Blvd, Rapid City, SD 57702",
      phone: "(605) 341-2450",
      website: "https://flyfishsd.com",
      notes: "South Dakota's premier fly shop in the Black Hills, Spearfish Creek, French Creek, and Rapid Creek wild trout.",
      rivers: ["Spearfish Creek", "French Creek", "Rapid Creek"],
      lat: 44.0672,
      lng: -103.2246,
    },
    {
      name: "Scheels Sports Rapid City",
      city: "Rapid City",
      state: "SD",
      address: "1225 Eglin St, Rapid City, SD 57701",
      phone: "(605) 342-9033",
      website: "https://www.scheels.com",
      notes: "Black Hills fly fishing resource, caters to Black Hills trout and Missouri River walleye on the fly. (Large-format retailer)",
      rivers: ["Rapid Creek", "Spearfish Creek", "Missouri River"],
      lat: 44.0795,
      lng: -103.2076,
    },
  ],

  TN: [
    {
      name: "Little River Outfitters",
      city: "Townsend",
      state: "TN",
      address: "7807 E Lamar Alexander Pkwy, Townsend, TN 37882",
      phone: "(865) 448-9459",
      website: "https://www.littleriveroutfitters.com",
      notes: "The gateway shop to Great Smoky Mountains National Park, wild brook trout in pristine mountain streams for over 30 years.",
      rivers: ["Little River", "Abrams Creek", "Hazel Creek"],
      lat: 35.6785,
      lng: -83.7362,
    },
    {
      name: "South Holston River Fly Shop",
      city: "Bristol",
      state: "TN",
      address: "608 Emmett Rd, Bristol, TN 37620",
      phone: "(423) 878-2822",
      website: "https://www.southholstonriverflyshop.com",
      notes: "On the South Holston River, one of the Southeast's top blue-ribbon tailwaters for trophy rainbow and brown trout.",
      rivers: ["South Holston River", "Watauga River", "Holston River"],
      lat: 36.5186,
      lng: -82.1546,
    },
    {
      name: "Fly South",
      city: "Nashville",
      state: "TN",
      address: "115 19th Ave S, Nashville, TN 37203",
      phone: "(615) 251-6199",
      website: "https://www.flysouth.net",
      notes: "Nashville's dedicated fly shop, Cumberland River tailwater trout and Duck River smallmouth bass for Music City anglers.",
      rivers: ["Cumberland River", "Duck River", "Caney Fork River"],
      lat: 36.1455,
      lng: -86.8036,
    },
  ],

  TX: [
    {
      name: "Gruene Outfitters",
      city: "New Braunfels",
      state: "TX",
      address: "1629 Hunter Rd, New Braunfels, TX 78130",
      phone: "(830) 625-4440",
      website: "https://www.grueneoutfitters.com",
      notes: "Texas Hill Country trout and bass specialists, Guadalupe River headquarters.",
      rivers: ["Guadalupe River", "South Llano River"],
      lat: 29.7385,
      lng: -98.1095,
    },
    {
      name: "The Angling Company",
      city: "Austin",
      state: "TX",
      address: "6206 Bee Cave Rd, Austin, TX 78746",
      phone: "(512) 328-6500",
      website: "https://www.theanglingcompany.com",
      notes: "Austin's go-to shop for Hill Country rivers and Central Texas warm-water fly fishing.",
      rivers: ["Pedernales River", "Frio River", "San Marcos River"],
      lat: 30.2961,
      lng: -97.8004,
    },
    {
      name: "Hook Line & Sinker",
      city: "Austin",
      state: "TX",
      address: "11811 N Lamar Blvd, Austin, TX 78753",
      phone: "(512) 452-9045",
      website: "https://www.hooklinesinker.com",
      notes: "Full-service Austin shop for Guadalupe trout, bass poppers, and carp on the Colorado.",
      rivers: ["Colorado River (Austin)", "Guadalupe River"],
      lat: 30.3738,
      lng: -97.7069,
    },
    {
      name: "Tailwaters Fly Fishing",
      city: "Dallas",
      state: "TX",
      address: "1933 E Levee St, Dallas, TX 75207",
      phone: "(214) 741-1281",
      website: "https://www.tailwatersflyfishing.com",
      notes: "Dallas's premier fly shop, Red River carp, Lake Tawakoni bass, and Texas saltwater redfish on the fly.",
      rivers: ["Trinity River", "Red River", "Guadalupe River"],
      lat: 32.7888,
      lng: -96.8025,
    },
  ],

  UT: [
    {
      name: "Western Rivers Flyfisher",
      city: "Salt Lake City",
      state: "UT",
      address: "1071 E 900 S, Salt Lake City, UT 84105",
      phone: "(801) 521-6424",
      website: "https://www.westernriversflyfisher.com",
      notes: "Utah's most respected fly shop, Provo River and Green River tailwater masters with top-tier guiding.",
      rivers: ["Provo River", "Green River", "Weber River"],
      lat: 40.7473,
      lng: -111.8652,
    },
    {
      name: "Jans Mountain Outfitters",
      city: "Park City",
      state: "UT",
      address: "1600 Park Ave, Park City, UT 84060",
      phone: "(800) 745-1020",
      website: "https://www.jans.com",
      notes: "Park City's premier fly shop, Provo River brown trout and Strawberry Reservoir rainbow specialists with expert guiding.",
      rivers: ["Provo River", "Weber River", "Strawberry River"],
      lat: 40.6445,
      lng: -111.4980,
    },
    {
      name: "Trout Creek Flies",
      city: "Dutch John",
      state: "UT",
      address: "1155 Little Hole Rd, Dutch John, UT 84023",
      phone: "(435) 885-3355",
      website: "https://troutcreekflies.com",
      notes: "The essential shop at Flaming Gorge, Green River tailwater guides with access to one of the West's great trout fisheries.",
      rivers: ["Green River", "Flaming Gorge Reservoir", "Sheep Creek"],
      lat: 40.9271,
      lng: -109.3994,
    },
  ],

  VT: [
    {
      name: "The Fly Rod Shop",
      city: "Stowe",
      state: "VT",
      address: "703 Waterbury Rd, Stowe, VT 05672",
      phone: "(802) 253-7346",
      website: "https://www.flyrodshop.com",
      notes: "Vermont's most celebrated fly shop, Lamoille and Winooski river wild trout with guided instructional classes.",
      rivers: ["Lamoille River", "Winooski River", "Little River"],
      lat: 44.4633,
      lng: -72.6763,
    },
    {
      name: "Vermont Fly Fishing School",
      city: "Quechee",
      state: "VT",
      address: "5765 Woodstock Rd, Quechee, VT 05059",
      phone: "(802) 295-7620",
      website: "https://www.quechee.com/outdoor-activities/fishing/",
      notes: "Vermont's fly fishing school on the Ottauquechee, novice-friendly instruction and guided trips on a pristine Vermont river.",
      rivers: ["Ottauquechee River", "White River", "Black River"],
      lat: 43.6282,
      lng: -72.4299,
    },
    {
      name: "Middlebury Mountaineer",
      city: "Middlebury",
      state: "VT",
      address: "10 Washington St, Middlebury, VT 05753",
      phone: "(802) 388-7735",
      website: "https://www.middleburymountaineer.com",
      notes: "Western Vermont's outdoor shop with fly fishing department, Otter Creek and Champlain Valley trout and bass.",
      rivers: ["Otter Creek", "New Haven River", "Dog River"],
      lat: 44.0103,
      lng: -73.1668,
    },
  ],

  VA: [
    {
      name: "Murray's Fly Shop",
      city: "Edinburg",
      state: "VA",
      address: "121 S Main St, Edinburg, VA 22824",
      phone: "(540) 984-4212",
      website: "https://www.murraysflyshop.com",
      notes: "Virginia's most storied fly shop, Shenandoah Valley smallmouth bass specialists and George Harvey wet fly tradition.",
      rivers: ["North Fork Shenandoah River", "South Fork Shenandoah River", "Rapidan River"],
      lat: 38.8204,
      lng: -78.5650,
    },
    {
      name: "South River Fly Shop",
      city: "Waynesboro",
      state: "VA",
      address: "323 W Main St, Waynesboro, VA 22980",
      phone: "(540) 942-5566",
      website: "https://southriverflyshop.com",
      notes: "Blue Ridge Virginia's top trout shop, South River wild trout and upper James River smallmouth bass specialists.",
      rivers: ["South River", "Tye River", "Maury River"],
      lat: 38.0685,
      lng: -78.8893,
    },
    {
      name: "Mossy Creek Fly Fishing",
      city: "Harrisonburg",
      state: "VA",
      address: "30 W Market St, Harrisonburg, VA 22801",
      phone: "(540) 434-2444",
      website: "https://www.mossycreekflyfishing.com",
      notes: "Shenandoah Valley's beloved shop, Mossy Creek limestone spring creek and Maury River brown trout specialists.",
      rivers: ["Mossy Creek", "Maury River", "Shenandoah River"],
      lat: 38.4496,
      lng: -78.8689,
    },
  ],

  WA: [
    {
      name: "Red's Fly Shop",
      city: "Ellensburg",
      state: "WA",
      address: "521 N Poplar St, Ellensburg, WA 98926",
      phone: "(509) 933-2337",
      website: "https://redsflyfishing.com",
      notes: "Washington's legendary fly shop on the Yakima River, steelhead, trout, and the celebrated Yakima caddis hatches.",
      rivers: ["Yakima River", "Klickitat River", "Columbia River"],
      lat: 46.9965,
      lng: -120.5479,
    },
    {
      name: "Emerald Water Anglers",
      city: "Seattle",
      state: "WA",
      address: "5405 Ballard Ave NW, Seattle, WA 98107",
      phone: "(206) 708-7250",
      website: "https://emeraldwateranglers.com",
      notes: "Seattle's top fly shop, Puget Sound sea-run cutthroat, Pacific steelhead, and Cascades wild trout experts.",
      rivers: ["Puget Sound", "Skykomish River", "Snoqualmie River"],
      lat: 47.6625,
      lng: -122.3834,
    },
    {
      name: "The Avid Angler",
      city: "Lake Forest Park",
      state: "WA",
      address: "17171 Bothell Way NE, Lake Forest Park, WA 98155",
      phone: "(206) 362-4030",
      website: "https://www.avidangler.com",
      notes: "North Seattle's beloved fly shop, Burke-Gilman Trail carp, Skykomish steelhead, and Puget Sound sea-run cutthroat.",
      rivers: ["Skykomish River", "Snohomish River", "Lake Washington"],
      lat: 47.7560,
      lng: -122.2827,
    },
    {
      name: "Waters West Fly Shop",
      city: "Port Angeles",
      state: "WA",
      address: "921 E Front St, Port Angeles, WA 98362",
      phone: "(360) 417-0937",
      website: "https://www.waterswest.com",
      notes: "Olympic Peninsula steelhead specialists, Sol Duc, Hoh, and Calawah wild steelhead with some of America's best guides.",
      rivers: ["Sol Duc River", "Hoh River", "Calawah River"],
      lat: 48.1187,
      lng: -123.4290,
    },
  ],

  WV: [
    {
      name: "White Fly Outfitters",
      city: "Harpers Ferry",
      state: "WV",
      address: "4332 William L Wilson Fwy, Harpers Ferry, WV 25425",
      phone: "(304) 876-8030",
      website: "https://www.whiteflyoutfitters.com",
      notes: "Eastern WV's premier shop at the confluence of the Shenandoah and Potomac, smallmouth bass and wild brown trout.",
      rivers: ["Shenandoah River", "Potomac River", "Cacapon River"],
      lat: 39.3162,
      lng: -77.7296,
    },
    {
      name: "Elk Springs Fly Shop",
      city: "Monterville",
      state: "WV",
      address: "228 Dry Branch Rd, Monterville, WV 26282",
      phone: "(304) 924-6682",
      website: "https://elkspringsresort.com",
      notes: "Deep in the Monongahela National Forest, Elk River and Williams River wild native brook trout in remote mountain country.",
      rivers: ["Elk River", "Williams River", "Cranberry River"],
      lat: 38.5031,
      lng: -80.3415,
    },
    {
      name: "Sportsman's Emporium",
      city: "Morgantown",
      state: "WV",
      address: "821 Greenbag Rd, Morgantown, WV 26508",
      phone: "(304) 291-2286",
      website: "https://www.wvsportsmansemporium.com",
      notes: "North-central WV's full-service outdoor shop, Cheat River wild trout and Monongahela River smallmouth bass.",
      rivers: ["Cheat River", "Monongahela River", "Blackwater River"],
      lat: 39.6148,
      lng: -79.9737,
    },
  ],

  WI: [
    {
      name: "Driftless Angler",
      city: "Viroqua",
      state: "WI",
      address: "106 S Main St, Viroqua, WI 54665",
      phone: "(608) 637-8779",
      website: "https://www.driftlessangler.com",
      notes: "Wisconsin's top-rated fly shop, Driftless Area limestone spring creeks and wild brown trout with a passionate following.",
      rivers: ["West Fork Kickapoo River", "Timber Coulee Creek", "Rush River"],
      lat: 43.5569,
      lng: -90.8832,
    },
    {
      name: "Lund's Fly Shop",
      city: "River Falls",
      state: "WI",
      address: "102 N Main St, River Falls, WI 54022",
      phone: "(715) 425-2415",
      website: "https://www.lundsflyshop.com",
      notes: "Kinnickinnic River hometown shop, 'The Kinni' is Wisconsin's top spring creek and Lund's has served it for generations.",
      rivers: ["Kinnickinnic River", "Rush River", "Willow River"],
      lat: 44.8613,
      lng: -92.6258,
    },
    {
      name: "Tight Lines Fly Fishing Co.",
      city: "De Pere",
      state: "WI",
      address: "1534 Mid Valley Dr, De Pere, WI 54115",
      phone: "(920) 336-4106",
      website: "https://www.tightlinesflyfishing.com",
      notes: "Fox River Valley fly shop, Green Bay Lake Michigan steelhead, Fox River smallmouth, and Driftless trout.",
      rivers: ["Fox River", "Peshtigo River", "Brule River"],
      lat: 44.4274,
      lng: -88.0762,
    },
  ],

  WY: [
    {
      name: "Platte River Fly Shop",
      city: "Casper",
      state: "WY",
      address: "7400 State Hwy 220, Casper, WY 82604",
      phone: "(307) 237-5997",
      website: "https://www.platteriverflyshop.com",
      notes: "Central Wyoming's landmark shop on the North Platte, Grey Reef and Miracle Mile world-class tailwater trout fishing.",
      rivers: ["North Platte River", "Miracle Mile", "Encampment River"],
      lat: 42.7948,
      lng: -106.4024,
    },
    {
      name: "Westbank Anglers",
      city: "Teton Village",
      state: "WY",
      address: "3655 N Moose Wilson Rd, Teton Village, WY 83025",
      phone: "(307) 733-6483",
      website: "https://www.westbankanglers.com",
      notes: "Jackson Hole's elite fly shop, Snake River cutthroat in Grand Teton National Park with world-class drift boat guides.",
      rivers: ["Snake River", "Green River", "South Fork Snake River"],
      lat: 43.5876,
      lng: -110.8272,
    },
    {
      name: "Fly Shop of the Bighorns",
      city: "Sheridan",
      state: "WY",
      address: "201 N Main St, Sheridan, WY 82801",
      phone: "(307) 672-5866",
      website: "https://www.sheridanflyfishing.com",
      notes: "Northern Wyoming's go-to shop, Bighorn River tailwater brown trout and Little Bighorn tributaries wild trout.",
      rivers: ["Bighorn River", "Little Bighorn River", "Tongue River"],
      lat: 44.7972,
      lng: -106.9563,
    },
  ],
};

export function getShopsForState(abbr: string): FlyShop[] {
  return shopsByState[abbr.toUpperCase()] ?? [];
}
