export interface StateInfo {
  name: string;
  abbr: string;
  region: string;
  topRivers: string[];
  targetSpecies: string[];
  bestMonths: number[];
  hatches: string[];
  quickTip: string;
  licenseUrl: string;
}

export const stateData: Record<string, StateInfo> = {
  // ── MONTANA ROCKIES ────────────────────────────────────────────────────────
  MT: {
    name: "Montana",
    abbr: "MT",
    region: "montana_rockies",
    topRivers: ["Madison River", "Yellowstone River", "Gallatin River", "Missouri River", "Big Hole River"],
    targetSpecies: ["Brown Trout", "Rainbow Trout", "Cutthroat Trout", "Brook Trout"],
    bestMonths: [6, 7, 8, 9],
    hatches: ["Salmonfly (June)", "PMD (July-Aug)", "Trico (Aug-Sep)", "Baetis (Sep-Oct)"],
    quickTip: "The Madison between Ennis Lake and Quake Lake fishes best early morning during salmonfly season, wade the riffles and target seams along the bank.",
    licenseUrl: "https://fwp.mt.gov/buyandapply/fishing",
  },
  WY: {
    name: "Wyoming",
    abbr: "WY",
    region: "montana_rockies",
    topRivers: ["North Platte River", "Green River", "Snake River", "Shoshone River", "Firehole River"],
    targetSpecies: ["Cutthroat Trout", "Brown Trout", "Rainbow Trout", "Brook Trout"],
    bestMonths: [6, 7, 8, 9],
    hatches: ["Salmonfly (June)", "PMD (July)", "Trico (Aug)", "Baetis (Sep-Oct)"],
    quickTip: "The Firehole River in Yellowstone fishes well in spring and fall, thermal inputs keep water temps elevated, so avoid mid-summer when temps spike.",
    licenseUrl: "https://wgfd.wyo.gov/Fishing/Fish-Regulation",
  },
  ID: {
    name: "Idaho",
    abbr: "ID",
    region: "montana_rockies",
    topRivers: ["Henry's Fork", "South Fork Snake River", "Boise River", "Clearwater River", "Silver Creek"],
    targetSpecies: ["Rainbow Trout", "Cutthroat Trout", "Steelhead", "Brown Trout"],
    bestMonths: [6, 7, 8, 9, 10],
    hatches: ["Green Drake (June-July)", "PMD (July-Aug)", "Trico (Aug)", "Caddis (Sep-Oct)"],
    quickTip: "Henry's Fork below Harriman Ranch is a technical dry-fly fishery, use long fine tippets (6X) and match the hatch precisely for its wild rainbows.",
    licenseUrl: "https://idfg.idaho.gov/licenses",
  },
  CO: {
    name: "Colorado",
    abbr: "CO",
    region: "montana_rockies",
    topRivers: ["Arkansas River", "South Platte River", "Fryingpan River", "Blue River", "Gunnison River"],
    targetSpecies: ["Rainbow Trout", "Brown Trout", "Cutthroat Trout", "Brook Trout"],
    bestMonths: [4, 5, 6, 9, 10],
    hatches: ["Midge (year-round)", "Blue-Winged Olive (Apr-May, Sep-Oct)", "PMD (June-Aug)", "Caddis (May-June)"],
    quickTip: "The Fryingpan River below Ruedi Reservoir is a world-class tailwater, midge larvae and emergers in sizes 22-26 are the bread-and-butter patterns.",
    licenseUrl: "https://cpw.state.co.us/buyapply/Pages/Fishing.aspx",
  },
  UT: {
    name: "Utah",
    abbr: "UT",
    region: "montana_rockies",
    topRivers: ["Green River", "Provo River", "Logan River", "Weber River", "Beaver River"],
    targetSpecies: ["Rainbow Trout", "Brown Trout", "Cutthroat Trout", "Brook Trout"],
    bestMonths: [4, 5, 6, 9, 10],
    hatches: ["Midge (Jan-Mar)", "Blue-Winged Olive (Apr-May)", "Caddis (May-June)", "PMD (July-Aug)"],
    quickTip: "The Green River below Flaming Gorge Dam (A-C sections) holds massive browns, nymph rigs with San Juan Worms and midge larvae produce year-round.",
    licenseUrl: "https://wildlife.utah.gov/licenses-permits.html",
  },
  NV: {
    name: "Nevada",
    abbr: "NV",
    region: "montana_rockies",
    topRivers: ["Truckee River", "Walker River", "Humboldt River", "Ruby Valley Streams", "Carson River"],
    targetSpecies: ["Rainbow Trout", "Brown Trout", "Lahontan Cutthroat Trout", "Brook Trout"],
    bestMonths: [4, 5, 6, 9, 10],
    hatches: ["Midge (Mar-Apr)", "Caddis (May-June)", "PMD (June-July)", "Trico (Aug-Sep)"],
    quickTip: "The upper Truckee near Reno sees strong evening caddis hatches in May and June, elk hair caddis in size 14-16 during the last two hours of light.",
    licenseUrl: "https://www.ndow.org/fish/fishing-licenses/",
  },

  // ── PACIFIC NORTHWEST ──────────────────────────────────────────────────────
  WA: {
    name: "Washington",
    abbr: "WA",
    region: "pacific_northwest",
    topRivers: ["Yakima River", "Methow River", "Wenatchee River", "Skagit River", "Klickitat River"],
    targetSpecies: ["Steelhead", "Rainbow Trout", "Cutthroat Trout", "Bull Trout"],
    bestMonths: [3, 4, 5, 9, 10, 11],
    hatches: ["Skwala Stonefly (Mar-Apr)", "PMD (June-July)", "Caddis (May-Sep)", "October Caddis (Sep-Oct)"],
    quickTip: "The Yakima Canyon is Washington's premier dry-fly river, skwala stoneflies in late March bring big hatches and aggressive rainbows to the surface.",
    licenseUrl: "https://wdfw.wa.gov/fishing/regulations",
  },
  OR: {
    name: "Oregon",
    abbr: "OR",
    region: "pacific_northwest",
    topRivers: ["Deschutes River", "Rogue River", "North Umpqua River", "McKenzie River", "Metolius River"],
    targetSpecies: ["Steelhead", "Rainbow Trout", "Brown Trout", "Cutthroat Trout"],
    bestMonths: [4, 5, 6, 8, 9, 10],
    hatches: ["Salmonfly (May-June)", "Golden Stonefly (June-July)", "PMD (July)", "October Caddis (Sep-Oct)"],
    quickTip: "The Deschutes below Maupin produces legendary steelhead in September, swing classic wet flies at dusk through the tail-outs of long glides.",
    licenseUrl: "https://myodfw.com/fishing/licensing",
  },

  // ── CALIFORNIA ────────────────────────────────────────────────────────────
  CA: {
    name: "California",
    abbr: "CA",
    region: "california",
    topRivers: ["McCloud River", "Hat Creek", "Fall River", "Upper Sacramento River", "Owens River"],
    targetSpecies: ["Rainbow Trout", "Brown Trout", "Golden Trout", "Brook Trout"],
    bestMonths: [4, 5, 6, 9, 10],
    hatches: ["PMD (May-July)", "Trico (July-Sep)", "Caddis (Apr-June)", "Blue-Winged Olive (Oct-Nov)"],
    quickTip: "Hat Creek and Fall River in Shasta County are spring-creek fisheries requiring stealthy presentations, size 18-22 dries and 6X tippet are the standard.",
    licenseUrl: "https://wildlife.ca.gov/Licensing/Fishing",
  },

  // ── ALASKA ────────────────────────────────────────────────────────────────
  AK: {
    name: "Alaska",
    abbr: "AK",
    region: "alaska",
    topRivers: ["Kenai River", "Naknek River", "Bristol Bay drainages", "Copper River", "Situk River"],
    targetSpecies: ["King Salmon", "Sockeye Salmon", "Rainbow Trout", "Arctic Grayling"],
    bestMonths: [6, 7, 8, 9],
    hatches: ["Egg patterns (July-Sep)", "Sculpin (year-round)", "Flesh flies (Aug-Sep)", "Caddis (June-July)"],
    quickTip: "On Bristol Bay streams, large rainbows stack below spawning sockeye in July, dead-drift flesh flies and egg patterns tight to the bottom for the biggest fish.",
    licenseUrl: "https://www.adfg.alaska.gov/index.cfm?adfg=license.main",
  },

  // ── SOUTHWEST ─────────────────────────────────────────────────────────────
  NM: {
    name: "New Mexico",
    abbr: "NM",
    region: "southwest",
    topRivers: ["San Juan River", "Rio Grande", "Pecos River", "Cimarron River", "Jemez River"],
    targetSpecies: ["Rainbow Trout", "Brown Trout", "Cutthroat Trout", "Brook Trout"],
    bestMonths: [3, 4, 5, 9, 10, 11],
    hatches: ["Midge (year-round)", "Blue-Winged Olive (Mar-Apr, Oct-Nov)", "Caddis (May-June)", "PMD (June-Aug)"],
    quickTip: "The San Juan River below Navajo Dam is one of the Southwest's best tailwaters, fish tiny midges (size 24-28) year-round in the Quality Waters section.",
    licenseUrl: "https://www.wildlife.state.nm.us/fishing/licenses-and-info/",
  },
  AZ: {
    name: "Arizona",
    abbr: "AZ",
    region: "southwest",
    topRivers: ["Lee's Ferry (Colorado River)", "Oak Creek", "Black River", "Little Colorado River", "White River"],
    targetSpecies: ["Rainbow Trout", "Brown Trout", "Apache Trout", "Brook Trout"],
    bestMonths: [3, 4, 5, 10, 11],
    hatches: ["Midge (Nov-Mar)", "Blue-Winged Olive (Mar-May)", "Caddis (Apr-June)", "Trico (Aug-Sep)"],
    quickTip: "Lee's Ferry below Glen Canyon Dam is Arizona's premier trout fishery, clear water and big rainbows demand precise midge and nymph presentations.",
    licenseUrl: "https://www.azgfd.com/fishing/licenses/",
  },

  // ── GREAT PLAINS ──────────────────────────────────────────────────────────
  ND: {
    name: "North Dakota",
    abbr: "ND",
    region: "great_plains",
    topRivers: ["Sheyenne River", "James River", "Heart River", "Missouri River (tailwaters)", "Souris River"],
    targetSpecies: ["Smallmouth Bass", "Walleye", "Northern Pike", "Carp"],
    bestMonths: [5, 6, 7, 8, 9],
    hatches: ["Caddis (May-June)", "Hex (June-July)", "Terrestrials (July-Aug)", "Midges (Apr-May)"],
    quickTip: "The Missouri River tailwaters below Garrison Dam hold surprising populations of large sauger and walleye, streamer fishing is most productive in spring.",
    licenseUrl: "https://gf.nd.gov/licensing",
  },
  SD: {
    name: "South Dakota",
    abbr: "SD",
    region: "great_plains",
    topRivers: ["Rapid Creek", "Spearfish Creek", "French Creek", "Belle Fourche River", "Fall River"],
    targetSpecies: ["Brown Trout", "Rainbow Trout", "Brook Trout", "Smallmouth Bass"],
    bestMonths: [4, 5, 6, 9, 10],
    hatches: ["Blue-Winged Olive (Apr-May)", "Caddis (May-June)", "PMD (June-July)", "Trico (Aug-Sep)"],
    quickTip: "Rapid Creek through Rapid City is a surprising urban trout fishery, access is excellent and browns up to 20 inches are common in town.",
    licenseUrl: "https://gfp.sd.gov/licenses/",
  },
  NE: {
    name: "Nebraska",
    abbr: "NE",
    region: "great_plains",
    topRivers: ["Platte River", "Niobrara River", "Snake River (Sandhills)", "Dismal River", "Loup River"],
    targetSpecies: ["Smallmouth Bass", "Trout (stocked)", "Carp", "Northern Pike"],
    bestMonths: [5, 6, 7, 8, 9],
    hatches: ["Caddis (May-June)", "Terrestrials (July-Aug)", "Hoppers (July-Sep)", "Midges (Mar-Apr)"],
    quickTip: "The Sandhills' spring-fed streams (Dismal, Snake) offer clear water smallmouth fishing with dry flies and poppers from June through August.",
    licenseUrl: "https://outdoornebraska.gov/fishing/",
  },
  KS: {
    name: "Kansas",
    abbr: "KS",
    region: "great_plains",
    topRivers: ["Flint Hills streams", "Arkansas River", "Neosho River", "Cottonwood River", "Walnut River"],
    targetSpecies: ["Smallmouth Bass", "Largemouth Bass", "Carp", "White Bass"],
    bestMonths: [4, 5, 6, 9, 10],
    hatches: ["Caddis (May-June)", "Hoppers (July-Aug)", "Trico (Aug-Sep)", "Midges (Mar-Apr)"],
    quickTip: "Flint Hills prairie streams offer surprising smallmouth action on streamers and crayfish patterns, best waded during low water in late summer.",
    licenseUrl: "https://ksoutdoors.com/Fishing/Fishing-Licenses-Permits",
  },
  OK: {
    name: "Oklahoma",
    abbr: "OK",
    region: "great_plains",
    topRivers: ["Illinois River", "Baron Fork", "Glover River", "Lower Mountain Fork River", "Blue River"],
    targetSpecies: ["Rainbow Trout (stocked)", "Smallmouth Bass", "Largemouth Bass", "Spotted Bass"],
    bestMonths: [3, 4, 5, 10, 11, 12],
    hatches: ["Midges (Nov-Mar)", "Caddis (Apr-May)", "Hoppers (July-Sep)", "Sulphur (May-June)"],
    quickTip: "The Lower Mountain Fork River (Broken Bow) is Oklahoma's best trout tailwater, nymphing with midge larvae and small San Juan Worms is most consistent.",
    licenseUrl: "https://www.wildlifedepartment.com/fishing/license",
  },
  TX: {
    name: "Texas",
    abbr: "TX",
    region: "texas_hill_country",
    topRivers: ["Guadalupe River", "South Llano River", "Frio River", "San Marcos River", "Pedernales River"],
    targetSpecies: ["Rainbow Trout (stocked winter)", "Guadalupe Bass", "Largemouth Bass", "Carp"],
    bestMonths: [11, 12, 1, 2, 3],
    hatches: ["Midges (Dec-Feb)", "Caddis (Mar-Apr)", "Guadalupe Bass on poppers (May-Oct)"],
    quickTip: "The Guadalupe River below Canyon Lake dam is Texas's only quality trout tailwater, cold water year-round, best Nov-Mar.",
    licenseUrl: "https://tpwd.texas.gov/business/licenses/online_sales/",
  },
  MO: {
    name: "Missouri",
    abbr: "MO",
    region: "great_plains",
    topRivers: ["North Fork of the White River", "Eleven Point River", "Current River", "Gasconade River", "Meramec River"],
    targetSpecies: ["Brown Trout", "Rainbow Trout", "Smallmouth Bass", "Largemouth Bass"],
    bestMonths: [3, 4, 5, 9, 10, 11],
    hatches: ["Caddis (Apr-May)", "Sulphur (May-June)", "Blue-Winged Olive (Sep-Oct)", "Midges (Jan-Mar)"],
    quickTip: "The Ozark spring creeks (Current, Eleven Point) run gin-clear year-round, sight-fishing to rising brown trout on sulphur dries in late May is world-class.",
    licenseUrl: "https://mdc.mo.gov/licenses-permits-and-fees",
  },
  IA: {
    name: "Iowa",
    abbr: "IA",
    region: "great_plains",
    topRivers: ["Upper Iowa River", "Yellow River", "Volga River", "Turkey River", "Little Maquoketa River"],
    targetSpecies: ["Brown Trout", "Rainbow Trout", "Brook Trout", "Smallmouth Bass"],
    bestMonths: [4, 5, 6, 9, 10],
    hatches: ["Caddis (May-June)", "Sulphur (May-June)", "PMD (June-July)", "Blue-Winged Olive (Sep-Oct)"],
    quickTip: "Northeast Iowa's Driftless Area streams hold wild brown trout in surprisingly small, cold creeks, look for limestone springs and fish small dry flies upstream.",
    licenseUrl: "https://www.iowadnr.gov/Hunting-Fishing/Fishing/Fishing-License",
  },
  MN: {
    name: "Minnesota",
    abbr: "MN",
    region: "great_plains",
    topRivers: ["Whitewater River", "Root River", "Kinnickinnic River (WI border)", "North Shore streams", "Brule River"],
    targetSpecies: ["Brown Trout", "Brook Trout", "Rainbow Trout", "Smallmouth Bass"],
    bestMonths: [4, 5, 6, 9, 10],
    hatches: ["Caddis (May-June)", "Sulphur (May-June)", "Hex (June)", "Trico (Aug-Sep)"],
    quickTip: "Southeast Minnesota's Driftless streams are spring-fed and cold, fish upstream with small dry flies and expect wild browns in even the tiniest limestone creeks.",
    licenseUrl: "https://www.dnr.state.mn.us/licenses/fishing/index.html",
  },

  // ── GREAT LAKES ───────────────────────────────────────────────────────────
  MI: {
    name: "Michigan",
    abbr: "MI",
    region: "great_lakes",
    topRivers: ["Au Sable River", "Pere Marquette River", "Manistee River", "Muskegon River", "Boardman River"],
    targetSpecies: ["Brown Trout", "Rainbow Trout (Steelhead)", "Brook Trout", "Chinook Salmon"],
    bestMonths: [4, 5, 6, 9, 10, 11],
    hatches: ["Hendrickson (May)", "Sulphur (May-June)", "Hex (June)", "Trico (July-Aug)"],
    quickTip: "The Au Sable's famous Hex hatch in mid-June draws big brown trout to the surface after dark, fish size 6-8 Hex dries in the first two hours of darkness.",
    licenseUrl: "https://www.michigan.gov/dnr/licenses-and-permits/fishing-licenses",
  },
  WI: {
    name: "Wisconsin",
    abbr: "WI",
    region: "great_lakes",
    topRivers: ["Bois Brule River", "Wolf River", "Namekagon River", "Prairie River", "Oconto River"],
    targetSpecies: ["Brown Trout", "Brook Trout", "Steelhead", "Smallmouth Bass"],
    bestMonths: [4, 5, 6, 9, 10],
    hatches: ["Hendrickson (May)", "Caddis (May-June)", "Hex (June)", "Trico (Aug)"],
    quickTip: "The Bois Brule is Wisconsin's blue-ribbon trout stream, spring brown trout fishing before runoff clears is excellent with streamers and large nymphs.",
    licenseUrl: "https://dnr.wisconsin.gov/topic/fishing/regulations",
  },
  IL: {
    name: "Illinois",
    abbr: "IL",
    region: "great_lakes",
    topRivers: ["Chicago River", "Fox River", "Des Plaines River", "Kankakee River", "Rock River"],
    targetSpecies: ["Smallmouth Bass", "Largemouth Bass", "Carp", "Channel Catfish"],
    bestMonths: [5, 6, 7, 8, 9],
    hatches: ["Caddis (May-June)", "Hoppers (July-Aug)", "Hex (June)", "Trico (Aug-Sep)"],
    quickTip: "The Fox River below Algonquin Dam holds a surprising population of smallmouth, streamer fishing and crayfish patterns work best from May through September.",
    licenseUrl: "https://www2.illinois.gov/dnr/LicensesPermits/Pages/FishingLicenses.aspx",
  },
  IN: {
    name: "Indiana",
    abbr: "IN",
    region: "great_lakes",
    topRivers: ["St. Joseph River", "Tippecanoe River", "Sugar Creek", "Wildcat Creek", "Elkhart River"],
    targetSpecies: ["Smallmouth Bass", "Largemouth Bass", "Steelhead (Lake Michigan tribs)", "Carp"],
    bestMonths: [4, 5, 6, 9, 10],
    hatches: ["Caddis (May-June)", "Sulphur (May-June)", "Hex (June)", "Trico (Aug)"],
    quickTip: "Lake Michigan tributary streams (St. Joe, Elkhart) see steelhead runs in March and April, swinging wet flies and egg patterns near tributary mouths is most productive.",
    licenseUrl: "https://www.in.gov/dnr/fish-and-wildlife/fishing/license-information/",
  },
  OH: {
    name: "Ohio",
    abbr: "OH",
    region: "great_lakes",
    topRivers: ["Grand River", "Chagrin River", "Rocky River", "Vermilion River", "Mad River"],
    targetSpecies: ["Steelhead", "Brown Trout", "Smallmouth Bass", "Carp"],
    bestMonths: [3, 4, 5, 10, 11, 12],
    hatches: ["Midges (Dec-Mar)", "Blue-Winged Olive (Mar-May)", "Caddis (Apr-June)", "Sulphur (May-June)"],
    quickTip: "Northeast Ohio's Lake Erie tributaries (Grand, Chagrin) host prolific steelhead runs from October through April, egg patterns and small nymphs under indicators are the standard approach.",
    licenseUrl: "https://ohiodnr.gov/buy-and-apply/hunting-fishing-boating/fishing-licenses-permits",
  },

  // ── NORTHEAST ────────────────────────────────────────────────────────────
  ME: {
    name: "Maine",
    abbr: "ME",
    region: "northeast",
    topRivers: ["Kennebec River", "Penobscot River", "Rapid River", "Roach River", "West Branch Penobscot"],
    targetSpecies: ["Brook Trout", "Landlocked Salmon", "Brown Trout", "Rainbow Trout"],
    bestMonths: [5, 6, 7, 8, 9],
    hatches: ["Hendrickson (May)", "Caddis (May-June)", "Gray Drake (June)", "Trico (Aug)"],
    quickTip: "Maine's remote pond outlets (Rapid River, Roach River) hold exceptional wild brook trout, fish streamers in the morning and dry flies during evening hatches.",
    licenseUrl: "https://www.maine.gov/ifw/hunting-fishing/fishing/license-registration/index.html",
  },
  NH: {
    name: "New Hampshire",
    abbr: "NH",
    region: "northeast",
    topRivers: ["Connecticut River", "Androscoggin River", "Ammonoosuc River", "Swift River", "Contoocook River"],
    targetSpecies: ["Brook Trout", "Brown Trout", "Rainbow Trout", "Landlocked Salmon"],
    bestMonths: [4, 5, 6, 9, 10],
    hatches: ["Hendrickson (May)", "Sulphur (May-June)", "Caddis (May-June)", "Blue-Winged Olive (Sep-Oct)"],
    quickTip: "The Connecticut River's upper reaches hold wild brown trout, hatches track about two weeks behind southern New England, so extend your season by fishing north.",
    licenseUrl: "https://www.wildlife.nh.gov/fishing/licenses.html",
  },
  VT: {
    name: "Vermont",
    abbr: "VT",
    region: "northeast",
    topRivers: ["Battenkill River", "Lamoille River", "White River", "Winooski River", "West River"],
    targetSpecies: ["Brown Trout", "Brook Trout", "Rainbow Trout", "Landlocked Salmon"],
    bestMonths: [4, 5, 6, 9, 10],
    hatches: ["Hendrickson (May)", "Sulphur (May-June)", "Light Cahill (June-July)", "Trico (Aug)"],
    quickTip: "The Battenkill is Vermont's most storied trout stream, its notoriously selective wild browns require drag-free presentations and accurate pattern matching.",
    licenseUrl: "https://vtfishandwildlife.com/fish/fishing-licenses-permits-and-registrations",
  },
  MA: {
    name: "Massachusetts",
    abbr: "MA",
    region: "northeast",
    topRivers: ["Deerfield River", "Swift River", "Farmington River (CT border)", "Millers River", "Westfield River"],
    targetSpecies: ["Brown Trout", "Rainbow Trout", "Brook Trout", "Atlantic Salmon (stocked)"],
    bestMonths: [4, 5, 6, 9, 10],
    hatches: ["Hendrickson (May)", "Caddis (May-June)", "Sulphur (May-June)", "Blue-Winged Olive (Sep-Oct)"],
    quickTip: "The Swift River below Quabbin Reservoir is a year-round tailwater, fish tiny midges and Blue-Winged Olives in the catch-and-release section for large wild rainbows.",
    licenseUrl: "https://www.mass.gov/how-to/get-a-fishing-license",
  },
  RI: {
    name: "Rhode Island",
    abbr: "RI",
    region: "northeast",
    topRivers: ["Wood River", "Pawcatuck River", "Hunt River", "Moosup River", "Queen River"],
    targetSpecies: ["Brown Trout", "Brook Trout", "Rainbow Trout", "Landlocked Striped Bass"],
    bestMonths: [4, 5, 6, 9, 10],
    hatches: ["Hendrickson (Apr-May)", "Caddis (May-June)", "Sulphur (May-June)", "Trico (Aug)"],
    quickTip: "The Wood River in Arcadia Wildlife Area is Rhode Island's best trout stream, crystal clear with wild browns and consistent Hendrickson hatches in late April.",
    licenseUrl: "https://dem.ri.gov/natural-resources-bureau/fish-wildlife/freshwater-fishing/freshwater-fishing-licenses",
  },
  CT: {
    name: "Connecticut",
    abbr: "CT",
    region: "northeast",
    topRivers: ["Farmington River", "Housatonic River", "Salmon River", "Willimantic River", "Natchaug River"],
    targetSpecies: ["Brown Trout", "Brook Trout", "Rainbow Trout", "Atlantic Salmon (stocked)"],
    bestMonths: [4, 5, 6, 9, 10],
    hatches: ["Hendrickson (Apr-May)", "Sulphur (May-June)", "Caddis (May-June)", "Blue-Winged Olive (Sep-Oct)"],
    quickTip: "The Farmington's catch-and-release section below Hogback Dam is Connecticut's finest trout water, hatches are prolific and fish are measured and selective.",
    licenseUrl: "https://portal.ct.gov/DEEP/Fishing/Freshwater-Fishing/Freshwater-Fishing-Licenses",
  },
  NY: {
    name: "New York",
    abbr: "NY",
    region: "northeast",
    topRivers: ["Delaware River (East Branch)", "Beaverkill River", "Willowemoc Creek", "AuSable River (ADK)", "West Canada Creek"],
    targetSpecies: ["Brown Trout", "Brook Trout", "Rainbow Trout", "Smallmouth Bass"],
    bestMonths: [4, 5, 6, 9, 10],
    hatches: ["Hendrickson (May)", "March Brown (May)", "Sulphur (May-June)", "Trico (Aug)"],
    quickTip: "The Catskill rivers (Beaverkill, Willowemoc) are the birthplace of American dry-fly fishing, fish traditional Catskill-tied dries during evening sulphur hatches for the full experience.",
    licenseUrl: "https://www.dec.ny.gov/permits/6091.html",
  },
  NJ: {
    name: "New Jersey",
    abbr: "NJ",
    region: "northeast",
    topRivers: ["South Branch Raritan River", "Big Flat Brook", "Musconetcong River", "Paulinskill River", "Pequest River"],
    targetSpecies: ["Brown Trout", "Brook Trout", "Rainbow Trout", "Smallmouth Bass"],
    bestMonths: [4, 5, 6, 9, 10],
    hatches: ["Hendrickson (Apr-May)", "Caddis (May-June)", "Sulphur (May-June)", "Trico (Aug)"],
    quickTip: "Big Flat Brook in the Delaware Water Gap area holds wild brown trout, the upper catch-and-release section fishes best in May during the Hendrickson and sulphur hatches.",
    licenseUrl: "https://www.nj.gov/dep/fgw/licreq.htm",
  },
  PA: {
    name: "Pennsylvania",
    abbr: "PA",
    region: "northeast",
    topRivers: ["Penns Creek", "Brodhead Creek", "Letort Spring Run", "Yellow Breeches Creek", "Spring Creek"],
    targetSpecies: ["Brown Trout", "Brook Trout", "Rainbow Trout", "Smallmouth Bass"],
    bestMonths: [4, 5, 6, 9, 10],
    hatches: ["Hendrickson (Apr-May)", "Green Drake (May-June)", "Sulphur (May-June)", "Trico (July-Aug)"],
    quickTip: "Penns Creek's Green Drake hatch in late May is legendary, size 10-12 extended-body drakes produce aggressive surface takes from large wild browns.",
    licenseUrl: "https://www.fishandboat.com/Fishing/FishingLicenses/Pages/default.aspx",
  },
  DE: {
    name: "Delaware",
    abbr: "DE",
    region: "northeast",
    topRivers: ["Brandywine Creek", "Red Clay Creek", "White Clay Creek", "Christina River", "Nanticoke River"],
    targetSpecies: ["Brown Trout", "Brook Trout", "Rainbow Trout", "Smallmouth Bass"],
    bestMonths: [3, 4, 5, 10, 11],
    hatches: ["Hendrickson (Apr)", "Caddis (Apr-May)", "Sulphur (May-June)", "Blue-Winged Olive (Oct)"],
    quickTip: "White Clay Creek's catch-and-release area near Newark holds wild brown trout, fish sulphur emergers in the evening from late May through June for consistent action.",
    licenseUrl: "https://www.fw.delaware.gov/Fishing/Pages/FishingLicenses.aspx",
  },
  MD: {
    name: "Maryland",
    abbr: "MD",
    region: "northeast",
    topRivers: ["Gunpowder Falls", "Big Gunpowder Falls", "Patuxent River", "North Branch Potomac", "Savage River"],
    targetSpecies: ["Brown Trout", "Brook Trout", "Rainbow Trout", "Smallmouth Bass"],
    bestMonths: [3, 4, 5, 10, 11],
    hatches: ["Blue-Winged Olive (Mar-Apr)", "Hendrickson (Apr-May)", "Sulphur (May-June)", "Trico (Aug)"],
    quickTip: "The Gunpowder Falls catch-and-release section below Prettyboy Reservoir is Maryland's top tailwater, midge and BWO patterns dominate year-round in this cold-water fishery.",
    licenseUrl: "https://compass.dnr.maryland.gov/CustomerWeb/licenses/License_list.aspx",
  },

  // ── APPALACHIAN EAST ──────────────────────────────────────────────────────
  VA: {
    name: "Virginia",
    abbr: "VA",
    region: "appalachian_east",
    topRivers: ["New River", "Rapidan River", "Mossy Creek", "North Fork Moormans River", "Smith River"],
    targetSpecies: ["Brown Trout", "Brook Trout", "Rainbow Trout", "Smallmouth Bass"],
    bestMonths: [3, 4, 5, 9, 10, 11],
    hatches: ["Blue-Winged Olive (Mar-Apr)", "Hendrickson (Apr-May)", "Sulphur (May-June)", "Trico (Aug)"],
    quickTip: "Mossy Creek in the Shenandoah Valley is Virginia's most challenging spring creek, the wild brown trout are extremely selective and require precise patterns and long leaders.",
    licenseUrl: "https://www.dgif.virginia.gov/fishing/licenses/",
  },
  WV: {
    name: "West Virginia",
    abbr: "WV",
    region: "appalachian_east",
    topRivers: ["Elk River", "Cranberry River", "Williams River", "Greenbrier River", "New River"],
    targetSpecies: ["Brook Trout", "Brown Trout", "Rainbow Trout", "Smallmouth Bass"],
    bestMonths: [4, 5, 6, 9, 10],
    hatches: ["Quill Gordon (Apr)", "Hendrickson (Apr-May)", "Sulphur (May-June)", "Blue-Winged Olive (Sep-Oct)"],
    quickTip: "The Cranberry and Williams Rivers in the Monongahela National Forest offer wild mountain brook trout in spectacular scenery, small dry flies in sizes 14-18 are all you need.",
    licenseUrl: "https://wvdnr.gov/fishing/fishing-licenses/",
  },
  KY: {
    name: "Kentucky",
    abbr: "KY",
    region: "appalachian_east",
    topRivers: ["Cumberland River (tailwater)", "Red River", "Russell Fork", "Big Sandy River", "Licking River"],
    targetSpecies: ["Rainbow Trout (stocked)", "Brown Trout", "Smallmouth Bass", "Largemouth Bass"],
    bestMonths: [3, 4, 5, 9, 10, 11],
    hatches: ["Midges (Nov-Mar)", "Blue-Winged Olive (Mar-Apr)", "Sulphur (May-June)", "Caddis (Apr-May)"],
    quickTip: "The Cumberland River tailwater below Wolf Creek Dam is Kentucky's top trout fishery, fish egg patterns and San Juan Worms year-round in the catch-and-release section.",
    licenseUrl: "https://fw.ky.gov/Fish/Pages/Fishing-License-Requirements.aspx",
  },
  NC: {
    name: "North Carolina",
    abbr: "NC",
    region: "appalachian_east",
    topRivers: ["Nantahala River", "Davidson River", "South Toe River", "Watauga River", "Tuckasegee River"],
    targetSpecies: ["Brook Trout", "Brown Trout", "Rainbow Trout", "Smallmouth Bass"],
    bestMonths: [4, 5, 6, 9, 10],
    hatches: ["Quill Gordon (Apr)", "Hendrickson (Apr-May)", "Sulphur (May-June)", "Yellow Sally (June-July)"],
    quickTip: "The Davidson River in Pisgah National Forest is the Southeast's most famous trout stream, hatchery-supported water in Avery Creek holds wild rainbows and browns with consistent hatches.",
    licenseUrl: "https://www.ncwildlife.org/licensing/fishing-licenses",
  },
  TN: {
    name: "Tennessee",
    abbr: "TN",
    region: "appalachian_east",
    topRivers: ["Clinch River", "Hiwassee River", "Watauga River", "South Holston River", "Little River (Smokies)"],
    targetSpecies: ["Rainbow Trout", "Brown Trout", "Brook Trout", "Smallmouth Bass"],
    bestMonths: [3, 4, 5, 10, 11],
    hatches: ["Sulphur (May-June)", "Caddis (Apr-May)", "Blue-Winged Olive (Mar-Apr, Oct)", "Midges (Nov-Mar)"],
    quickTip: "The South Holston tailwater below South Holston Dam is Tennessee's most technical fishery, tiny sulfur dries and emergers in sizes 18-22 during evening hatches produce exceptional browns.",
    licenseUrl: "https://www.tn.gov/twra/license-sales/fishing-licenses.html",
  },

  // ── SOUTHEAST ─────────────────────────────────────────────────────────────
  SC: {
    name: "South Carolina",
    abbr: "SC",
    region: "southeast",
    topRivers: ["Chattooga River", "Saluda River", "Edisto River", "Broad River", "Savannah River"],
    targetSpecies: ["Brook Trout", "Brown Trout", "Largemouth Bass", "Redbreast Sunfish"],
    bestMonths: [3, 4, 5, 10, 11],
    hatches: ["Sulphur (Apr-May)", "Caddis (Apr-May)", "Yellow Sally (May-June)", "Terrestrials (July-Sep)"],
    quickTip: "The upper Chattooga on the SC/NC border holds native brook trout in a wild, remote setting, small attractor dries like Elk Hair Caddis and Royal Wulff are reliable.",
    licenseUrl: "https://www.dnr.sc.gov/fishing/freshwater/licenses.html",
  },
  GA: {
    name: "Georgia",
    abbr: "GA",
    region: "southeast",
    topRivers: ["Chattahoochee River", "Toccoa River", "Chestatee River", "Tallulah River", "Etowah River"],
    targetSpecies: ["Rainbow Trout", "Brown Trout", "Brook Trout", "Largemouth Bass"],
    bestMonths: [3, 4, 5, 10, 11],
    hatches: ["Blue-Winged Olive (Mar-Apr)", "Caddis (Apr-May)", "Sulphur (Apr-June)", "Yellow Sally (May-June)"],
    quickTip: "The Toccoa River tailwater below Blue Ridge Dam is Georgia's best cold-water fishery, large browns hold in the deep pools below the dam year-round.",
    licenseUrl: "https://www.georgiawildlife.com/fishing/licenses",
  },
  FL: {
    name: "Florida",
    abbr: "FL",
    region: "southeast",
    topRivers: ["Everglades flats", "Florida Keys flats", "Suwannee River", "St. Johns River", "Ochlockonee River"],
    targetSpecies: ["Tarpon", "Bonefish", "Redfish", "Largemouth Bass"],
    bestMonths: [3, 4, 5, 10, 11],
    hatches: ["Crab patterns (Apr-June)", "Shrimp patterns (year-round)", "Poppers for bass (Mar-Oct)", "Crabs for permit (Apr-July)"],
    quickTip: "Florida fly fishing means saltwater flats, sight-fishing to tailing redfish in backcountry mangroves and tarpon on the flats requires stealth, accuracy, and fast presentations.",
    licenseUrl: "https://myfwc.com/license/recreational/freshwater-fishing/",
  },
  AL: {
    name: "Alabama",
    abbr: "AL",
    region: "southeast",
    topRivers: ["Sipsey Fork (Smith Lake)", "Little River Canyon", "Cahaba River", "Tallapoosa River", "Mulberry Fork"],
    targetSpecies: ["Rainbow Trout (stocked)", "Largemouth Bass", "Spotted Bass", "Striped Bass"],
    bestMonths: [10, 11, 12, 1, 2, 3],
    hatches: ["Midges (Dec-Feb)", "Caddis (Mar-Apr)", "Sulphur (Apr-May)", "Terrestrials (June-Sep)"],
    quickTip: "Sipsey Fork in north Alabama is a coldwater tailwater that holds stocked and holdover rainbows year-round, fish small nymphs in the canyon section for consistent results.",
    licenseUrl: "https://www.outdooralabama.com/fishing/freshwater-fishing/buy-fishing-license",
  },
  MS: {
    name: "Mississippi",
    abbr: "MS",
    region: "southeast",
    topRivers: ["Natchez Trace streams", "Pearl River", "Noxubee River", "Big Black River", "Pascagoula River"],
    targetSpecies: ["Largemouth Bass", "Spotted Bass", "Carp", "Striped Bass"],
    bestMonths: [3, 4, 5, 10, 11],
    hatches: ["Caddis (Mar-May)", "Poppers for bass (Apr-Oct)", "Hoppers (July-Sep)", "Midges (Dec-Feb)"],
    quickTip: "Mississippi's clear-water streams in the Natchez Trace corridor offer surprisingly good smallmouth and spotted bass fishing on streamers and deer-hair poppers.",
    licenseUrl: "https://www.mdwfp.com/wildlife-hunting/fishing-license/",
  },
  LA: {
    name: "Louisiana",
    abbr: "LA",
    region: "southeast",
    topRivers: ["Marsh flats (Lafitte area)", "Sabine River", "Red River", "Atchafalaya Basin", "Pearl River"],
    targetSpecies: ["Redfish", "Largemouth Bass", "Bowfin", "Carp"],
    bestMonths: [3, 4, 5, 10, 11],
    hatches: ["Shrimp/crab patterns (year-round)", "Poppers for bass (Apr-Oct)", "Crawfish patterns (Mar-June)", "Baitfish streamers (Sep-Nov)"],
    quickTip: "Louisiana's coastal marsh is one of America's top redfish destinations, sight-casting to tailing reds in shallow grass flats with crab or shrimp patterns is exceptional March through May.",
    licenseUrl: "https://www.wlf.louisiana.gov/page/fishing-licenses-and-fees",
  },
  AR: {
    name: "Arkansas",
    abbr: "AR",
    region: "southeast",
    topRivers: ["White River", "Norfork River", "Little Red River", "Mulberry River", "Buffalo National River"],
    targetSpecies: ["Brown Trout", "Rainbow Trout", "Smallmouth Bass", "Brook Trout"],
    bestMonths: [3, 4, 5, 10, 11, 12],
    hatches: ["Midges (Oct-Mar)", "Blue-Winged Olive (Mar-Apr)", "Caddis (Apr-May)", "Sulphur (May-June)"],
    quickTip: "The White River below Bull Shoals Dam produces world-record brown trout, large streamers and sculpin patterns fished deep in the dam's discharge pools target the biggest fish.",
    licenseUrl: "https://www.agfc.com/en/licensing/",
  },
  HI: {
    name: "Hawaii",
    abbr: "HI",
    region: "southeast",
    topRivers: ["Oahu saltwater flats", "Kaneohe Bay flats", "Maui coastal flats", "Kauai streams", "Hawaii Island coastal areas"],
    targetSpecies: ["Bonefish", "Peacock Bass", "Bluegill", "Tilapia"],
    bestMonths: [4, 5, 6, 7, 8, 9, 10],
    hatches: ["Shrimp patterns (year-round)", "Crab patterns (year-round)", "Poppers for peacock bass (May-Oct)", "Small nymphs for stream fish (year-round)"],
    quickTip: "Oahu's Kaneohe Bay flats hold bonefish year-round, wade carefully on the sand and coral and present shrimp patterns ahead of tailing fish for Hawaii's unique saltwater fly fishing.",
    licenseUrl: "https://dlnr.hawaii.gov/dar/fishing/sport-fishing-license/",
  },
};

export function getStateInfo(abbr: string): StateInfo | undefined {
  return stateData[abbr.toUpperCase()];
}

export function stateToRegion(abbr: string): string {
  return stateData[abbr.toUpperCase()]?.region ?? "great_plains";
}
