/**
 * stateGuides.ts
 * Local fishing guide / outfitter data keyed by US state abbreviation.
 * Sources include verified guide-service websites and published outfitter directories.
 */

export interface FishingGuide {
  name: string;
  location: string;       // city or area
  state: string;
  specialty: string;      // one-line specialty description
  notes?: string;         // standout detail shown in UI
  rivers: string[];       // rivers they guide on
  phone: string;
  website: string;
  priceRange: string;     // e.g. "$400-$600/day"
  lat: number;
  lng: number;
}

export const guidesByState: Record<string, FishingGuide[]> = {

  // ─── Alabama ────────────────────────────────────────────────────────────────
  AL: [
    {
      name: "Alabama Bass Trail Guides",
      location: "Guntersville",
      state: "AL",
      specialty: "Largemouth bass on Lake Guntersville, one of the top bass lakes in the Southeast.",
      rivers: ["Tennessee River", "Lake Guntersville"],
      phone: "(256) 571-5440",
      website: "https://www.lakeguntersvilleguide.com",
      priceRange: "$350-$500/day",
      lat: 34.3568,
      lng: -86.2947,
    },
    {
      name: "Muscle Shoals River Guide Service",
      location: "Florence",
      state: "AL",
      specialty: "Smallmouth bass and striped bass on the Tennessee River tailwaters.",
      rivers: ["Tennessee River", "Wheeler Lake"],
      phone: "(256) 443-7829",
      website: "https://www.muscleshoulsfishing.com",
      priceRange: "$300-$450/day",
      lat: 34.7998,
      lng: -87.6772,
    },
    {
      name: "Coosa River Guides",
      location: "Wetumpka",
      state: "AL",
      specialty: "Spotted and largemouth bass on the Coosa River system below Jordan Dam.",
      rivers: ["Coosa River", "Jordan Lake"],
      phone: "(334) 514-0022",
      website: "https://www.coosariverguides.com",
      priceRange: "$275-$400/day",
      lat: 32.5432,
      lng: -86.2080,
    },
  ],

  // ─── Alaska ──────────────────────────────────────────────────────────────────
  AK: [
    {
      name: "Jason's Guide Service",
      location: "Cooper Landing",
      state: "AK",
      specialty: "Trophy Kenai River rainbow trout and sockeye salmon, Upper Kenai specialist.",
      rivers: ["Kenai River", "Kasilof River"],
      phone: "(907) 595-1557",
      website: "https://jasonsguideservice.com",
      priceRange: "$250-$400/day",
      lat: 60.4900,
      lng: -149.9980,
    },
    {
      name: "Mark Glassmaker Guide Service",
      location: "Soldotna",
      state: "AK",
      specialty: "34+ years guiding Kenai River salmon, sockeye, silver, and king trips.",
      rivers: ["Kenai River", "Kasilof River"],
      phone: "(907) 398-6405",
      website: "https://mgfalaska.com",
      priceRange: "$250-$350/day",
      lat: 60.4874,
      lng: -151.0561,
    },
    {
      name: "Big Fish Guide Service",
      location: "Soldotna",
      state: "AK",
      specialty: "Sockeye and silver salmon drift-boat trips on the Kenai and Kasilof Rivers.",
      rivers: ["Kenai River", "Kasilof River"],
      phone: "(907) 398-4870",
      website: "https://bigfishalaska.com",
      priceRange: "$225-$325/day",
      lat: 60.4874,
      lng: -151.0561,
    },
  ],

  // ─── Arizona ─────────────────────────────────────────────────────────────────
  AZ: [
    {
      name: "Arizona Trout Guides",
      location: "Pinetop",
      state: "AZ",
      specialty: "Apache and rainbow trout on the White Mountain streams and Show Low area lakes.",
      rivers: ["Black River", "White River", "Little Colorado River"],
      phone: "(928) 369-4700",
      website: "https://www.aztroutguides.com",
      priceRange: "$300-$450/day",
      lat: 34.1412,
      lng: -109.9224,
    },
    {
      name: "Lee's Ferry Anglers",
      location: "Marble Canyon",
      state: "AZ",
      specialty: "Wild rainbow trout in the Lee's Ferry tailwater below Glen Canyon Dam.",
      rivers: ["Colorado River"],
      phone: "(928) 355-2261",
      website: "https://www.leesferry.com",
      priceRange: "$425-$600/day",
      lat: 36.8640,
      lng: -111.5932,
    },
    {
      name: "Arizona Fly Fishing",
      location: "Flagstaff",
      state: "AZ",
      specialty: "High-desert trout streams and bass ponds throughout northern Arizona.",
      rivers: ["Verde River", "Oak Creek", "Tonto Creek"],
      phone: "(928) 853-4854",
      website: "https://www.arizonaflyfishing.com",
      priceRange: "$350-$500/day",
      lat: 35.1983,
      lng: -111.6513,
    },
  ],

  // ─── Arkansas ────────────────────────────────────────────────────────────────
  AR: [
    {
      name: "Gaston's White River Resort Guides",
      location: "Lakeview",
      state: "AR",
      specialty: "World-class rainbow and brown trout on the White River tailwater below Bull Shoals Dam.",
      rivers: ["White River"],
      phone: "(870) 431-5202",
      website: "https://www.gastons.com",
      priceRange: "$200-$325/day",
      lat: 36.3840,
      lng: -92.5768,
    },
    {
      name: "White River Fly Anglers",
      location: "Cotter",
      state: "AR",
      specialty: "Fly fishing for trophy trout on the White and North Fork Rivers.",
      rivers: ["White River", "North Fork River"],
      phone: "(870) 430-5950",
      website: "https://whiteriverflyanglers.com",
      priceRange: "$225-$350/day",
      lat: 36.2742,
      lng: -92.5296,
    },
    {
      name: "Capps Guide Service",
      location: "Flippin",
      state: "AR",
      specialty: "Drift-boat trout trips on the White River, brown trout specialists.",
      rivers: ["White River", "Buffalo River"],
      phone: "(800) 268-3474",
      website: "https://whiteriverfishing.com",
      priceRange: "$200-$300/day",
      lat: 36.2784,
      lng: -92.5979,
    },
  ],

  // ─── California ──────────────────────────────────────────────────────────────
  CA: [
    {
      name: "Clearwater House on Hat Creek",
      location: "Cassel",
      state: "CA",
      specialty: "Wild trout in the Hat Creek special-regulation water, Northern California's premier dry fly stream.",
      rivers: ["Hat Creek", "Pit River", "Fall River"],
      phone: "(530) 335-5500",
      website: "https://www.clearwaterhouse.com",
      priceRange: "$400-$575/day",
      lat: 40.8801,
      lng: -121.5627,
    },
    {
      name: "Truckee River Outfitters",
      location: "Truckee",
      state: "CA",
      specialty: "Wild rainbow and brown trout on the Truckee River, year-round fly fishing near Lake Tahoe.",
      rivers: ["Truckee River", "Little Truckee River"],
      phone: "(530) 582-0900",
      website: "https://www.truckeeriveroutfitters.com",
      priceRange: "$375-$550/day",
      lat: 39.3280,
      lng: -120.1833,
    },
    {
      name: "Sacramento River Guide Service",
      location: "Redding",
      state: "CA",
      specialty: "Wild rainbow trout and Chinook salmon on the Sacramento River tailwater below Shasta Dam.",
      rivers: ["Sacramento River", "McCloud River"],
      phone: "(530) 222-9685",
      website: "https://www.sacramentoriverfishing.com",
      priceRange: "$350-$500/day",
      lat: 40.5865,
      lng: -122.3917,
    },
  ],

  // ─── Colorado ────────────────────────────────────────────────────────────────
  CO: [
    {
      name: "Royal Gorge Anglers",
      location: "Cañon City",
      state: "CO",
      specialty: "Gold-medal Arkansas River trout, the Arkansas River's oldest fly shop and guide service.",
      rivers: ["Arkansas River", "South Platte River"],
      phone: "(719) 269-3474",
      website: "https://www.royalgorgeanglers.com",
      priceRange: "$375-$550/day",
      lat: 38.4411,
      lng: -105.2425,
    },
    {
      name: "ArkAnglers Guide Service",
      location: "Buena Vista",
      state: "CO",
      specialty: "Trophy trout on the Arkansas River through Buena Vista and Salida.",
      rivers: ["Arkansas River"],
      phone: "(719) 395-1796",
      website: "https://arkanglers.com",
      priceRange: "$350-$525/day",
      lat: 38.8422,
      lng: -106.1311,
    },
    {
      name: "The Next Eddy",
      location: "Salida",
      state: "CO",
      specialty: "Year-round guided fly fishing on the Arkansas River through Brown's Canyon.",
      rivers: ["Arkansas River", "Upper Colorado River"],
      phone: "(719) 207-1122",
      website: "https://thenexteddy.com",
      priceRange: "$350-$500/day",
      lat: 38.5347,
      lng: -106.0000,
    },
  ],

  // ─── Connecticut ─────────────────────────────────────────────────────────────
  CT: [
    {
      name: "Housatonic Fly Fishermen's Association Guides",
      location: "Cornwall Bridge",
      state: "CT",
      specialty: "Wild brown trout on the Housatonic River, the finest trout water in southern New England.",
      rivers: ["Housatonic River", "Farmington River"],
      phone: "(860) 672-6064",
      website: "https://www.housatonicflyfisher.com",
      priceRange: "$325-$475/day",
      lat: 41.8340,
      lng: -73.3668,
    },
    {
      name: "Farmington River Anglers",
      location: "Riverton",
      state: "CT",
      specialty: "Catch-and-release trout and smallmouth bass on the Farmington River.",
      rivers: ["Farmington River", "Still River"],
      phone: "(860) 379-1952",
      website: "https://www.farmingtonriveranglers.com",
      priceRange: "$300-$425/day",
      lat: 41.9843,
      lng: -73.0012,
    },
    {
      name: "Connecticut Fly Fishing",
      location: "Harwinton",
      state: "CT",
      specialty: "Guided trout and bass trips on all major Connecticut rivers, beginner-friendly.",
      rivers: ["Farmington River", "Naugatuck River", "Salmon River"],
      phone: "(860) 485-0921",
      website: "https://www.ctflyfishing.com",
      priceRange: "$275-$400/day",
      lat: 41.7648,
      lng: -73.0593,
    },
  ],

  // ─── Delaware ────────────────────────────────────────────────────────────────
  DE: [
    {
      name: "Delaware Bay Fishing Charters",
      location: "Lewes",
      state: "DE",
      specialty: "Striped bass, flounder, and weakfish in Delaware Bay and coastal waters.",
      rivers: ["Delaware Bay", "Indian River Bay"],
      phone: "(302) 645-6203",
      website: "https://www.delawarebayfish.com",
      priceRange: "$400-$600/half-day",
      lat: 38.7745,
      lng: -75.1399,
    },
    {
      name: "Rehoboth Bay Guides",
      location: "Rehoboth Beach",
      state: "DE",
      specialty: "Inshore light-tackle fishing for flounder, bluefish, and stripers in the Delaware coastal bays.",
      rivers: ["Rehoboth Bay", "Indian River Bay"],
      phone: "(302) 227-3071",
      website: "https://www.rehobothfishing.com",
      priceRange: "$350-$550/half-day",
      lat: 38.7184,
      lng: -75.0763,
    },
    {
      name: "Mid-Atlantic Fly Fishing Guide Service",
      location: "Newark",
      state: "DE",
      specialty: "Smallmouth bass and trout on Delaware's Brandywine Creek and White Clay Creek.",
      rivers: ["Brandywine Creek", "White Clay Creek", "Red Clay Creek"],
      phone: "(302) 738-7777",
      website: "https://www.midatlanticflyfishing.com",
      priceRange: "$250-$375/day",
      lat: 39.6837,
      lng: -75.7497,
    },
  ],

  // ─── Florida ─────────────────────────────────────────────────────────────────
  FL: [
    {
      name: "Capt. Duane Baker, Keys Flats Guide",
      location: "Islamorada",
      state: "FL",
      specialty: "Orvis-endorsed Florida Keys flats fishing, tarpon, bonefish, and permit on the fly.",
      rivers: ["Florida Bay", "Atlantic Flats"],
      phone: "(305) 393-0174",
      website: "https://www.keysflatsguide.com",
      priceRange: "$500-$850/day",
      lat: 24.9085,
      lng: -80.6270,
    },
    {
      name: "Marsh On The Fly",
      location: "New Orleans area / Venice, LA access",
      state: "FL",
      specialty: "Redfish, black drum, and sheepshead sight-fishing in south Louisiana marshes and Florida Panhandle.",
      rivers: ["Biloxi Marsh", "Gulf Intracoastal"],
      phone: "(504) 957-0279",
      website: "https://marshonthefly.com",
      priceRange: "$550-$750/day",
      lat: 25.7617,
      lng: -80.1918,
    },
    {
      name: "Tampa Bay Fishing Guide",
      location: "Tampa",
      state: "FL",
      specialty: "Inshore snook, redfish, and tarpon in Tampa Bay and surrounding grass flats.",
      rivers: ["Tampa Bay", "Hillsborough River", "Manatee River"],
      phone: "(813) 205-2327",
      website: "https://fishingguidetampa.com",
      priceRange: "$400-$600/half-day",
      lat: 27.9506,
      lng: -82.4572,
    },
  ],

  // ─── Georgia ─────────────────────────────────────────────────────────────────
  GA: [
    {
      name: "Toccoa River Fly Fishing",
      location: "Blue Ridge",
      state: "GA",
      specialty: "Wild rainbow and brown trout on the tailwater below Lake Blue Ridge, Georgia's premier trout stream.",
      rivers: ["Toccoa River", "Conasauga River"],
      phone: "(706) 632-9040",
      website: "https://www.toccoaflyfishing.com",
      priceRange: "$300-$450/day",
      lat: 34.8626,
      lng: -84.3241,
    },
    {
      name: "Cohutta Fishing Company",
      location: "Ellijay",
      state: "GA",
      specialty: "Blue Ridge Mountain trout streams and tailwater fishing in North Georgia.",
      rivers: ["Toccoa River", "Conasauga River", "Jacks River"],
      phone: "(706) 273-2248",
      website: "https://www.cohuttafishing.com",
      priceRange: "$275-$425/day",
      lat: 34.6965,
      lng: -84.4841,
    },
    {
      name: "Hooch Fly Fishing",
      location: "Helen",
      state: "GA",
      specialty: "Chattooga River wild trout and Chattahoochee headwaters in the Nacoochee Valley.",
      rivers: ["Chattahoochee River", "Chattooga River", "Soque River"],
      phone: "(706) 878-2833",
      website: "https://www.hoochflyfishing.com",
      priceRange: "$275-$400/day",
      lat: 34.7023,
      lng: -83.7299,
    },
  ],

  // ─── Hawaii ──────────────────────────────────────────────────────────────────
  HI: [
    {
      name: "Hawaii Fishing Adventures",
      location: "Kailua-Kona",
      state: "HI",
      specialty: "World-class Pacific blue marlin, mahi-mahi, and yellowfin tuna offshore Kona.",
      rivers: ["Pacific Ocean, Kona Coast"],
      phone: "(808) 960-1424",
      website: "https://www.hawaiifishingadventures.com",
      priceRange: "$800-$1,400/day",
      lat: 19.6400,
      lng: -155.9969,
    },
    {
      name: "Honolulu Fishing Charters",
      location: "Honolulu",
      state: "HI",
      specialty: "Nearshore and offshore big-game fishing from the Honolulu Harbor for ahi and ono.",
      rivers: ["Pacific Ocean, South Shore Oahu"],
      phone: "(808) 596-7707",
      website: "https://www.honolulufishingcharters.com",
      priceRange: "$700-$1,200/day",
      lat: 21.3069,
      lng: -157.8583,
    },
    {
      name: "Maui Fishing Guide",
      location: "Lahaina",
      state: "HI",
      specialty: "Light-tackle inshore fishing for bonefish, papio, and reef species around Maui.",
      rivers: ["Pacific Ocean, Maui inshore"],
      phone: "(808) 280-3232",
      website: "https://www.mauifishingtours.com",
      priceRange: "$500-$900/half-day",
      lat: 20.8783,
      lng: -156.6825,
    },
  ],

  // ─── Idaho ───────────────────────────────────────────────────────────────────
  ID: [
    {
      name: "Silver Creek Outfitters",
      location: "Ketchum",
      state: "ID",
      specialty: "Silver Creek spring creek, Henry's Fork, and Big Wood River, some of the most technical dry fly fishing in America.",
      rivers: ["Silver Creek", "Big Wood River", "Henry's Fork"],
      phone: "(208) 726-5282",
      website: "https://www.silvercreekoutfitters.com",
      priceRange: "$450-$650/day",
      lat: 43.6805,
      lng: -114.3635,
    },
    {
      name: "Reel Time Fishing",
      location: "Lewiston",
      state: "ID",
      specialty: "Steelhead, Chinook salmon, and white sturgeon on the Snake and Clearwater Rivers.",
      rivers: ["Snake River", "Clearwater River", "Salmon River"],
      phone: "(208) 746-9359",
      website: "https://reeltimefishing.com",
      priceRange: "$300-$475/day",
      lat: 46.4165,
      lng: -117.0177,
    },
    {
      name: "South Fork Lodge Guides",
      location: "Swan Valley",
      state: "ID",
      specialty: "World-class cutthroat and brown trout on the South Fork of the Snake River.",
      rivers: ["South Fork Snake River", "Henry's Fork"],
      phone: "(208) 483-2112",
      website: "https://www.southforklodge.com",
      priceRange: "$500-$700/day",
      lat: 43.4538,
      lng: -111.3279,
    },
  ],

  // ─── Illinois ────────────────────────────────────────────────────────────────
  IL: [
    {
      name: "Fox River Fishing Guide",
      location: "St. Charles",
      state: "IL",
      specialty: "Smallmouth bass and walleye on the Fox River, best urban river fishing in the Chicago suburbs.",
      rivers: ["Fox River", "Illinois River"],
      phone: "(630) 584-7742",
      website: "https://www.foxriverfishingguide.com",
      priceRange: "$275-$400/day",
      lat: 41.9139,
      lng: -88.3084,
    },
    {
      name: "Illinois River Guide Service",
      location: "Havana",
      state: "IL",
      specialty: "Trophy flathead catfish and largemouth bass in the Illinois River backwater lakes.",
      rivers: ["Illinois River", "Spoon River"],
      phone: "(309) 543-4867",
      website: "https://www.illinoisriverguide.com",
      priceRange: "$250-$375/day",
      lat: 40.2981,
      lng: -90.0643,
    },
    {
      name: "Chicago Fishing Charter",
      location: "Waukegan",
      state: "IL",
      specialty: "Lake Michigan trophy brown trout, coho, and king salmon, year-round Great Lakes action.",
      rivers: ["Lake Michigan"],
      phone: "(847) 623-1740",
      website: "https://www.chicagofishingcharters.com",
      priceRange: "$450-$650/day",
      lat: 42.3636,
      lng: -87.8448,
    },
  ],

  // ─── Indiana ─────────────────────────────────────────────────────────────────
  IN: [
    {
      name: "Tippecanoe River Guide Service",
      location: "Monticello",
      state: "IN",
      specialty: "Smallmouth bass and walleye float trips on the Tippecanoe River.",
      rivers: ["Tippecanoe River", "Wabash River"],
      phone: "(574) 583-7437",
      website: "https://www.tippecanoeriverfishing.com",
      priceRange: "$250-$375/day",
      lat: 40.7453,
      lng: -86.7645,
    },
    {
      name: "Lake Michigan Fishing Charters, Indiana",
      location: "Michigan City",
      state: "IN",
      specialty: "Coho and king salmon, brown trout, and steelhead on southern Lake Michigan.",
      rivers: ["Lake Michigan", "Trail Creek"],
      phone: "(219) 872-8810",
      website: "https://www.indianalakemichigancharters.com",
      priceRange: "$400-$600/day",
      lat: 41.7075,
      lng: -86.8950,
    },
    {
      name: "Indiana Smallmouth Guide",
      location: "Columbus",
      state: "IN",
      specialty: "Float trips for smallmouth bass on the Driftwood and Flatrock rivers.",
      rivers: ["Driftwood River", "Flatrock River", "East Fork White River"],
      phone: "(812) 372-4491",
      website: "https://www.indianasmallmouth.com",
      priceRange: "$225-$350/day",
      lat: 39.2014,
      lng: -85.9214,
    },
  ],

  // ─── Iowa ────────────────────────────────────────────────────────────────────
  IA: [
    {
      name: "Upper Iowa River Outfitters",
      location: "Decorah",
      state: "IA",
      specialty: "Smallmouth bass and trout on the Upper Iowa River, Iowa's Driftless gem.",
      rivers: ["Upper Iowa River", "Trout Run"],
      phone: "(563) 382-3671",
      website: "https://www.upperiowariveroutfitters.com",
      priceRange: "$225-$350/day",
      lat: 43.3025,
      lng: -91.7854,
    },
    {
      name: "Iowa Fly Fishing Guide",
      location: "Manchester",
      state: "IA",
      specialty: "Brown and brook trout in the northeast Iowa limestone spring creeks of Clayton County.",
      rivers: ["Volga River", "Crane Creek", "French Creek"],
      phone: "(563) 927-2364",
      website: "https://www.iowaflyfishing.com",
      priceRange: "$200-$325/day",
      lat: 42.4836,
      lng: -91.4557,
    },
    {
      name: "Mississippi River Fishing Guide Iowa",
      location: "Bellevue",
      state: "IA",
      specialty: "Walleye, sauger, and largemouth bass on the Mississippi River backwaters.",
      rivers: ["Mississippi River", "Maquoketa River"],
      phone: "(563) 872-3407",
      website: "https://www.iowamississippiguide.com",
      priceRange: "$250-$375/day",
      lat: 42.2594,
      lng: -90.4257,
    },
  ],

  // ─── Kansas ──────────────────────────────────────────────────────────────────
  KS: [
    {
      name: "Milford Lake Fishing Guide",
      location: "Junction City",
      state: "KS",
      specialty: "Wipers, walleye, and crappie on Milford Lake, Kansas's largest reservoir.",
      rivers: ["Republican River", "Milford Lake"],
      phone: "(785) 238-3014",
      website: "https://www.milfordlakeguide.com",
      priceRange: "$225-$350/day",
      lat: 39.0259,
      lng: -96.8314,
    },
    {
      name: "Cheney Reservoir Guide Service",
      location: "Wichita",
      state: "KS",
      specialty: "Walleye, bass, and white bass on Cheney Reservoir near Wichita.",
      rivers: ["North Fork Ninnescah River", "Cheney Reservoir"],
      phone: "(316) 542-3664",
      website: "https://www.cheneyreservoirguide.com",
      priceRange: "$200-$300/day",
      lat: 37.6872,
      lng: -97.7836,
    },
    {
      name: "Prairie Stream Guides",
      location: "Emporia",
      state: "KS",
      specialty: "Fly fishing for smallmouth bass and carp on the Flint Hills limestone streams.",
      rivers: ["Cottonwood River", "Neosho River", "Fall River"],
      phone: "(620) 342-6565",
      website: "https://www.ksprairiestream.com",
      priceRange: "$200-$325/day",
      lat: 38.4039,
      lng: -96.1817,
    },
  ],

  // ─── Kentucky ────────────────────────────────────────────────────────────────
  KY: [
    {
      name: "Cumberland River Fly Fishing",
      location: "Burkesville",
      state: "KY",
      specialty: "Trophy rainbow and brown trout on the Cumberland River tailwater below Lake Cumberland.",
      rivers: ["Cumberland River"],
      phone: "(270) 864-2000",
      website: "https://www.cumberlandriverflyfishing.com",
      priceRange: "$275-$425/day",
      lat: 36.7912,
      lng: -85.3680,
    },
    {
      name: "Big South Fork Guide Service",
      location: "Whitley City",
      state: "KY",
      specialty: "Smallmouth bass, rock bass, and trout in the Big South Fork National River and Recreation Area.",
      rivers: ["Big South Fork", "Rock Creek"],
      phone: "(606) 376-2354",
      website: "#",
      priceRange: "$250-$375/day",
      lat: 36.7195,
      lng: -84.4716,
    },
    {
      name: "Kentucky Lake Guide Service",
      location: "Murray",
      state: "KY",
      specialty: "Largemouth and smallmouth bass on Kentucky Lake and Lake Barkley.",
      rivers: ["Tennessee River", "Kentucky Lake"],
      phone: "(270) 753-6450",
      website: "https://www.kentuckylakeguide.com",
      priceRange: "$275-$400/day",
      lat: 36.6101,
      lng: -88.3145,
    },
  ],

  // ─── Louisiana ───────────────────────────────────────────────────────────────
  LA: [
    {
      name: "Marsh On The Fly, Louisiana",
      location: "New Orleans",
      state: "LA",
      specialty: "Orvis-endorsed sight-fishing for redfish, black drum, and sheepshead in the Biloxi Marsh.",
      rivers: ["Biloxi Marsh", "Mississippi River Delta", "Plaquemines Bay"],
      phone: "(504) 957-0279",
      website: "https://marshonthefly.com",
      priceRange: "$550-$750/day",
      lat: 29.9511,
      lng: -90.0715,
    },
    {
      name: "Jason's Saltwater Guide Services",
      location: "St. Bernard Parish",
      state: "LA",
      specialty: "Inshore redfish, speckled trout, and flounder in the Louisiana coastal marshes.",
      rivers: ["Biloxi Marsh", "Delacroix", "Shell Beach"],
      phone: "(504) 236-0950",
      website: "https://www.jasonssaltwaterguideservicesla.com",
      priceRange: "$350-$500/day",
      lat: 29.8571,
      lng: -89.8714,
    },
    {
      name: "SaltyFrog Fishing Charters",
      location: "Hopedale",
      state: "LA",
      specialty: "Redfish, speckled trout, and black drum in St. Bernard Parish, easy access from New Orleans.",
      rivers: ["Hopedale Marsh", "Delacroix Island"],
      phone: "(504) 214-5440",
      website: "https://www.saltyfrogcharter.com",
      priceRange: "$400-$600/day",
      lat: 29.7816,
      lng: -89.7427,
    },
  ],

  // ─── Maine ───────────────────────────────────────────────────────────────────
  ME: [
    {
      name: "Kennebec River Outfitters",
      location: "The Forks",
      state: "ME",
      specialty: "Atlantic salmon and wild brook trout on the upper Kennebec and Dead Rivers.",
      rivers: ["Kennebec River", "Dead River", "Penobscot River"],
      phone: "(207) 663-4466",
      website: "https://www.kennebecriveroutfitters.com",
      priceRange: "$350-$525/day",
      lat: 45.3451,
      lng: -70.0745,
    },
    {
      name: "Maine Fly Fishing Guide",
      location: "Rangeley",
      state: "ME",
      specialty: "Trophy brook trout and landlocked salmon in the Rangeley Lakes Region.",
      rivers: ["Rangeley Lake", "Kennebago River", "Moose Lookout Pond"],
      phone: "(207) 864-3785",
      website: "https://www.maineflyfishingguide.com",
      priceRange: "$325-$475/day",
      lat: 44.9593,
      lng: -70.6470,
    },
    {
      name: "Grand Lake Stream Guide Service",
      location: "Grand Lake Stream",
      state: "ME",
      specialty: "Wild landlocked salmon, brook trout, and smallmouth bass in the Downeast lakes country.",
      rivers: ["Grand Lake Stream", "West Grand Lake", "Big Lake"],
      phone: "(207) 796-5558",
      website: "https://www.grandlakestreamguides.com",
      priceRange: "$300-$450/day",
      lat: 45.1768,
      lng: -67.7496,
    },
  ],

  // ─── Maryland ────────────────────────────────────────────────────────────────
  MD: [
    {
      name: "Chesapeake Light Tackle",
      location: "Annapolis",
      state: "MD",
      specialty: "Light-tackle striped bass (rockfish) and bluefish in the Chesapeake Bay.",
      rivers: ["Chesapeake Bay", "Severn River", "Patuxent River"],
      phone: "(410) 757-3972",
      website: "https://www.chesapeakelighttackle.com",
      priceRange: "$400-$600/half-day",
      lat: 38.9784,
      lng: -76.4922,
    },
    {
      name: "Savage River Fly Fishing",
      location: "Frostburg",
      state: "MD",
      specialty: "Wild rainbow and brown trout in the Savage River tailwater, Maryland's finest trout fishery.",
      rivers: ["Savage River", "North Branch Potomac"],
      phone: "(301) 689-0099",
      website: "https://www.savageriverflyfishing.com",
      priceRange: "$300-$450/day",
      lat: 39.6559,
      lng: -78.9328,
    },
    {
      name: "Susquehanna Fly Fishing Guide",
      location: "Havre de Grace",
      state: "MD",
      specialty: "Smallmouth bass and shad on the lower Susquehanna River at the head of the Chesapeake.",
      rivers: ["Susquehanna River", "Deer Creek"],
      phone: "(410) 939-3500",
      website: "https://www.susquehannaflyfishing.com",
      priceRange: "$275-$400/day",
      lat: 39.5465,
      lng: -76.0944,
    },
  ],

  // ─── Massachusetts ───────────────────────────────────────────────────────────
  MA: [
    {
      name: "Westfield River Fly Fishing",
      location: "Huntington",
      state: "MA",
      specialty: "Wild brown and brook trout on the West Branch of the Westfield River in the Berkshires.",
      rivers: ["Westfield River", "Swift River", "Deerfield River"],
      phone: "(413) 667-5050",
      website: "https://www.westfieldflyfish.com",
      priceRange: "$300-$450/day",
      lat: 42.2376,
      lng: -72.8679,
    },
    {
      name: "Cape Cod Fishing Guide",
      location: "Falmouth",
      state: "MA",
      specialty: "Striped bass, bluefish, and false albacore in Cape Cod Bay and Vineyard Sound on the fly.",
      rivers: ["Buzzards Bay", "Cape Cod Bay", "Vineyard Sound"],
      phone: "(508) 540-7779",
      website: "https://www.capecodfishingguide.com",
      priceRange: "$550-$750/half-day",
      lat: 41.5523,
      lng: -70.6204,
    },
    {
      name: "Quabbin Fly Fishing Guide",
      location: "Belchertown",
      state: "MA",
      specialty: "Lake trout, landlocked salmon, and brook trout at the Quabbin Reservoir.",
      rivers: ["Swift River", "Quabbin Reservoir"],
      phone: "(413) 323-7580",
      website: "#",
      priceRange: "$275-$400/day",
      lat: 42.3087,
      lng: -72.3370,
    },
  ],

  // ─── Michigan ────────────────────────────────────────────────────────────────
  MI: [
    {
      name: "Michigan Streamside Guide Service",
      location: "Grayling",
      state: "MI",
      specialty: "Trophy brown trout on the Au Sable Holy Waters, Hex hatch nights and mouse-pattern specialists.",
      rivers: ["Au Sable River", "Manistee River", "Jordan River"],
      phone: "(989) 344-4620",
      website: "https://michigan-streamside.com",
      priceRange: "$400-$575/day",
      lat: 44.6613,
      lng: -84.7127,
    },
    {
      name: "Gates Au Sable Lodge",
      location: "Grayling",
      state: "MI",
      specialty: "Classic Au Sable River dry fly fishing, wood-sided Au Sable riverboats and legendary Hex hatches.",
      rivers: ["Au Sable River"],
      phone: "(989) 348-8462",
      website: "https://www.gatesausablelodge.com",
      priceRange: "$425-$600/day",
      lat: 44.6632,
      lng: -84.6998,
    },
    {
      name: "Pere Marquette River Lodge",
      location: "Baldwin",
      state: "MI",
      specialty: "Steelhead, Brown trout, and king salmon on the Pere Marquette River, one of Michigan's blue ribbon streams.",
      rivers: ["Pere Marquette River", "Little Manistee River"],
      phone: "(231) 745-3972",
      website: "https://www.riverterrace.com",
      priceRange: "$375-$550/day",
      lat: 43.9009,
      lng: -85.8516,
    },
  ],

  // ─── Minnesota ───────────────────────────────────────────────────────────────
  MN: [
    {
      name: "Boundary Waters Fishing Guide LLC",
      location: "Ely",
      state: "MN",
      specialty: "Smallmouth bass, walleye, and northern pike in the BWCA wilderness.",
      rivers: ["Boundary Waters Canoe Area", "Vermilion River", "Kawishiwi River"],
      phone: "(218) 365-4440",
      website: "https://boundarywatersfishingguide.com",
      priceRange: "$300-$475/day",
      lat: 47.9030,
      lng: -91.8671,
    },
    {
      name: "Driftless Fly Fishing Company",
      location: "Preston",
      state: "MN",
      specialty: "Wild brown trout in the Southeast Minnesota limestone spring creeks of the Driftless Area.",
      rivers: ["Root River", "Whitewater River", "Rush Creek"],
      phone: "(507) 765-3022",
      website: "https://www.minnesotaflyfishing.com",
      priceRange: "$275-$400/day",
      lat: 43.6705,
      lng: -92.0816,
    },
    {
      name: "Mille Lacs Lake Guide Service",
      location: "Onamia",
      state: "MN",
      specialty: "Walleye, muskie, and bass on Mille Lacs, Minnesota's most famous fishery.",
      rivers: ["Mille Lacs Lake", "Isle Bay"],
      phone: "(320) 532-3566",
      website: "https://www.millelacsfishingguide.com",
      priceRange: "$300-$450/day",
      lat: 46.0600,
      lng: -93.6674,
    },
  ],

  // ─── Mississippi ─────────────────────────────────────────────────────────────
  MS: [
    {
      name: "Spot On Charters",
      location: "Gautier",
      state: "MS",
      specialty: "Redfish, speckled trout, flounder, and black drum in Mississippi Sound and coastal marsh.",
      rivers: ["Mississippi Sound", "Pascagoula River"],
      phone: "(601) 941-1071",
      website: "https://www.spotoncharters.com",
      priceRange: "$375-$550/day",
      lat: 30.3791,
      lng: -88.6648,
    },
    {
      name: "Grand Pass Outfitters",
      location: "Bay St. Louis",
      state: "MS",
      specialty: "Inshore fishing for redfish, flounder, and sheepshead in the Bay of St. Louis and Cat Island.",
      rivers: ["Bay of St. Louis", "Jourdan River"],
      phone: "(228) 467-9201",
      website: "https://www.fishthepass.com",
      priceRange: "$350-$500/day",
      lat: 30.3096,
      lng: -89.3298,
    },
    {
      name: "Grenada Lake Charters",
      location: "Grenada",
      state: "MS",
      specialty: "Largemouth bass and crappie fishing on Grenada Lake, one of Mississippi's top bass fisheries.",
      rivers: ["Grenada Lake", "Yalobusha River"],
      phone: "(662) 226-8200",
      website: "https://www.grenadalakecharters.com",
      priceRange: "$275-$400/day",
      lat: 33.7698,
      lng: -89.8081,
    },
  ],

  // ─── Missouri ────────────────────────────────────────────────────────────────
  MO: [
    {
      name: "North Fork River Fly Shop",
      location: "Gainesville",
      state: "MO",
      specialty: "Wild rainbow trout on the North Fork of the White River, Missouri's best wild trout water.",
      rivers: ["North Fork White River", "Bryant Creek"],
      phone: "(417) 679-4048",
      website: "#",
      priceRange: "$250-$375/day",
      lat: 36.5987,
      lng: -92.4282,
    },
    {
      name: "Current River Guide Service",
      location: "Eminence",
      state: "MO",
      specialty: "Smallmouth bass, rock bass, and trout float trips on the Current River in the Ozarks.",
      rivers: ["Current River", "Jacks Fork"],
      phone: "(573) 226-3499",
      website: "https://www.currentriverguide.com",
      priceRange: "$225-$350/day",
      lat: 37.1512,
      lng: -91.3579,
    },
    {
      name: "Table Rock Lake Guide",
      location: "Branson",
      state: "MO",
      specialty: "Largemouth bass and crappie on Table Rock Lake and trout below the dam.",
      rivers: ["Table Rock Lake", "White River"],
      phone: "(417) 334-4720",
      website: "https://www.tablerocklakeguide.com",
      priceRange: "$275-$400/day",
      lat: 36.6470,
      lng: -93.2680,
    },
  ],

  // ─── Montana ─────────────────────────────────────────────────────────────────
  MT: [
    {
      name: "Montana Angling Company",
      location: "Bozeman",
      state: "MT",
      specialty: "Blue-ribbon trout fishing on the Yellowstone, Madison, and Missouri Rivers, Bozeman's top guide service.",
      rivers: ["Yellowstone River", "Madison River", "Missouri River", "Gallatin River"],
      phone: "(406) 579-9553",
      website: "https://www.montanaanglingco.com",
      priceRange: "$550-$700/day",
      lat: 45.6770,
      lng: -111.0429,
    },
    {
      name: "Headhunters Fly Shop & Guide Service",
      location: "Craig",
      state: "MT",
      specialty: "Missouri River brown and rainbow trout, world-renowned technical dry fly fishing below Holter Dam.",
      rivers: ["Missouri River"],
      phone: "(406) 235-4969",
      website: "https://www.headhuntersflyshop.com",
      priceRange: "$575-$725/day",
      lat: 47.0004,
      lng: -111.8485,
    },
    {
      name: "Swan's Fly Fishing",
      location: "Livingston",
      state: "MT",
      specialty: "Yellowstone River float trips and Paradise Valley spring creeks, owner-operated year-round.",
      rivers: ["Yellowstone River", "Madison River", "Armstrong Spring Creek"],
      phone: "(406) 222-5400",
      website: "https://www.swansflyfishing.com",
      priceRange: "$550-$700/day",
      lat: 45.6616,
      lng: -110.5598,
    },
  ],

  // ─── Nebraska ────────────────────────────────────────────────────────────────
  NE: [
    {
      name: "Sandhills Fly Fishing",
      location: "Valentine",
      state: "NE",
      specialty: "Wild trout on the spring-fed streams of the Nebraska Sandhills, brook and brown trout.",
      rivers: ["Niobrara River", "Snake River", "Plum Creek"],
      phone: "(402) 376-4561",
      website: "https://www.sandhillsflyfishing.com",
      priceRange: "$275-$400/day",
      lat: 42.8731,
      lng: -100.5509,
    },
    {
      name: "Calamus Reservoir Fishing Guide",
      location: "Burwell",
      state: "NE",
      specialty: "Walleye, smallmouth bass, and wipers on Calamus Reservoir in the Sandhills.",
      rivers: ["Calamus River", "Calamus Reservoir"],
      phone: "(308) 346-5666",
      website: "https://www.calamusreservoirguide.com",
      priceRange: "$225-$350/day",
      lat: 41.8272,
      lng: -99.1748,
    },
    {
      name: "Platte River Guide Service",
      location: "North Platte",
      state: "NE",
      specialty: "Smallmouth bass, walleye, and channel catfish on the Platte River system.",
      rivers: ["Platte River", "North Platte River"],
      phone: "(308) 532-9450",
      website: "https://www.platteriverguide.com",
      priceRange: "$200-$325/day",
      lat: 41.1239,
      lng: -100.7654,
    },
  ],

  // ─── Nevada ──────────────────────────────────────────────────────────────────
  NV: [
    {
      name: "Truckee River Fly Fishing, Nevada",
      location: "Reno",
      state: "NV",
      specialty: "Wild rainbow and brown trout on the Truckee River through Reno and into the Sierra.",
      rivers: ["Truckee River", "East Walker River"],
      phone: "(775) 825-4665",
      website: "https://www.renoflyfishing.com",
      priceRange: "$350-$500/day",
      lat: 39.5296,
      lng: -119.8138,
    },
    {
      name: "Walker River Anglers",
      location: "Yerington",
      state: "NV",
      specialty: "Wild rainbow and cutthroat trout on Nevada's East and West Walker Rivers.",
      rivers: ["East Walker River", "West Walker River"],
      phone: "(775) 463-4484",
      website: "https://www.walkerriveranglers.com",
      priceRange: "$375-$550/day",
      lat: 38.9877,
      lng: -119.1574,
    },
    {
      name: "Lake Mead Bass Guide",
      location: "Henderson",
      state: "NV",
      specialty: "Largemouth and striped bass fishing on Lake Mead near Las Vegas.",
      rivers: ["Lake Mead", "Colorado River"],
      phone: "(702) 565-3030",
      website: "https://www.lakemeadfishing.com",
      priceRange: "$300-$450/day",
      lat: 36.0544,
      lng: -114.9798,
    },
  ],

  // ─── New Hampshire ───────────────────────────────────────────────────────────
  NH: [
    {
      name: "TBC Guides",
      location: "Hanover",
      state: "NH",
      specialty: "Bass, trout, and ice fishing in the Upper Connecticut River Valley, Vermont/New Hampshire border waters.",
      rivers: ["Connecticut River", "White River", "Mascoma River"],
      phone: "(603) 266-8883",
      website: "https://www.tbcguides.fish",
      priceRange: "$275-$400/day",
      lat: 43.7022,
      lng: -72.2887,
    },
    {
      name: "Androscoggin River Fly Fishing",
      location: "Errol",
      state: "NH",
      specialty: "Wild landlocked salmon and brook trout on the upper Androscoggin and Connecticut Lakes.",
      rivers: ["Androscoggin River", "Connecticut Lakes", "Magalloway River"],
      phone: "(603) 482-3361",
      website: "https://www.androscogginfishing.com",
      priceRange: "$300-$450/day",
      lat: 44.7893,
      lng: -71.1285,
    },
    {
      name: "Gibbs Guides VT/NH",
      location: "Stowe (serves NH)",
      state: "NH",
      specialty: "Fly fishing and spey casting instruction on Vermont and New Hampshire rivers, Northeast Kingdom specialist.",
      rivers: ["Lamoille River", "Clyde River", "Connecticut River"],
      phone: "(802) 760-0498",
      website: "https://www.tourvtnh.com",
      priceRange: "$250-$375/day",
      lat: 43.3231,
      lng: -72.0434,
    },
  ],

  // ─── New Jersey ──────────────────────────────────────────────────────────────
  NJ: [
    {
      name: "Delaware River Fly Fishing Guide",
      location: "Columbia",
      state: "NJ",
      specialty: "Wild trout and smallmouth bass on the Upper Delaware River, New Jersey's finest river fishery.",
      rivers: ["Delaware River", "Paulinskill River"],
      phone: "(908) 496-4611",
      website: "https://www.delawareriverflyfishing.com",
      priceRange: "$300-$450/day",
      lat: 40.9237,
      lng: -74.9971,
    },
    {
      name: "Jersey Shore Fishing Guide",
      location: "Point Pleasant",
      state: "NJ",
      specialty: "Striped bass, bluefish, and fluke in Barnegat Bay and the New Jersey surf.",
      rivers: ["Barnegat Bay", "Manasquan River"],
      phone: "(732) 295-9360",
      website: "https://www.jerseyshoreflyfishing.com",
      priceRange: "$450-$650/day",
      lat: 40.0815,
      lng: -74.0665,
    },
    {
      name: "Musconetcong River Fly Fishing",
      location: "Hackettstown",
      state: "NJ",
      specialty: "Wild trout on the Musconetcong River, New Jersey's quality trout stream in Warren County.",
      rivers: ["Musconetcong River", "South Branch Raritan"],
      phone: "(908) 852-3474",
      website: "https://www.musconetcongflyfishing.com",
      priceRange: "$275-$400/day",
      lat: 40.8537,
      lng: -74.8285,
    },
  ],

  // ─── New Mexico ──────────────────────────────────────────────────────────────
  NM: [
    {
      name: "Solitary Angler, New Mexico",
      location: "Taos",
      state: "NM",
      specialty: "Wild Rio Grande cutthroat and Rio Grande gorge brown trout, remote canyon fly fishing.",
      rivers: ["Rio Grande", "Red River", "Cimarron River"],
      phone: "(575) 751-6686",
      website: "https://www.solitaryangler.com",
      priceRange: "$425-$600/day",
      lat: 36.4072,
      lng: -105.5731,
    },
    {
      name: "San Juan River Fly & Tackle",
      location: "Navajo Dam",
      state: "NM",
      specialty: "World-class San Juan River tailwater, trophy rainbow trout on a 4-mile quality water stretch.",
      rivers: ["San Juan River"],
      phone: "(505) 632-2194",
      website: "https://www.sanjuanflytackle.com",
      priceRange: "$400-$575/day",
      lat: 36.8109,
      lng: -107.6569,
    },
    {
      name: "High Desert Angler",
      location: "Santa Fe",
      state: "NM",
      specialty: "Pecos River and Jemez Mountain wild trout, New Mexico front-range fly fishing specialist.",
      rivers: ["Pecos River", "Rio Chama", "Jemez River"],
      phone: "(505) 988-7688",
      website: "https://www.highdesertangler.com",
      priceRange: "$375-$550/day",
      lat: 35.6870,
      lng: -105.9378,
    },
  ],

  // ─── New York ────────────────────────────────────────────────────────────────
  NY: [
    {
      name: "Catskill Flies",
      location: "Roscoe",
      state: "NY",
      specialty: "The Beaverkill and Willowemoc, the birthplace of American fly fishing and home of the dry fly.",
      rivers: ["Beaverkill River", "Willowemoc River", "Delaware River"],
      phone: "(607) 498-6146",
      website: "https://www.catskillflies.com",
      priceRange: "$400-$575/day",
      lat: 41.9384,
      lng: -74.9998,
    },
    {
      name: "Salmon River Fly Box",
      location: "Pulaski",
      state: "NY",
      specialty: "World-famous Salmon River steelhead, Chinook, and coho salmon runs, drift boat and wade trips.",
      rivers: ["Salmon River", "Oswego River"],
      phone: "(315) 298-6177",
      website: "https://www.salmonriverflybox.com",
      priceRange: "$375-$550/day",
      lat: 43.5673,
      lng: -76.1283,
    },
    {
      name: "Battenkill Outfitters",
      location: "Arlington",
      state: "NY",
      specialty: "Battenkill River wild brown trout, storied Vermont/New York border stream dry fly fishing.",
      rivers: ["Battenkill River", "Hoosic River", "Walloomsac River"],
      phone: "(802) 379-9887",
      website: "https://www.battenkilloutfitters.com",
      priceRange: "$325-$475/day",
      lat: 43.0731,
      lng: -73.1540,
    },
  ],

  // ─── North Carolina ──────────────────────────────────────────────────────────
  NC: [
    {
      name: "Mac Brown Fly Fish",
      location: "Bryson City",
      state: "NC",
      specialty: "Western North Carolina's premier fly fishing school since 1987, Tuckasegee, Nantahala, and Smokies trout.",
      rivers: ["Tuckasegee River", "Nantahala River", "Oconaluftee River"],
      phone: "(828) 488-3232",
      website: "https://macbrownflyfish.com",
      priceRange: "$400-$600/day",
      lat: 35.4285,
      lng: -83.4515,
    },
    {
      name: "Brookings Anglers",
      location: "Cashiers",
      state: "NC",
      specialty: "Wild trout and smallmouth bass in the headwaters of the French Broad and Chattooga watersheds.",
      rivers: ["Whitewater River", "Thompson River", "Chattooga River"],
      phone: "(828) 743-3768",
      website: "https://www.brookingsanglers.com",
      priceRange: "$350-$525/day",
      lat: 35.1046,
      lng: -83.0941,
    },
    {
      name: "Fly Fishing the Smokies",
      location: "Gatlinburg (also Bryson City, NC)",
      state: "NC",
      specialty: "The Smokies' largest outfitter, all-inclusive guided trips for rainbow, brown, and brook trout.",
      rivers: ["Oconaluftee River", "Deep Creek", "Cataloochee Creek"],
      phone: "(828) 421-6378",
      website: "https://flyfishingthesmokies.net",
      priceRange: "$300-$450/day",
      lat: 35.4732,
      lng: -83.5015,
    },
  ],

  // ─── North Dakota ────────────────────────────────────────────────────────────
  ND: [
    {
      name: "Missouri River Guide Service ND",
      location: "Bismarck",
      state: "ND",
      specialty: "Walleye, sauger, and smallmouth bass on the Missouri River through central North Dakota.",
      rivers: ["Missouri River", "Heart River"],
      phone: "(701) 258-8145",
      website: "https://www.ndfishingguide.com",
      priceRange: "$275-$400/day",
      lat: 46.8083,
      lng: -100.7837,
    },
    {
      name: "Devils Lake Fishing Guide",
      location: "Devils Lake",
      state: "ND",
      specialty: "World-class perch, walleye, and pike on Devils Lake, the best perch fishing in North America.",
      rivers: ["Devils Lake"],
      phone: "(701) 662-5251",
      website: "https://www.devilslakefishing.com",
      priceRange: "$250-$375/day",
      lat: 48.1128,
      lng: -98.8651,
    },
    {
      name: "Sakakawea Bass & Walleye Guide",
      location: "Garrison",
      state: "ND",
      specialty: "Trophy walleye and smallmouth bass on Lake Sakakawea, one of the largest reservoirs in North America.",
      rivers: ["Lake Sakakawea", "Missouri River"],
      phone: "(701) 337-5615",
      website: "https://www.sakakawealake.com",
      priceRange: "$250-$375/day",
      lat: 47.6528,
      lng: -101.4167,
    },
  ],

  // ─── Ohio ────────────────────────────────────────────────────────────────────
  OH: [
    {
      name: "Mad River Fly Fishing Guide",
      location: "Urbana",
      state: "OH",
      specialty: "Ohio's best wild rainbow trout stream, year-round catch-and-release fishing on the Mad River.",
      rivers: ["Mad River", "Little Miami River"],
      phone: "(937) 652-1200",
      website: "https://www.madriverflyfishing.com",
      priceRange: "$250-$375/day",
      lat: 40.1084,
      lng: -83.7524,
    },
    {
      name: "Lake Erie Walleye Fishing Charter",
      location: "Port Clinton",
      state: "OH",
      specialty: "World-class walleye fishing in western Lake Erie, the 'Walleye Capital of the World'.",
      rivers: ["Lake Erie", "Sandusky Bay"],
      phone: "(419) 734-2141",
      website: "https://www.lakeeriefishingcharter.com",
      priceRange: "$450-$650/day",
      lat: 41.5134,
      lng: -82.9374,
    },
    {
      name: "Steelhead Alley Outfitters",
      location: "Geneva",
      state: "OH",
      specialty: "Lake Erie tributary steelhead, premium drift-boat and wade trips on the Grand, Chagrin, and Rocky Rivers.",
      rivers: ["Grand River", "Chagrin River", "Rocky River"],
      phone: "(440) 466-6882",
      website: "https://www.steelheadalleyoutfitters.com",
      priceRange: "$325-$500/day",
      lat: 41.8026,
      lng: -80.9476,
    },
  ],

  // ─── Oklahoma ────────────────────────────────────────────────────────────────
  OK: [
    {
      name: "Blue River Fly Fishing",
      location: "Tishomingo",
      state: "OK",
      specialty: "Oklahoma's best trout stream, rainbow trout in the Blue River spring-fed bottoms.",
      rivers: ["Blue River"],
      phone: "(580) 371-2258",
      website: "https://www.blueriverflyfishing.com",
      priceRange: "$225-$350/day",
      lat: 34.2381,
      lng: -96.6842,
    },
    {
      name: "Lake Texoma Fishing Guide",
      location: "Madill",
      state: "OK",
      specialty: "Trophy striped bass on Lake Texoma, the best striper lake in the country.",
      rivers: ["Lake Texoma", "Red River"],
      phone: "(580) 795-2100",
      website: "https://www.laketexomastriper.com",
      priceRange: "$300-$450/day",
      lat: 34.1042,
      lng: -96.7706,
    },
    {
      name: "Illinois River Canoe & Fishing",
      location: "Tahlequah",
      state: "OK",
      specialty: "Smallmouth bass and sunfish float trips on the Illinois River through Cherokee Nation lands.",
      rivers: ["Illinois River", "Baron Fork Creek"],
      phone: "(918) 456-7165",
      website: "https://www.illinoisriverfishing.com",
      priceRange: "$200-$300/day",
      lat: 35.9151,
      lng: -94.9699,
    },
  ],

  // ─── Oregon ──────────────────────────────────────────────────────────────────
  OR: [
    {
      name: "Deschutes Angler",
      location: "Maupin",
      state: "OR",
      specialty: "Lower Deschutes River steelhead and redside trout, camp float trips and walk-wade.",
      rivers: ["Deschutes River", "Grande Ronde River"],
      phone: "(541) 395-0995",
      website: "https://deschutesangler.com",
      priceRange: "$400-$600/day",
      lat: 45.1793,
      lng: -120.8259,
    },
    {
      name: "River Borne Outfitters",
      location: "Bend",
      state: "OR",
      specialty: "Year-round fly fishing on the Upper Deschutes for wild redside rainbow trout.",
      rivers: ["Upper Deschutes River", "Crooked River"],
      phone: "(541) 389-6208",
      website: "https://www.riverborneoutfitters.com",
      priceRange: "$375-$550/day",
      lat: 44.0582,
      lng: -121.3153,
    },
    {
      name: "Rain Coast Guides",
      location: "Forks, WA / Tillamook, OR",
      state: "OR",
      specialty: "Olympic Peninsula and North Coast Oregon steelhead, winter and summer runs on wild rivers.",
      rivers: ["Nestucca River", "Wilson River", "Siletz River"],
      phone: "(360) 374-5170",
      website: "https://raincoastguides.com",
      priceRange: "$400-$575/day",
      lat: 45.4557,
      lng: -123.8448,
    },
  ],

  // ─── Pennsylvania ────────────────────────────────────────────────────────────
  PA: [
    {
      name: "TCO Fly Shop & Guide Service",
      location: "State College",
      state: "PA",
      specialty: "Pennsylvania limestone spring creeks, Penns Creek, Spring Creek, and Falling Springs technical trout fishing.",
      rivers: ["Penns Creek", "Spring Creek", "Little Juniata River"],
      phone: "(814) 689-3654",
      website: "https://www.tcoflyfishing.com",
      priceRange: "$325-$500/day",
      lat: 40.7934,
      lng: -77.8600,
    },
    {
      name: "Delaware River Outfitters",
      location: "Dingmans Ferry",
      state: "PA",
      specialty: "Wild trout and smallmouth bass on the Upper Delaware River, Pennsylvania's premier float fishery.",
      rivers: ["Delaware River", "Brodhead Creek"],
      phone: "(570) 828-2705",
      website: "https://www.delawareriveroutfitters.com",
      priceRange: "$300-$475/day",
      lat: 41.2187,
      lng: -74.9057,
    },
    {
      name: "Yellow Breeches Outfitters",
      location: "Boiling Springs",
      state: "PA",
      specialty: "Cumberland Valley limestone stream trout, Yellow Breeches and Letort Spring Run.",
      rivers: ["Yellow Breeches Creek", "Letort Spring Run", "Big Spring Creek"],
      phone: "(717) 258-6752",
      website: "https://www.yellowbreeches.com",
      priceRange: "$300-$450/day",
      lat: 40.1453,
      lng: -77.1261,
    },
  ],

  // ─── Rhode Island ────────────────────────────────────────────────────────────
  RI: [
    {
      name: "Narragansett Bay Fishing Charters",
      location: "Newport",
      state: "RI",
      specialty: "Striped bass, bluefish, and false albacore in Narragansett Bay and Rhode Island Sound.",
      rivers: ["Narragansett Bay", "Sakonnet River"],
      phone: "(401) 848-2920",
      website: "https://www.narragansettfishingcharters.com",
      priceRange: "$500-$700/half-day",
      lat: 41.4901,
      lng: -71.3128,
    },
    {
      name: "Wood River Fly Fishing",
      location: "Hope Valley",
      state: "RI",
      specialty: "Wild brook and brown trout on the Wood River, Rhode Island's best inland trout stream.",
      rivers: ["Wood River", "Pawcatuck River"],
      phone: "(401) 539-2740",
      website: "https://www.woodriverflyfishing.com",
      priceRange: "$275-$400/day",
      lat: 41.5015,
      lng: -71.7215,
    },
    {
      name: "Block Island Saltwater Guide",
      location: "Block Island",
      state: "RI",
      specialty: "Striped bass and false albacore surf fishing around Block Island from July through October.",
      rivers: ["Block Island Sound", "Great Salt Pond"],
      phone: "(401) 466-2654",
      website: "https://www.blockislandfishing.com",
      priceRange: "$500-$700/half-day",
      lat: 41.1696,
      lng: -71.5773,
    },
  ],

  // ─── South Carolina ──────────────────────────────────────────────────────────
  SC: [
    {
      name: "Lowcountry Fly Fishing",
      location: "Charleston",
      state: "SC",
      specialty: "Redfish, spotted seatrout, and tarpon in the ACE Basin, premier Lowcountry saltwater fly fishing.",
      rivers: ["ACE Basin", "Combahee River", "Edisto River"],
      phone: "(843) 881-3645",
      website: "https://www.lowcountryflyfishing.com",
      priceRange: "$450-$650/day",
      lat: 32.7765,
      lng: -79.9311,
    },
    {
      name: "Upstate Fly Fishing",
      location: "Clemson",
      state: "SC",
      specialty: "Wild brown and rainbow trout on the Chattooga and Chauga Rivers in the Blue Ridge escarpment.",
      rivers: ["Chattooga River", "Chauga River", "Keowee River"],
      phone: "(864) 654-5900",
      website: "https://www.upstateflyfishing.com",
      priceRange: "$300-$450/day",
      lat: 34.6834,
      lng: -82.8374,
    },
    {
      name: "Santee Cooper Bass Fishing Guide",
      location: "Manning",
      state: "SC",
      specialty: "Trophy largemouth bass and striped bass on Lake Marion and Lake Moultrie.",
      rivers: ["Lake Marion", "Lake Moultrie", "Santee River"],
      phone: "(803) 435-4500",
      website: "https://www.santeecooperbassguide.com",
      priceRange: "$300-$450/day",
      lat: 33.6957,
      lng: -80.2126,
    },
  ],

  // ─── South Dakota ────────────────────────────────────────────────────────────
  SD: [
    {
      name: "Black Hills Fly Fishing",
      location: "Custer",
      state: "SD",
      specialty: "Wild brown and rainbow trout in the spring creeks and limestone streams of the Black Hills.",
      rivers: ["Rapid Creek", "French Creek", "Spearfish Creek"],
      phone: "(605) 673-4664",
      website: "https://www.blackhillsflyfishing.com",
      priceRange: "$275-$425/day",
      lat: 43.7667,
      lng: -103.5987,
    },
    {
      name: "Big Bend Resort Fishing Guide",
      location: "Chamberlain",
      state: "SD",
      specialty: "Trophy walleye and sauger on the Missouri River, the best walleye stretch between the Dakotas.",
      rivers: ["Missouri River", "Lake Sharpe"],
      phone: "(605) 734-5548",
      website: "https://www.bigbendresort.com",
      priceRange: "$275-$400/day",
      lat: 43.7997,
      lng: -99.3256,
    },
    {
      name: "Oahe Walleye Guide",
      location: "Pierre",
      state: "SD",
      specialty: "Walleye, pike, and smallmouth bass on Lake Oahe, one of the largest reservoirs in the United States.",
      rivers: ["Lake Oahe", "Missouri River"],
      phone: "(605) 224-8605",
      website: "https://www.oahefishing.com",
      priceRange: "$250-$375/day",
      lat: 44.3683,
      lng: -100.3510,
    },
  ],

  // ─── Tennessee ───────────────────────────────────────────────────────────────
  TN: [
    {
      name: "Fly Fishing the Smokies",
      location: "Gatlinburg",
      state: "TN",
      specialty: "All-inclusive guided trips in the Great Smoky Mountains for brook, rainbow, and brown trout.",
      rivers: ["Little Pigeon River", "West Prong", "Middle Prong"],
      phone: "(828) 421-6378",
      website: "https://flyfishingthesmokies.net",
      priceRange: "$300-$450/day",
      lat: 35.7143,
      lng: -83.5102,
    },
    {
      name: "Clinch River Fly Shop",
      location: "Clinton",
      state: "TN",
      specialty: "Wild rainbow and brown trout on the Clinch River tailwater below Norris Dam.",
      rivers: ["Clinch River", "Holston River"],
      phone: "(865) 457-3233",
      website: "https://www.clinchriverflyfishing.com",
      priceRange: "$275-$425/day",
      lat: 36.0979,
      lng: -84.1318,
    },
    {
      name: "Caney Fork River Guide",
      location: "Cookeville",
      state: "TN",
      specialty: "Tailwater trophy trout on the Caney Fork River below Center Hill Dam.",
      rivers: ["Caney Fork River"],
      phone: "(931) 646-0100",
      website: "https://www.caneyforkriverguide.com",
      priceRange: "$275-$400/day",
      lat: 36.1626,
      lng: -85.5016,
    },
  ],

  // ─── Texas ───────────────────────────────────────────────────────────────────
  // CRITICAL: Both entries below are required with exact field values.
  TX: [
    {
      name: "Hill Country Fly Fishers",
      location: "New Braunfels",
      state: "TX",
      specialty: "Guadalupe River trout and Hill Country bass, the best guide operation on Texas water.",
      rivers: ["Guadalupe River", "South Llano River"],
      phone: "(830) 708-7863",
      website: "https://www.hillcountryflyfishers.com",
      priceRange: "$350-$500/day",
      lat: 29.7030,
      lng: -98.1245,
    },
    {
      name: "Texas Fly Fishing & Brew Fest",
      location: "Austin",
      state: "TX",
      specialty: "Hill Country rivers guide service, Guadalupe bass, trout, and warm-water species.",
      rivers: ["Pedernales River", "Frio River", "Colorado River"],
      phone: "(512) 555-0190",
      website: "https://www.txflyfishing.com",
      priceRange: "$300-$450/day",
      lat: 30.2672,
      lng: -97.7431,
    },
    {
      name: "Galveston Bay Fly Fishing",
      location: "Galveston",
      state: "TX",
      specialty: "Sight-fishing for redfish, speckled trout, and flounder in Galveston Bay flats.",
      rivers: ["Galveston Bay", "Trinity Bay", "San Luis Pass"],
      phone: "(409) 740-7526",
      website: "https://www.galvestonbayflyfishing.com",
      priceRange: "$400-$600/day",
      lat: 29.3013,
      lng: -94.7977,
    },
  ],

  // ─── Utah ────────────────────────────────────────────────────────────────────
  UT: [
    {
      name: "Trout Bum 2",
      location: "Park City",
      state: "UT",
      specialty: "Provo River and Weber River wild rainbow and brown trout, Utah's best trout guide service.",
      rivers: ["Provo River", "Weber River", "Green River"],
      phone: "(435) 658-1166",
      website: "https://www.troutbum2.com",
      priceRange: "$400-$575/day",
      lat: 40.6461,
      lng: -111.4980,
    },
    {
      name: "Flaming Gorge Guides",
      location: "Dutch John",
      state: "UT",
      specialty: "World-class Green River tailwater below Flaming Gorge Dam, trophy brown and rainbow trout.",
      rivers: ["Green River"],
      phone: "(435) 885-3338",
      website: "https://www.flaminggorgedam.com",
      priceRange: "$425-$600/day",
      lat: 40.9252,
      lng: -109.4099,
    },
    {
      name: "Moab Guide Service",
      location: "Moab",
      state: "UT",
      specialty: "Colorado and Green River smallmouth bass and carp in canyon country.",
      rivers: ["Colorado River", "Green River"],
      phone: "(435) 259-7983",
      website: "#",
      priceRange: "$350-$500/day",
      lat: 38.5733,
      lng: -109.5498,
    },
  ],

  // ─── Vermont ─────────────────────────────────────────────────────────────────
  VT: [
    {
      name: "Vermont Fly Fishers",
      location: "Arlington",
      state: "VT",
      specialty: "Battenkill River wild brown trout and Common Carp, Southern Vermont's premier guide service.",
      rivers: ["Battenkill River", "Hoosic River", "Mettawee River"],
      phone: "(802) 375-6673",
      website: "https://www.vermontflyfishers.com",
      priceRange: "$300-$450/day",
      lat: 43.0731,
      lng: -73.1540,
    },
    {
      name: "The Fly Rod Shop",
      location: "Stowe",
      state: "VT",
      specialty: "Full-service Stowe-area guided trips on the Lamoille, Winooski, and Dog Rivers for trout and bass.",
      rivers: ["Lamoille River", "Winooski River", "Dog River"],
      phone: "(802) 253-7346",
      website: "https://www.flyrodshop.com",
      priceRange: "$275-$425/day",
      lat: 44.4654,
      lng: -72.6874,
    },
    {
      name: "Stream and Brook Fly Fishing",
      location: "Middlebury",
      state: "VT",
      specialty: "Wild trout and Northern Pike on Otter Creek and central Vermont spring creeks.",
      rivers: ["Otter Creek", "New Haven River", "Middlebury River"],
      phone: "(802) 388-6869",
      website: "https://streamandbrook.com",
      priceRange: "$275-$400/day",
      lat: 44.0153,
      lng: -73.1673,
    },
  ],

  // ─── Virginia ────────────────────────────────────────────────────────────────
  VA: [
    {
      name: "Shenandoah River Outfitters",
      location: "Luray",
      state: "VA",
      specialty: "Smallmouth bass and native brook trout float trips on the North Fork of the Shenandoah River.",
      rivers: ["Shenandoah River", "North Fork Shenandoah"],
      phone: "(540) 743-4159",
      website: "https://www.shenandoahriver.com",
      priceRange: "$300-$450/day",
      lat: 38.6651,
      lng: -78.4594,
    },
    {
      name: "New River Fly Fishing",
      location: "Radford",
      state: "VA",
      specialty: "Wild smallmouth bass and muskie on the New River, one of the oldest rivers in the world.",
      rivers: ["New River"],
      phone: "(540) 731-4011",
      website: "https://www.newriverflyfishing.com",
      priceRange: "$275-$425/day",
      lat: 37.1318,
      lng: -80.5765,
    },
    {
      name: "Virginia Highland Fly Fishing",
      location: "Abingdon",
      state: "VA",
      specialty: "Native brook trout in the wild headwaters of the Holston and Clinch Rivers in Southwest Virginia.",
      rivers: ["North Fork Holston", "Clinch River", "Laurel Creek"],
      phone: "(276) 628-3826",
      website: "https://www.vahighlandflyfishing.com",
      priceRange: "$275-$400/day",
      lat: 36.7096,
      lng: -82.0021,
    },
  ],

  // ─── Washington ──────────────────────────────────────────────────────────────
  WA: [
    {
      name: "Snake River Angler",
      location: "Jackson Hole (Teton area / WA access)",
      state: "WA",
      specialty: "Winter steelhead on the Olympic Peninsula rivers and summer salmon on the Olympic coast.",
      rivers: ["Hoh River", "Sol Duc River", "Quinault River"],
      phone: "(307) 733-3699",
      website: "https://snakeriverangler.com",
      priceRange: "$450-$650/day",
      lat: 47.9035,
      lng: -124.1671,
    },
    {
      name: "Olympic Peninsula Guide Service",
      location: "Forks",
      state: "WA",
      specialty: "World-class steelhead and king salmon on the wild rivers of the Olympic Peninsula year-round.",
      rivers: ["Hoh River", "Bogachiel River", "Calawah River", "Sol Duc River"],
      phone: "(360) 374-9009",
      website: "https://www.olympicpeninsulaguideservice.com",
      priceRange: "$375-$575/day",
      lat: 47.9535,
      lng: -124.3968,
    },
    {
      name: "Brazda's Fly Fishing",
      location: "Tacoma",
      state: "WA",
      specialty: "Trout, salmon, and trophy winter steelhead on Washington's Olympic Peninsula and Puget Sound rivers.",
      rivers: ["Yakima River", "Green River", "Skykomish River"],
      phone: "(253) 307-3210",
      website: "https://brazdasflyfishing.com",
      priceRange: "$350-$525/day",
      lat: 47.2529,
      lng: -122.4443,
    },
  ],

  // ─── West Virginia ───────────────────────────────────────────────────────────
  WV: [
    {
      name: "Elk River Fly Fishing",
      location: "Slatyfork",
      state: "WV",
      specialty: "Wild brown trout on the Elk River and Back Fork of the Elk, West Virginia's top trout fishery.",
      rivers: ["Elk River", "Cranberry River"],
      phone: "(304) 572-3771",
      website: "https://www.elkriverinn.com",
      priceRange: "$300-$450/day",
      lat: 38.5379,
      lng: -80.1587,
    },
    {
      name: "Greenbrier River Fishing Guide",
      location: "Lewisburg",
      state: "WV",
      specialty: "Smallmouth bass and wild rainbow trout on the Greenbrier River through Greenbrier County.",
      rivers: ["Greenbrier River", "Anthonys Creek"],
      phone: "(304) 645-6290",
      website: "#",
      priceRange: "$275-$400/day",
      lat: 37.8026,
      lng: -80.4453,
    },
    {
      name: "New River Gorge Guide Service",
      location: "Fayetteville",
      state: "WV",
      specialty: "Smallmouth bass and muskie float trips through the New River Gorge National Park.",
      rivers: ["New River", "Gauley River"],
      phone: "(304) 574-0704",
      website: "https://www.newrivergorguide.com",
      priceRange: "$300-$450/day",
      lat: 38.0568,
      lng: -81.1040,
    },
  ],

  // ─── Wisconsin ───────────────────────────────────────────────────────────────
  WI: [
    {
      name: "Driftless Angler",
      location: "Viroqua",
      state: "WI",
      specialty: "Wild brown trout on the Driftless Area spring creeks, the epicenter of Wisconsin limestone stream fishing.",
      rivers: ["Timber Coulee Creek", "Seas Branch", "Kickapoo River"],
      phone: "(608) 637-8779",
      website: "https://driftlessangler.com",
      priceRange: "$300-$450/day",
      lat: 43.5569,
      lng: -90.8843,
    },
    {
      name: "Black Earth Angling",
      location: "Black Earth",
      state: "WI",
      specialty: "Guided Driftless Area spring creek trout fishing, private water access and expert instruction.",
      rivers: ["Black Earth Creek", "Vermont Creek", "Garfoot Creek"],
      phone: "(608) 767-3422",
      website: "https://www.blackearthangling.com",
      priceRange: "$325-$475/day",
      lat: 43.1389,
      lng: -89.7400,
    },
    {
      name: "Feather Thief Fly Fishing",
      location: "Westby",
      state: "WI",
      specialty: "Northern Driftless spring creek brown trout with expert guide Scott Harness.",
      rivers: ["Coon Creek", "Bohemian Valley Creek", "Timber Coulee Creek"],
      phone: "(608) 634-2212",
      website: "https://www.featherthief.com",
      priceRange: "$275-$425/day",
      lat: 43.6652,
      lng: -90.8582,
    },
  ],

  // ─── Wyoming ─────────────────────────────────────────────────────────────────
  WY: [
    {
      name: "Snake River Angler",
      location: "Jackson",
      state: "WY",
      specialty: "Jackson Hole's premier fly shop and guide service, Snake River cutthroat, Yellowstone Park trips.",
      rivers: ["Snake River", "Green River", "Salt River"],
      phone: "(307) 733-3699",
      website: "https://snakeriverangler.com",
      priceRange: "$500-$700/day",
      lat: 43.4799,
      lng: -110.7624,
    },
    {
      name: "Teton Anglers",
      location: "Jackson Hole",
      state: "WY",
      specialty: "20+ years guiding the Snake, Salt, and Green rivers, no-pretension expert local knowledge.",
      rivers: ["Snake River", "Salt River", "Green River"],
      phone: "(307) 413-8550",
      website: "https://www.teton-anglers.com",
      priceRange: "$525-$700/day",
      lat: 43.4799,
      lng: -110.7624,
    },
    {
      name: "Greater Yellowstone Outfitters",
      location: "Cody",
      state: "WY",
      specialty: "Blue-ribbon Yellowstone Park rivers and Shoshone River, cutthroat, brown, and rainbow trout.",
      rivers: ["Yellowstone River", "Shoshone River", "North Fork Shoshone"],
      phone: "(816) 591-3535",
      website: "https://www.greateryellowstoneoutfitters.com",
      priceRange: "$500-$700/day",
      lat: 44.5263,
      lng: -109.0565,
    },
  ],

};

/**
 * Returns all guides for the given state abbreviation (case-insensitive).
 * Returns an empty array if no guides are found.
 */
export function getGuidesForState(abbr: string): FishingGuide[] {
  return guidesByState[abbr.toUpperCase()] ?? [];
}
